### ISSUE TITLE
Independence from libfm

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1033]
In the last few months, I saw that some libfm-qt methods and functions, which were based on libfm, could be replaced by Qt-only ones. Naturally, it occurred to me that maybe libfm-qt could be rewritten so that it would be independent from libfm and hence, from GLib. That may not be achievable easily at all.

Therefore, I took the liberty of opening this discussion tracker. All ideas are welcome, whether they be general or technical. Is this a good idea? Does it have any advantage? Could it be achieved? At once or step by step? In a backward compatible way or not? Should we start from those apps that are based on libfm-qt or from libfm-qt itself?...

**Comment by agaida** [comment]
Only my two cents, we should do this step by step if it make things easier for further development.

**Comment by PCMan** [comment]
I totally understand your concerns and it's quite natural for C++/Qt programmers to choose pure C++ solutions, but if you step back and think it twice, you might change your mind. Sharing libfm/glib between the gtk+ and Qt version is actually by design. That's a careful design decision made at the beginning.
Warning: Something very technical ahead.

Performance consideration:
Loading C libraries is significantly faster than C++ ones which provide the same features because of the nature of C++. To support the rich-features provided by C++, one C++ class generates much more long symbols in your dynamic library then you think. Try to use a profiler, and you'll be surprised that most of the startup time is spent in do_lookup_x() resolving the C++ symbols, which is part of ld.so. There is no way to optimize this part.
FYI: http://www.macieira.org/blog/2012/01/sorry-state-of-dynamic-libraries-on-linux/
This is from the lead developer of Qt.
So if you have two libraries offering the same features, I tend to choose the one written in C if it's easy to use. All C++ programmers should know C well. So there is no problem.

Dependency:
glib is an essential part of modern desktop system. Both systemd and some necessary system dbus services, such as udisks and upower, are using it, too. So you can never get rid of the dependency. On the other hand, this dependency is "free" of charge since it's already installed in the system and almost always loaded in memory already. The .text segment of the dynamic library is shared by all processes so this saves memory. By avoiding glib, it looks like you decrease the dependency, but actually you get nothing. Memory usage might actually increase in some cases.

glib/gio provides support for remote filesystems and various useful virtual filesystems, such as mtp, and gphoto. But since it's modular, you don't need to install these modules/backends if you don't need them. The alternative to this feature is KIO/Slave, which does not offer this kind of modularity and is more bloated. That's why we use gio here. No to say it's actully "desktop independent". No, it does not require Gnome at all. It's just a set of C libraries and dbus services.

Software engineering:
1. Reusing existing code that is well tested and maintained is a good idea.
2. Though it's in C, libfm/GObject is fully object-oriented.
3. glib provides very good xdg implementations and it's rapidly updated. I know that we have QtXdg, but since the existing code using glib works as well, there is no need to "fix" it.
4. Never fix things that are not broken.

The proposed alternative:
1. Generate C++ wrappers for the C structs and APIs with the help of ctags and some simple python scripts. Most of the C APIs can be wrapped in C++ inline methods so this won't increase the overhead of dynamic linking while you can still write C++ only.

2. For those objects with glib signal emission, wrap them in QObject wrappers. Again this can be generated automatically.

3. This kind of technique is used by gtkmm, which is a C++ wrapper for GTK+.

Just my two cents

**Comment by PCMan** [comment]
To get the symbols from a C header file, try this:
ctags --c++-kinds=+p <file path to the *.h file>
Then you'll see a list of all structs, macros, and functions, for which C++ wrapper can be generated automatically. Since libfm follows strict naming convention, this approach is quite feasible and can be a good alternative to a complete rewrite. Or, if you really love a complete C++ rewrite, this provides quite reasonable transition.

**Comment by tsujan** [comment]
@PCMan 
Thank you very much for this detailed information! It should be read and re-read. You're absolutely right.

I know how valuable libfm is. I've come from GTK+ to Qt. ~5 years ago, when someone asked which one was better, the answer was, "both are good; choose the one you prefer!" However, as you surely know, after Gnome3 everything changed. My real concern is that, AFAIK, GLib is being developed by Gnome and, since its v3, *Gnome has proven that it doesn't care about others.* I just can't trust them after what they did (and are still doing) to GTK+.

**Comment by tsujan** [comment]
In other words, the whimsical attitude of Gnome may affect GLib. *This* is my concern. Otherwise, I completely agree with you.

**Comment by agaida** [comment]
@tsujan - i guess we can close this now?

**Comment by tsujan** [comment]
Oh, yes, this should be closed. And my mind has changed a lot about it since that time.
