### ISSUE TITLE
LXQT Desktop affects behaviour of Conky

### ISSUE THREAD

**Issue by LonCJr** [lxqt/lxqt#107]
https://github.com/lxde/lxde-qt/issues/91

When setting a margin in Openbox/rc.xml Conky is also excluded from displaying in the margin area.

Only solution I've found is to disable the Desktop module from auto-starting and add a 3rd party app for setting wallpaper.

**Comment by je-vv** [comment]
same behavior with lxqt+fluxbox, only work around is to disable the desktop module as well

**Comment by je-vv** [comment]
btw, wow, this is 4 years old already, :-1:

**Comment by tsujan** [comment]
I always use Conky with LXQt+desktop module and have never had a problem. IMO, Conky's problem are either about Conky's bad settings or about the window manager, none of which is related to LXQt.

**Comment by tsujan** [comment]
A part of my Conky's rc file:
```
	own_window = true,
	own_window_class = 'Conky',
	own_window_type = 'normal',
	own_window_transparent = false,
	own_window_argb_visual = true,
	own_window_argb_value = 0,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	double_buffer = true,
```

**Comment by je-vv** [comment]
My conky relevant settings are equivalent to yours (you can read the conky documentation), and Iv'e tried yours as well.  Results on the same behavior.  Now, how come a window manager thing?  I've always used fluxbox + feh + conky (even before lxqt, and then with lxqt but without desktop module) with no problem, conky works.  I just wanted to enable the desktop module, to find out it overrides the wallpaper (fine, setting the one I want on lxqt is OK, but it would have been nice an "unset"), and conky easily goes away (I haven't found a workaround).  I've also tried not setting a wallpaper on fluxbox (unset) and that doesn't help either.

I really don't understand how come there's nothing wrong if it doesn't work.  Probably you're using openbox, and that's the way to make it work, but then lxqt is meant to work with different WMs, isn't it?

BTW, forgot to mention:

liblxqt 0.13.0-1
lxqt-session 0.13.0-1
pcmanfm-qt 0.13.0-1

Any way to get information on what I'm missing?  conky doesn't show any error message, or similar.  It just doesn't show up anymore...

Thanks !

**Comment by tsujan** [comment]
> My conky relevant settings are equivalent to yours

Obviously, it isn't.

> I really don't understand how come there's nothing wrong if it doesn't work.

Who said there's nothing wrong? Read my reply again.

**Comment by tsujan** [comment]
> Probably you're using openbox

Conky has worked OK here with openbox, KWin and Compiz-reloaded. Instead of wasting your time with the hypothesis that the problem is in LXQt, I recommend you play with Conky.

**Comment by je-vv** [comment]
I owe you an apology.  I thought I tried all combinations, and the one you shared was equivalent to the one I showed, but I was mistaken as you clarified.  I understood normal with all those hints was the same as desktop, and no transparency with no opacity was the same as transparent, but all that was an error...

You were right, and your configuration actually worked out.

So perhaps someone else might find this closed issue helpful, since your shared config, rocks with LXQT, and even with fluxbox as its WM...

Thanks !

**Comment by tsujan** [comment]
It's OK. There have been places where I thought Conky wouldn't work but it started to work fine after changing some of its variables.

**Comment by QiangF** [comment]
@tsujan Can you please share your full configuration?
I tried set own_window_type to 'normal',  when press Windows-D to show desktop, cocky window is gone.
There must be something on LXQT that prevent the 'desktop' option to work.

My config is https://gist.github.com/QiangF/9ee71581ad70afe3fd6d944c05435724
> A part of my Conky's rc file:
> 
> ```
> 	own_window = true,
> 	own_window_class = 'Conky',
> 	own_window_type = 'normal',
> 	own_window_transparent = false,
> 	own_window_argb_visual = true,
> 	own_window_argb_value = 0,
> 	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
> 	double_buffer = true,
> ```

**Comment by QiangF** [comment]
This seems to work:

    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,top',

**Comment by tsujan** [comment]
This has worked for me everywhere and with any WM (even under Wayfire):

```
conky.config = {
	background = false,
	font = 'Sans:bold:size=8',
	use_xft = true,
	xftalpha = 1.0,
	update_interval = 1.0,
	total_run_times = 0,
	own_window = true,
	own_window_class = 'Conky',
	own_window_type = 'normal',
	own_window_transparent = false,
	own_window_argb_visual = true,
	own_window_argb_value = 0,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	double_buffer = true,
	draw_shades = true,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = true,
	default_color = 'white',
	default_shade_color = 'black',
	default_outline_color = 'green',
	no_buffers = true,
	uppercase = false,
	cpu_avg_samples = 2,
	override_utf8_locale = true,
	-- and so on....
};
```

**Comment by tsujan** [comment]
> There must be something on LXQT that prevent the 'desktop' option to work.

No, the WM does it.

With KWin, it has become worse recently: Conky is shown when presenting windows too. There are Conky confiigs that circumvent some WM annoyances but they may create other problems. For example, I remember that `own_window_type = 'desktop'` had serious problems with KWin.

**Comment by Bluey26** [comment]
Hello.

This thread is a bit old, but since i was having problems with LXQt and Conky, specifically with the 'show desktop' function, i started to search on what to do to keep conky properly showing, after pressing 'show desktop' and to also keep conky in the desktop window, even if you use the 'select' (hovering the mouse and move the mouse over the screen) function.

To do this i received some help in the LXQt Matrix room, and also a bit was obtained from the web, so its just a 'collage' of code.

This consists on 'replacing' or using another script to show the desktop, not the one triggered by CTRL+D or the 'widget' coming with LXQT.

First of all, i use this configs in my `conky.conf`

```
background = true,
own_window = true,
own_window_class = 'Conky',
own_window_type = 'normal',
own_window_colour = 'black',
own_window_transparent = false,
own_window_argb_visual = true,
own_window_argb_value = 90,
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
```

This makes my window transparent, but `argb_value = 90` makes a light black background which produces a comfortable contrast with backgrounds, allowing you to use backgrounds normally, not using only those which makes you see the conky stats properly.

The script for 'show desktop' is the following one:

```
#!/usr/bin/env bash

if [ $(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | sed -e 's/.*"\(.*\)".*/\1/') == "pcmanfm-desktop0" ]; then
	xprop -root|grep "^_NET_CLIENT_LIST_STACKING" | tr "," " " | wmctrl -ia $(awk '{print $(NF-1)}')
			
else
	wmctrl -k on
	wmctrl -a Conky
fi
```
In the first part, it will check if the current active window is the `pcmanfm-desktop0`, which is the one where conky is displayed normally. It also makes, after some code, to 'load' in screen the n-1 window opened, which matches the 'last opened window', the behavior that has the 'Show Desktop' LXQt plugin.
It load N-1 because N was the last one, which is conky.

The 'else' statement does show the desktop, in those cases in where there is another window, which does not match 'pcmanfm-desktop0'

For this to run, you need to have installed `xorg-xprop` and `wmctrl`
You have to create a .sh file with that code, then making a .desktop file pointing to that .sh, here is mine:

```
[Desktop Entry]
Name=Show Desktop
GenericName=
Comment=
Exec=POINT-TO-.SH-FILE
Type=Application
Icon=org.kde.plasma.showdesktop
Terminal=false
```
Replace the `POINT-TO-.SH-FILE` for the location of the .sh file.

Then, tick 'trust the executable' for the .desktop file created, and place it into the desktop.
After that, drop the .desktop in the quicklaunch bar. I suggest you to logout, and then log-in and try if it works.
Sometimes the script gets buggy(mostly when conky crash or the conky.config file is modified), not working properly. For solve it, logout and login solves the problem.

Keep in mind that this relies on using xorg (xprop). At the moment, it does not work, for example, under lxqt-labwc-session (which uses xwayland), feel free to improve and modify the script, so this will not work when using xwayland, as far as i know.

I also attach a video to show how does it looks, and the behavior. Keep in mind that i have hidden the icons on my screen, but 'Show Desktop' .desktop file is present in the screen.
I am not a programmer, so the code may be a bit 'clumsy', but it does what is needed to do.

Bluey.


https://github.com/lxqt/lxqt/assets/143142826/9bcb48a7-5d59-4385-9c18-4ad8f788ac15

**Comment by tsujan** [comment]
> it does not work, for example, under lxqt-labwc-session

With LabWC I use (having `own_window_class = 'Conky'` in my `conkyrc`)

```xml
    <windowRule identifier="Conky">
      <skipTaskbar>yes</skipTaskbar>
      <skipWindowSwitcher>yes</skipWindowSwitcher>
      <noFocus>yes</noFocus>
      <action name="MoveTo" x="1730" y="37" />
    </windowRule>
```

Of course, the values of `MoveTo` depend on Conky's size and position. I tolerate its being shown only on one desktop — unfortunately, `ToggleAlwaysOnBottom` can't be used with Conky because it would make Conky go behind PCManFM-Qt's desktop once the desktop is clicked, but there's an open LabWC report about decoupling stickiness from `ToggleAlwaysOnBottom`.
