### ISSUE TITLE
Translations not shown for "User Directories"

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1107]
Translations from line 300 on in lxqt-config-session_it.ts (and all others too I guess) are not applied, see screenshot.

 `<context>
    <name>UserLocationsPrivate</name>
    <message>
        <location filename="../../../userlocationspage.cpp" line="60"/>
        <source>Desktop</source>
        <translation>Desktop</translation>
    </message>
    <message>
        <location filename="../../../userlocationspage.cpp" line="61"/>
        <source>Downloads</source>
        <translation>Scaricamenti</translation>
...`

![schermata03](https://cloud.githubusercontent.com/assets/10681413/17332880/a6bf1ce4-58d0-11e6-9d1c-3513790b0894.png)
(https://cloud.githubusercontent.com/assets/10681413/17332880/a6bf1ce4-58d0-11e6-9d1c-3513790b0894.png)

**Comment by pmattern** [comment]
If I'm not mistaken this is because lots of translations went missing when the TS files were updated to reflect changes in the actual code.
This is something that takes place on a regular basis and I've been wondering for a long time whether it cannot be avoided somehow as it basically means a lot of superfluous work. But it seems it can't as the problem is the very same in many other projects making use of the Qt translation system as well.

Right now it is affecting many languages and not limited to `lxqt-config-session`, see e. g. search for Italian (invoked in a checkout of repository "translations"):
```
$ find . -type f -iname '*_it*' -print0 | xargs -0 grep -l unfinished 
./obconf-qt/obconf-qt_it.ts
./lxqt-powermanagement/lxqt-config-powermanagement/lxqt-config-powermanagement_it.ts
./lxqt-sudo/lxqt-sudo_it.ts
./libfm-qt/libfm-qt_it.ts
./lxqt-session/lxqt-config-session/lxqt-config-session_it.ts
./lximage-qt/lximage-qt_it.ts
./lxqt-about/lxqt-about_it_IT.ts
./lxqt-config/lxqt-config-appearance/lxqt-config-appearance_it.ts
./lxqt-config/lxqt-config-monitor/lxqt-config-monitor_it.ts
./lxqt-panel/plugin-mount/mount_it.ts
./lxqt-panel/plugin-volume/volume_it.ts
./lxqt-panel/panel/lxqt-panel_it.ts
./lxqt-panel/plugin-sysstat/sysstat_it.ts
./lxqt-panel/plugin-spacer/spacer_it.ts
./lxqt-panel/plugin-worldclock/worldclock_it.ts
```

**Comment by agaida** [comment]
https://github.com/lxqt/lxqt-session/blob/master/lxqt-config-session/userlocationspage.cpp#L60-L67
^^ @luis-pereira could you please have a look?

**Comment by palinek** [comment]
> https://github.com/lxqt/lxqt-session/blob/master/lxqt-config-session/userlocationspage.cpp#L60-L67

@agaida here you go lxqt/lxqt-session#157
