### ISSUE TITLE
Lxqt-sudo changes config permissions

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1138]
I tried lxqt-sudo for the first time and encountered this bug: Use `lxsudo lxmage-qt`, _for example_, and the file `/.config/lximage-qt/settings.conf` will be owned by root. That's while `sudo` doesn't change the permission.

Fortunately, this doesn’t happen with pcmanfm-qt but the user config is used in this case too (while the root config should be used logically).

The bug seemed so serious to me that I uninstalled lxqt-sudo for now.

**Comment by Vladimir-csp** [comment]
Judging by description, lxqt-sudo runs `sudo` instead of `sudo -H`.

**Comment by tsujan** [comment]
> Judging by description, lxqt-sudo runs sudo instead of sudo -H.

But `sudo lximage-qt` is OK.

**Comment by Vladimir-csp** [comment]
Environment differs significantly. There were already an issue here somewhere about proper sanitation of sudo environment in lxqt-sudo.

```
sudo env > /tmp/sudo_env
lxqt-sudo env 2> /tmp/lxqt-sudo_env # BTW why does it output everything to stderr?
diff /tmp/sudo_env /tmp/lxqt-sudo_env
```

**Comment by Vladimir-csp** [comment]
#899

**Comment by tsujan** [comment]
@Vladimir-csp, you're right, they're very different. `XDG_CONFIG_HOME`, among others, is set to `/.config` for lxqt-sudo! `HOME` is user's home too.

**Comment by tsujan** [comment]
I fixed the problem for myself by adding the following lines to @palinek's `env_workarounds()`:
````
        unsetenv("XDG_DATA_HOME");
        setenv("HOME", "/root", 1);
        unsetenv("XDG_CONFIG_HOME");
        unsetenv("XDG_CACHE_HOME");
        unsetenv("XDG_DATA_DIRS");
````
However, since I didn't know it's good for all, I didn't make a PR.

**Comment by palinek** [comment]
Have a try with the lxde/lxqt-sudo#22...

**Comment by tsujan** [comment]
@palinek 

I didn't have time to read https://github.com/lxde/lxqt-sudo/pull/22 but after trying it, `lxsudo PROGRAM` gave:
````
sudo: PROGRAM: command not found
````
for any PROGRAM.

Although I tried it under Enlightenment, https://github.com/lxde/lxqt/issues/1138#issuecomment-246129588 worked well there. Back to my workaround for now.

**Comment by tsujan** [comment]
It seems this is still a dangerous issue: https://github.com/lxde/lxqt/issues/1436.

Since my last comment here, I've used my patch with `lxqt-sudo` and had no problem with user configs.

[lxqt-sudo.diff.zip](https://github.com/lxde/lxqt/files/1636896/lxqt-sudo.diff.zip)

**Comment by agaida** [comment]
right, if we don't find somehow who has a deeper understanding of the su(do) things we are forced to become experts and gain the needed knowledge

**Comment by aleex5** [comment]
@tsujan
change the file permissions with the "chown" and "chgrp" commands
and restart the computer and everything went back to normal

PD: pity that I can only help with bug reports or give ideas

![1](https://user-images.githubusercontent.com/35360938/35015147-795257c8-fae9-11e7-874b-d4e46915278a.png)

**Comment by tsujan** [comment]
> pity that I can only help with bug reports

Bug reports are an important part of the process. Your reports are very appreciated.

**Comment by tsujan** [comment]
@agaida I'm no sudo expert but I'm sure that:

(1) lxqt-sudo is dangerous in its current form, as it was when I opened this issue. Actually, lxqt-sudo hasn't changed since then.

(2) `XDG_CONFIG_HOME` should be unset, as in the patch. The other variables in the patch are for the sake of certainty. It not only worked in that time (2016) and under Debian but also works now and under Manjaro.

(3) @palinek's patches didn't work in that time (2016).

**Comment by stefonarch** [comment]
Just compiled  3) https://github.com/lxde/lxqt-sudo/pull/22 and  it works fine with lximage-qt here, when changing settings  /root/.config is used while before it messed up ~/.config as described.

**Comment by palinek** [comment]
> (3) palinek's patches didn't work in that time (2016).

To be precise...the lxde/lxqt-sudo#22 did the job, but your comment began a discussion if:
- env. should be kept, but some "well known vars" should be stripped
- or env. sholud be stripped except som "well known wars"
... and nobody made the decission since then.

Now I've rebased the lxde/lxqt-sudo#22 and added the QT_PLATFORM_PLUGIN and QT_QPA_PLATFORMTHEME to the vars list to not strip.

**Comment by tsujan** [comment]
> To be precise...the lxde/lxqt-sudo#22 did the job, but your comments began a discussion...

On the contrary, my comment was about the fact that it didn't work: https://github.com/lxde/lxqt-sudo/pull/22#issuecomment-251339725.

**Comment by stefonarch** [comment]
Uhm, maybe I'm getting old ... I compiled the rebased version, ~/.config/lximage-qt remains untouched but also /root/.config/lximage/settings.conf remains untouched but settings changed with lxsudo lximage-qt remain stored (e.g. green background) even when I deletesettings.conf in /root... 
I tried to do a  locate settings.conf with no result.

**Comment by tsujan** [comment]
@stefonarch Could you try the patch attached to https://github.com/lxde/lxqt/issues/1138#issuecomment-358111955?

**Comment by stefonarch** [comment]
This patch works as the original commit from palinek did, settings from /root/.config get used and modified.
There has to be a problem in the rebased version.

**Comment by tsujan** [comment]
@stefonarch The 2016 commit of @palinek's didn't work as expected. I'm not going to try it again but please see https://github.com/lxde/lxqt-sudo/pull/22#issuecomment-251331886 and https://github.com/lxde/lxqt-sudo/pull/22#issuecomment-251339725.

Such problems don't happen with my patch: root apps are like non-root ones.

**Comment by tsujan** [comment]
I quote what @palinek said in that time:

"The result is obvious (in this PR usage all the QT_* are stripped, in yours they are left so you're using e.g. kvantum also while with root privileges)."

IMO, what he calls "obvious" is an obvious mistake. Root apps should be like non-root apps, as kdesu did in that time. I haven't had such problems for years.

**Comment by tsujan** [comment]
More explicitly:

The main difference between @palinek's approach and mine is that he thinks about what should be set, while I mostly think about what should be unset. As there are many env variables, it's safer to focus on unsetting just a few variables because we can't be sure about the side effects of not setting others (as has been the case with @palinek's attempts).

**Comment by luis-pereira** [comment]
@tsujan The reason `kdesu` performs gracefully is an unset `XDG_CONFIG_HOME`. If one sets `XDG_CONFIG_HOME` and then run a Qt program with kdesu it will misbehave like lxqt-sudo.

**Comment by tsujan** [comment]
@luis-pereira `XDG_CONFIG_HOME` is one of the variables that are unset [here](https://github.com/lxde/lxqt-sudo/pull/30/commits/3080b52b92fcfc66ab4365d3bd7c42543a745250). We shouldn't unset variables without why; hence that patch.

**Comment by luis-pereira** [comment]
@tsujan I didn't took a look at the patches yet. But that's not what I'm talking about.

I'm saying that although `kdesu` performed correctly in your tests it's flawed also.  It only performed correctly because `XDG_CONFIG_HOME` wasn't set. It performed badly under LXQt because we set XDG_CONFIG_HOME in `starlxqt`.

**Comment by tsujan** [comment]
@luis-pereira `kdesu` doesn't have a special relation to this -- I haven't tried it for a long time but I know why it worked in that time -- as you mentioned correctly.

The current discussion is about 2 opposite viewpoints. From experience, I known it's *unsetting* that should be done selectively, not setting (= allowing some variables to remain set): Unset a few variables, knowing what you're doing, and you'll have a reliable `lxqt-sudo`.

**Comment by luis-pereira** [comment]
@tsujan I tryed `kdesu` today.

Regarding the 2 opposite viewpoints: 
It's a tricky issue. We are acting God in both approaches. Acting differently but still acting as God.

We really don't know what environment variables a user might have set and what are the consequences of preserving them.
IMO it's "more secure" to only allow the ones we now are safe. Drop everything else. That probably leads to progressively adding variables to the safe list over time. It might brake something, but the fix is easy and it leads to a more secure `lxqt-sudo`.  So I see @palinek as the way to go. Keeping in mind that it probably will lead to more "maintenance" work but to a more secure scenario.
An option to allow the user to choose additional variables to preserve also makes sense in my opinion.
That's my two cents.

p.s. I did not look into the actual patches. Will probably do it tomorrow, if not's merged by that time. My cold is going away :smile:

**Comment by tsujan** [comment]
> We are acting God in both approaches

 I used that idiom because it was pertinent ;)

> We really don't know what environment variables a user might have set and what are the consequences of preserving them.

Oh, we shouldn't decide for users (one meaning of "playing God.") but unset only those variables that we *know* are dangerous. @palinek's method *blindly* wipes out all variables we don't know about. Without taking the slightest risk, the code would be "secure", of course, but rigidly and impractically secure.

And after all, the current state of lxqt-sudo hasn't exploded anyone's computer. Turning the problem I reported here into its opposite is not an option to me.

**Comment by luis-pereira** [comment]
@tsujan @palinek  For the `sudo` backend we [preserving the environment](https://github.com/lxde/lxqt-sudo/blob/master/sudo.cpp#L186). Was it taken into account when writing the patches ?

**Comment by palinek** [comment]
> For the sudo backend we preserving the environment. 

Yes, that's because `su` preserves environment and `sudo` does not (by default). But we wanted the `lxqt-sudo` behave equally no matter which backend is used.

Then the problem with changing ownership of config files arised. So I took the approach to strip everything, but the known needed vars. That was the same approach, which is used by sudo people (and I believe they know better, what is more secure than me/us - I believe the default behavior of sudo to strip the environment has its ratio).

Then the comment about not correctly used Qt theme came and I added to preserve QT_.... vars to use the correct theme plugin.

...so that was the spin of adding needed vars as you told.

But  I'm not going to try convince anybody any more (it's been written too much about this topic and now I'm lacking enthusiasm to write the same again and again)

**Comment by agaida** [comment]
Ok . will test both variants - and will add this to the other variant too - in the end i still don't know which way to go, but i have an idea - i will build two live isos with the different approaches, start some root terminal and export the environment - we will see how both environments differ, maybe that helps - and don't get me wrong - as i wrote, both have it's pros and cons - so please discuss it without to much emotions, it is not a fight :D

**Comment by tsujan** [comment]
> ... which is used by sudo people (and I believe they know better, what is more secure ...

That can be one reason to not use sudo for GUI apps.

**Comment by luis-pereira** [comment]
I was already convince but after reading @palinek response to my comment I'm even more: IMO @palinek "variant" is the way to go.

**Comment by palinek** [comment]
>>... which is used by sudo people (and I believe they know better, what is more secure ...

>That can be one reason to not use sudo for GUI apps.

No, that's definitely not. IMO the only reason to have apps like gsudo/kdesudo/lxqt-sudo (which all are just a GUI frontends for su/sud) is to not spawn terminal window to launch GUI app.

**Comment by tsujan** [comment]
If by "spawning terminal window" you mean a need to a terminal emulator, `sudo` could also be used in custom actions, pcmanfm-qt preferences, etc. If not, I didn't understand it correctly.

**Comment by tsujan** [comment]
[Ubuntu doc](https://help.ubuntu.com/community/RootSudo) says, "This prevents files in your home directory becoming owned by root." Of course, I don't mean that it's correct *because* Ubuntu says so but a sensitive job of such frontends is managing env variables.
