### ISSUE TITLE
Lxqt-panel disappears when resolution is changed-external monitor-

### ISSUE THREAD

**Issue by aldobelus0** [lxqt/lxqt#1144]
I have an external monitor to manage my computer. When I initiate the session, and being both screens, internal and external, of different resolution, I set the image of the desktop to the monitor with _Arandr_ and, when the change happens, the panel disappears. 

It have made this process with the application by default of the system and has occurred exactly the same, so it's not a problem of the program with which is manage, is a problem of the panel, I figure. 

I have managed several desktop environments and never had this problem. Do you need more data to think of a solution?

I use Trisquel 7.0, Ubuntu 14.04-based.

**Comment by pmattern** [comment]
We've recently had a large number of issues affecting lxqt-panel on multi-monitor systems. All of them except a minor detail which doesn't seem to be your problem are fixed in current master, though. See initial issue #990 and discussion in lxde/lxqt-panel#310 where the current status is summed-up in [this comment](https://github.com/lxde/lxqt-panel/pull/310#issuecomment-233174982).

So I'd guess you're still running 0.10 and the problems could be fixed by upgrading to current master or using release 0.11 which you can expect to be released this week.

On a side-note please always state the LXQt version you're using and the way it was installed to make answering easier for us.

**Comment by tsujan** [comment]
Not reproducible after removing `QDesktopWidget` (git lxqt-panel, for now).
