### ISSUE TITLE
New forum/lists for LXQt

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1354]
Hi, finally i managed to setup a new instance of discourse for LXQt. We can take over the database from digital ocean or start from scratch, both will work without problems. DNS is set and ready.

The one remaining problem is the mailserver - to be true, i set up my last mail server five or six years ago. I take over the settings from digitalocean as much i know them, mail records should be up and running - the probelm is to finally set this "thing" up, set some aliases and test it - telling discourse about should not be rocket science. 

So this is a loud cry for help @pmattern @paulolieuthier @all. Please let us roll out this damn thing as fast as possible, four years talking about are nearly enough, we need this communication channel badly.

**Comment by palinek** [comment]
@agaida I'm ready for help... but I need specific tasks/goals to look/do on. Do you have some?

**Comment by agaida** [comment]
@palinek - please ping me

**Comment by pmattern** [comment]
The Discourse instance at `lists.lxde.org` currently suffers from a security hole and is screwed to a degree that I couldn't even get it updated from its webinterface, the mail server lacks helpful features and the underlying OS has never been updated on a regular basis.
So I'd strongly vote against adopting anything from this virtual machine except maybe some configuration files.

Meanwhile I had set up a mail server and Discourse instance as well, both should provide all the features we need.
I could sure help establish these on a production system the next days.

As for the subdomain I think we should chose a generic term and not state the software.
We cannot expect all users to know all software in use while they obviously do know generic terms. Also, chances are we will switch software one day.
Personally I'd still go for `discuss.lxqt.org`.

Btw. I was recently wondering whether Debian, IMO subject to a number of serious problems since years, can really still be considered a good choice for servers.
E. g. right now [CVE-2017-12133](https://nvd.nist.gov/vuln/detail/CVE-2017-12133) and [CVE-2017-12132](https://nvd.nist.gov/vuln/detail/CVE-2017-12132), two remotely exploitable vulnerabilities in the stub resolver of glibc which are tagged "Medium" in terms of CVSS and have been addressed by others long ago, remain [unsolved](https://security-tracker.debian.org/tracker/source-package/glibc) in stable since weeks.

**Comment by agaida** [comment]
Please elaborate the importance of these bugs for a server - btw, the host is a current ubuntu that will be switched to LTS maybe after 18.04
* https://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-12133.html
* https://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-12132.html

Next thing is - i took the database and the configuration files to some extend - i see no downside to do so. I'm open to all naming suggestions - right now it is forum.lxqt.org, but thats only a name that can easely be changed (A record) - same for the MX record. We are free to setup what we want too.

**Comment by agaida** [comment]
@palinek @tsujan - please join https://forum.lxqt.org - i need your help with the release notes - and even if the forum is not ready to official promote it (name, mailserver setup, categories and so on) - it is a fine platform to prepare some things

**Comment by tsujan** [comment]
I edited "Release Notes pcmanfm-qt/libfm-qt 0.12.0"  but found no way other than saving the changes. Is that OK or is there a way to propose changes instead of saving them?

**Comment by agaida** [comment]
just save it, there is a revision control behind

**Comment by palinek** [comment]
> please join https://forum.lxqt.org

I signed up... but by regular sign-up process, not accepting your invitation. Because the invitation ended in `spam` and I noticed it just later.

**Comment by stefonarch** [comment]
Github credentials do not work (for me...)

**Comment by agaida** [comment]
it might be that the credentials are outdated - there are much things to do, but right now the forum in it's current state is a big help for the team. We will improve the forum shortly after the release, The current state is best described as "scratching our own itch" - we will fix these things before we will promote it

**Comment by agaida** [comment]
done long ago
