### ISSUE TITLE
Colorize Icons again

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt#1446]
##### Expected Behavior
In an ideal world the icons would match the current window style

##### Current Behavior
i only can decide between "colorize on widget style on/off" - and thats something that looks bad in the most cases - with the current possible settings at least some applications or menus look plain bad.

![wordfence](https://user-images.githubusercontent.com/1162845/36119755-3d56f04a-1041-11e8-8801-9799258b8d58.jpg)
![wordfence](https://user-images.githubusercontent.com/1162845/36120704-4e89dde8-1044-11e8-8557-d6ca57a520ac.jpg)

##### Possible Solution
Settings per application in control center
or Setting overrides in application
or hints in the theme

##### System Information

* Distribution & Version: Sid/Current git/Qt 5.9.2

**Comment by tsujan** [comment]
When you disable colorizing, the default color of your SVG icons will be picked up. That default color can be dark gray, black, white, red... depending on your icon theme.

Your widget style is light but your panel *stylesheet* is dark. Colorizing always follows the widget style -- it can't follow the specific stylesheet used by this or that app -- hence the SVG icons might have a low contrast on the panel.

That being said, when I use a light Kvantum theme with a dark panel, I give a dark Kvantum theme to `lxqt-panel`, so that SVG icons are light on the panel and dark on windows. In other words, Kvantum can give different *widget styles* to different apps, and that's what colorizing "sees".

When you have a dark stylesheet with any app, while your widget style is globally light, you'll have to use an icon set that's good on both light and dark backgrounds. I really don't think that this problem can be solved by LXQt. It's about icon set + widget style.

**Comment by agaida** [comment]
In other words - i should bring Kvantum to debian and install it :D - Ok, no problem :D

**Comment by agaida** [comment]
There is one remaining question - kvantum can do that - why not LXQt? Or in other words: Hell, if we are so limited with our themes, why don't we use kvantum or similar as default?

**Comment by tsujan** [comment]
Here, I've given a dark Kvantum theme to the panel (while it's styled by a stylesheet, not by Kvantum) and the Kvantum theme used by other apps is light. See the USB icon on the panel and the toolbar icons of FeatherPad:

![style](https://user-images.githubusercontent.com/981076/36123466-f360cc56-1061-11e8-9752-98aba6adc64b.png)

> There is one remaining question - kvantum can do that - why not LXQt? 

A good question, about whose answer I may be wrong but, as far as I know, colorizing is based on the QStyle palette (not stylesheet colors) and I can't see how LXQt could define that.

@palinek?  Do you have a better answer or probably, an idea to do this?

**Comment by tsujan** [comment]
BTW, KDE exactly has this problem too. And I agree that it *is* a problem; I just think that the KDE widget style should have solved it under KDE but Breeze doesn't, apparently.

However, LXQt doesn't have a widget style of its own (and that was a good choice, IMO).

**Comment by agaida** [comment]
And my problem is - nearly from the beginning of LXQt - that i like dark main menues and a dark panel, but light applications - and i think that i'm not alone. And nothing against kvantum - but we should make those "basic" things possible in a default LXQt. Meanwhile i have a look into kvantum packaging :D

**Comment by agaida** [comment]
@tsujan - depend kvantum on a WM?

**Comment by tsujan** [comment]
> And my problem is - nearly from the beginning of LXQt -  that i like dark main menues and a dark panel, but light applications

You would have the same problem under KDE. As far as I know, there are only 2 solutions:

(1) Using of an icon set that's good on both dark and light backgrounds.
(2) Using a widget style that can be app specific.

I'll be happy if LXQt can have a third way.

> depend kvantum on a WM?

No. It only depends on Qt and is independent of anything else.

**Comment by tsujan** [comment]
> Meanwhile i have a look into kvantum packaging :D

Oh, that would be very kind of you; like what you did with FP :) It supports both qmake and cmake.

**Comment by tsujan** [comment]
> but we should make those "basic" things possible in a default LXQt. 

I agree but, like you put the word "basic" inside quotes, I think it isn't so basic ;)

**Comment by agaida** [comment]
So - i know that it is _not_ basic - but please forget for a minute that we are developers. So - from a users pov that really should a very basic thing. And from time to time i switch to the user perspective and refresh and polish my whole set of swearwords :D

**Comment by tsujan** [comment]
> from a users pov this should really be a very basic thing.

I completely agree. I also agree that the lack of this feature in KDE isn't an excuse for us.

**Comment by tsujan** [comment]
I looked into this and remembered the problems I had with stylesheets in Kvantum ;). This is my argument:

The SVG icons get their colors based on the application palette (libqtxdg → xdgiconloader.cpp → ScalableFollowsColorEntry::pixmap). Qt has 2 ways to style apps: (1) with `QStyle`, which is the main way and provides the above-mentioned palette; and (2) with a stylesheet, like in the panel.

When it comes to stylesheets, there are, at least, 3 problems:

(1) What's the stylesheet of a widget (on which an icon should be colorized)?
(2) How to read that stylesheet? 
(3) *On which widget an icon should be colorized?*

The first and second problems may be solved in this or that way but the third one cannot. Why does (3) become important? Please continue reading:

When we use the application palette (the standard way), we don't deal with widgets (buttons, text entries, check boxes,...). Actually, we can't know which icon is on which widget and, with the application palette, we don't need to because all widgets use the application palette *if there is no stylesheet and no hard-coded widget style*.

However, when there is a stylesheet (or a hard-coded widget style), each widget can have its own background and foreground colors defined in the stylesheet. So, we should know which icon is on which widget with which background and foreground colors in order to set its color correctly. That's simply impossible.

In general, stylesheets aren't manageable. This is a basic problem in Qt. Stylesheets are good because they can override the platform style easily; and they're bad because of that.

**Comment by palinek** [comment]
> > There is one remaining question - kvantum can do that - why not LXQt?

> A good question, about whose answer I may be wrong but, as far as I know, colorizing is based on the QStyle palette (not stylesheet colors) and I can't see how LXQt could define that.

> @palinek? Do you have a better answer or probably, an idea to do this?

I believe this is doable "easily" in following steps:
1. we can make the palette to be configurable in `lxqt-qtplugin` -> [here](https://github.com/lxde/lxqt-qtplugin/blob/master/src/lxqtplatformtheme.cpp#L222) (we could make it also per-app configurable? ... so @agaida can have black panel with other apps light :))
2. remove all manual changes of colors in all our themes (stylesheets)

For the 1. step IMO there should be some configuration GUI made....

**Comment by agaida** [comment]
@palinek thank you so much - and btw. i noticed the problem with the papirus theme, which was choosen by the Lubuntu team - so i guess they will not be exactly happy with the current situation. But this is a totally different story :P

**Comment by tsujan** [comment]
> we can make the palette to be configurable

Palettes aren't enough. For example, we have various kinds of tool buttons on the panel; QuickLaunch can have a light background and TaskBar can have a dark one. Stylesheets allow that. That's while `QPlatformTheme` has only one `ToolButtonPalette`.

Moreover,

(1) we're talking about app-specific palettes here: a palette for app A, another for B, yet another for C...
(2) Setting the palette of a tool button to dark doesn't make its icon light automatically. The colorizing method relies on the window and highlighted text colors.

> remove all manual changes of colors in all our themes.

People should be allowed to do anything they want to with any theme or make their own themes.

That being said, a partial solution may be possible by letting the user *pretend* that an app -- like panel or runner -- has a totally dark or light style by *pretending* that it has a specific window and highlighted text color. That would be a *partial* solution because a style can be a mixture of light and dark elements.

Looking forward to any app-specific implementation...

**Comment by tsujan** [comment]
> So which standard exactly is governing dynamic colors in icons? I can not find anything in XDG icon theme spec.

@Vladimir-csp I don't think they're in the XDG icon theme spec. KDE uses "text/css"  in the SVG. Consider this SVG icon:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <defs id="blahblah">
    <style type="text/css" id="current-color-scheme">
      .ColorScheme-Text {
        color:#4d4d4d;
      }
      </style>
  </defs>
 <path style="fill:currentColor;fill-opacity:1;stroke:none" 
     d="blahblahblah....... "
     class="ColorScheme-Text"
     />
</svg>
```
KDE sets `.ColorScheme-Text` based on the icon mode (a selected menu-tem, for example) and the window and highlighted text colors of the palette. We use the KDE method. That means, if a themes is light (its window text color is dark) its usual icons will be dark but if its highlight color is dark (which means a light highlighted text color), the icons on the "highlighted" widgets are light (white). A "highlighted" widget reports its icons as being in the `QIcon::Selected` mode.

In Kvatum, I made a simple trick to report the icons of dark elements of a light theme -- or light elements of a dark theme -- to be in the `QIcon::Selected` mode, so that colorizing won't be based on *selected* men-items, view-tems, etc. With that trick, light-and-dark themes became possible.

How that may be implemented in LXQt, I have no clear idea but I hope it's possible.

**Comment by agaida** [comment]
i close the colorize thing for now - we have a working state, ok, not all things are fixed, but it "kind of work" 

If there are things we can and should improve this should be done in separated issues.
