### ISSUE TITLE
Look into Qt app styling for our dark themes (Ambiance)

### ISSUE THREAD

**Issue by jleclanche** [lxqt/lxqt#145]
Our Ambiance and A-Mego themes should probably restyle Qt apps as a whole. FWIU this is pretty easy now that we have a platform plugin.

**Comment by antis81** [comment]
Hey guys,

with LXQt 0.16 I worked around this issue and created a "dark mode" by modifying LXQt's color palette. One can reproduce this relatively simple by grabbing each color from screenshot (red rectangle) - takes a minute or two, but works pretty well.

![theme-dark-sample](https://user-images.githubusercontent.com/440517/104104637-abc99e80-52a9-11eb-952a-36df1221e750.png)

Further by overriding GTK2/3 themes (as the screenshot shows ) a consistent "look&feel" throughout applications (including LibreOffice, Firefox etc.) can be achieved.

Can't each LXQt theme provide a (fixed/preset) color palette so that it sets the colors "automagically"?

**Comment by tsujan** [comment]
> Can't each LXQt theme provide a (fixed/preset) color palette

The palette colors are inside `~/.config/lxqt/lxqt.conf`. If that file is edited manually, the changes will be applied as soon as it's saved.

This old report isn't (and wasn't) valid because Qt's stylesheet and `QStyle` are totally different from each other.

**Comment by antis81** [comment]
@tsujan Why? This is a valid feature request (for "dark mode" -> "dark theme" actually). Furthermore the current integration is far enough so it is not too hard to implement it (could be part of LXQt 0.17). In the first place all we have to do is provide a (constant) QPalette object for each theme, which in turn defines the system color palette (overwrite the colors in `~/.config/lxqt/lxqt.conf`). I will have a look and prbly provide a PR for that.

Btw. it is possible to change color configuration via UI already. Thanks anyway for letting me know where it is stored. :slightly_smiling_face:

**Comment by tsujan** [comment]
> This is a valid feature request

It isn't because it presupposes that stylesheets can be forced on Qt apps. Read the end of my last comment.

> In the first place all we have to do is provide a (constant) QPalette object for each theme...

This is a completely different feature request; and it's valid. You could open an issue for it, clearly describing the feature you want.

**Comment by stefonarch** [comment]
> The palette colors are inside `~/.config/lxqt/lxqt.conf`. If that file is edited manually, the changes will be applied as soon as it's saved.

I wondered not to find it in `~/.config/lxqt/lxqt-appearance.conf`, wouldn't this be the better place?

**Comment by tsujan** [comment]
> wouldn't this be the better place?

Conf files aren't for manual editing; they're changed by the GUI. Moreover, `lxqt.conf` is "watched". It isn't a good practice to watch multiple files.

Applying "palette files" will have nothing to do with the name of the config file. If that's implemented, the GUI will take a "palette file" and do the job: again, no manual editing.
