### ISSUE TITLE
 Some issues in PCManFM-Qt 0.13.0

### ISSUE THREAD

**Issue by slm0** [lxqt/lxqt#1566]
Hi!

I'm new here and found some annoyances in PCManFM-Qt that I don't know if these are normal behaviors:

- I can't send a link, move or copy to the Places frame.
- I can't send to the trash with the Del-key, instead I can press Alt+Del to permanently delete.
- I can select and compress a set of folders, same for set of files... but not both at the same time. The "Compress" action disappears from the context menu.

Cheers!

// PCManFM-Qt 0.13.0 in Debian Buster 64-bit + LXQt + Openbox

**Comment by tsujan** [comment]
> I can't send a link, move or copy to the Places frame.

It isn't implemented but already reported (I don't remember where but we know about it).

> I can't send to the trash with the Del-key

Fixed in git.

> I can select and compress a set of folders, same for set of files... but not both at the same time. The "Compress" action disappears from the context menu.

For now, "Compress/Extract" only works with files with the same type.

I close this and will open an issue about "Compress/Extract" for various mimetypes at https://github.com/lxqt/pcmanfm-qt/issues if it's possible.

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/pcmanfm-qt/issues/791 .
