### ISSUE TITLE
Makepkg was unable to build libqtxdg-git (Arch)

### ISSUE THREAD

**Issue by eirenicon** [lxqt/lxqt#1619]
##### Expected Behavior
A clean build of the latest LXQt

##### Current Behavior
yaourt throws the following error:
Error: Makepkg was unable to build libqtxdg-git

##### Steps to Reproduce (for bugs)
1. Create Artix LXQt install
2. install yaourt
3. update libs
4. attempt to install libqtxdg-git from cli using yaourt libqtxdg-git

##### Context
Am unable to build a current version of LXQt on Artix
![screenshot_2018-11-11_08-21-51](https://user-images.githubusercontent.com/44545644/48314746-f09f0100-e58a-11e8-93fa-1066c3988c58.png)

##### System Information
see image

**Comment by agaida** [comment]
i just use pacman - same result - it build just fine - just have done a full rebuild of lxqt-git

**Comment by tsujan** [comment]
> i just use pacman

Me too. Upgraded libqtxdg a week ago, while the last commit was made 27 days ago.

**Comment by eirenicon** [comment]
As was noted, the issue was with Artix not manjaro or vanilla arch.  The 
problem must rest with Artix then.

Pax vobiscum,
...mark

------------------------------------------------------------------------

*Mark F. Rabideau,* *Owner/ Manager of:
PEP, Inc. & eirenicon l.l.c. +1.303.660.9400*
711 Nob Hill Trail - Franktown, Colorado USA - 80116
Former CMMI Institute Authorized High Maturity SCAMPI Lead Appraiser # 
0100059-00
SIX SIGMA Master Black Belt Certificate #3167140TY463591U
*PEP, Inc*.:_http://www.pep-inc.com_ <http://www.pep-inc.com/> 
*eirenicon l.l.c.*:_http://www.eirenicon.org_ 
<http://www.eirenicon.org/> */Envision-It!/*: 
_http://www.envision-it.org_ <http://www.envision-it.org/>

/*"*//*The privilege of a lifetime is being who you are.*//*"
*//*- Joseph Campbell*/

------------------------------------------------------------------------

/*The information transmitted is intended only for the person or entity 
to which it is addressed and may contain confidential and/or privileged 
material. Any review, retransmission, dissemination or other use of, or 
taking of any action in reliance upon, this information by persons or 
entities other than the intended recipient is prohibited. If you 
received this in error, please contact the sender and delete the 
material from any computer.*/

**Comment by eirenicon** [comment]
I am testing on Sparky for the same issue.

**Comment by tsujan** [comment]
> I am testing on Sparky for the same issue.

You didn't say a word about the failure ;) You just said there was a failure.

**Comment by agaida** [comment]
re: Sparky - it will fail in more than one point - and you will likely destroy/mess up your installation. Trust me - apt changelog $foo will tell you why. :smile:

**Comment by agaida** [comment]
@eirenicon - just downloaded and installed the testing  base thing - and you are right, Pawel has built a good release out of the base. What i like:
* calamares as installer
* using the lxqt meta-packages and some basic tasks
* Installation went well, first start went well, i like the dialogue at first start very much
* qt5-style-plugins installed by default - gtk style selected - nice one

Things that i don't like so much:
* lightdm as DM - but hey, personal choice, lxqt meta only depend on a DM - so totally fine
* Openbox as WM - ok, one can read my opinion about openbox everywhere, again - the only dependency in lxqt meta is a WM - so also totally fine
* Gnome nm applet - good choice, if one don't want do go the connman/cmst way  - lxqt meta is prepered for, so fine
* there are some daemons running that make no sense at all:
  * rsyslog - hey, we are in the 21. ct - and i would bet, that rsyslog isn't configured right, only standard debian
  * exim4 is installed and running - really, i hate it 
  * acpid is installed and running - again, we are in the 21. ct - no need for
  * ntpd is installed and runnong - really, we are in the 21. ct - and the systemd timedated does just fine

Ok, rsyslog, exim4, acpid, ntpd are debian defaults and could be circumvented - but who cares :sunglasses: - not bad at all i would say. Really good job with minimal point deduction in the posture grades. 

But that don't change anything - if one want to run latest git on sparky one should use the experimental-snapshots repo - otherwise one wil likely fail miserable - i mentioned the intentionally destroyed system before? :)

**Comment by agaida** [comment]
and even if you use the experimental release it will break - hopefully, if not Pawel is so brave and included the experimental-snapshots (i hope he does not :D) - but thats a different thing
