### ISSUE TITLE
Status Notifier Plugin shows the same menu for the right and left click but with a different style

### ISSUE THREAD

**Issue by micrococo** [lxqt/lxqt#1650]
Hi.

The right and left mouse click on the Status Notifier Plugin both show the same menu but with a different style. A left click shows a normal, not styled menu. A right click shows a menu using the style defined for menus in the style sheet.

Left click:

![right-click-menu](https://user-images.githubusercontent.com/7717273/50890222-12d1c580-13fa-11e9-814b-7bd2306bee38.jpg)

Right click:

![left-click-menu](https://user-images.githubusercontent.com/7717273/50890232-15ccb600-13fa-11e9-8ca5-0bcbc94b1b0a.jpg)

##### Expected Behavior

I think that the left click should show a styled menu like the one currently shown when you press the right click. Then the right click should show the same options that the others plugins show when you right click on then (configure/move/remove and the options to configure the panel).

##### Current Behavior

Both the right click and the left click show the same menu.

##### Possible Solution

Right click and left click should show a different menu.

##### Steps to Reproduce (for bugs)

1. Left click on the plugin button: you should see a popup menu
2. Right click on the plugin button: you should see the same menu with a different style

##### Context

I expected the menu to have the style defined in the style sheet. In addition I expected getting the same options menu on right click that the other plugins show.

##### System Information

* Distribution & Version: openSUSE Tumbleweed version 20181224
* Kernel: 4.19.11
* Qt Version: 5.12.0
* liblxqt Version: 0.13.0+git113.7a2ae47
* Package version: 114

**Comment by palinek** [comment]
No. The status notifier item shows the menu (whose items are provided by application) upon the right click and "just" notifies the application about the left click... the application is responsible for processing the left click (and show the exact same menu in your case).

**Comment by micrococo** [comment]
Sorry but I don't understand what you mean @palinek. I'm talking about right/left clicks on the panel button (the plugin you add to the panel) not on the popup menu items. Given that it is a plugin I'd expect it behaving the same the other plugins do. For example, this is what I expected to see when I right click on the plugin button on the panel (the image is the right click on the button of the removable media plugin):

![menu](https://user-images.githubusercontent.com/7717273/50892511-fc7a3880-13fe-11e9-8da9-a1de564b3f9c.jpg)

**Comment by palinek** [comment]
> Sorry but I don't understand what you mean @palinek. I'm talking about right/left clicks on the panel button (the plugin you add to the panel) not on the popup menu items.

Your description:

> The right and left mouse click on the Status Notifier Plugin both show the same menu but with a different style. A left click shows a normal, not styled menu.

Status notifier plugin is not a button, it is an "area" for notifier items. Each notifier item provide its own menu.

**Comment by tsujan** [comment]
@micrococo The status notifier icon is a *system tray item* and each tray item has its own right-click menu, while most of them don't have any lef-click menu.

In the case of status notifier, I also made the right-click menu be shown with a left click -- for the ease of use.

Now, if the menu has two different styles with righ and left clicks, I think the status notifier has a widget style *other than* the active style because it has started too soon.

@palinek Although it isn't a critical problem, I think this report is valid. I have another example of a too soon startup of the status notifier. Please reopen it if you agree! And any idea what could be done with the start order?

**Comment by tsujan** [comment]
BTW, if the addition left-click menu didn't exist, still another issue could be opened with this title: "Status Notifier Plugin right click menu has a different style."

When `lxqt-notificationd` didn't have a the tray icon, its too soon startup couldn't be "seen" (although I'd seen it and encountered a small problem caused by it -- since then, I add a small delay).

**Comment by micrococo** [comment]
Thanks for the clarification @tsujan. I didn't know it was a tray icon. But then, shouldn't it behave like others applications, Qlipper for example, and be run from the Autostart section of Session Settings? I think that as it is now is confusing (because it looks like any other panel plugin except that you can't remove it by using the mouse: you have to open the panel configuration dialog, go to Widgets and remove it from there) but it behaves as a tray icon. And not exactly like a real tray icon because those usually have a different menu for each mouse click: in this case, the left click would show the notifications list, and the right click the options to close the application, clear the list, open the configuration dialog, etc.

By the way, I added a red border to the tray and it is empty. I'd expect that tray icons like Qlipper to be placed there. The `TrayIcon` style isn't working either (the tray icons in the image are styled via `Plugin > QWidget > QToolButton`). I don't know whether this a bug or not.

![tray](https://user-images.githubusercontent.com/7717273/50899699-2e959580-1413-11e9-8a05-2782f6b10835.jpg)

This is all just feedback from a user point of view, just ideas, it is neither a real request nor a complain.

**Comment by tsujan** [comment]
@micrococo There is an understandable misunderstanding in your report: Status Notifier is the new systray (the old one is called "System tray"), while that icon belongs to `lxqt-notificationd`. In other words, the systray icon of `lxqt-notificationd` is inside Status Notifier ;)

I don't expect AT ALL that users should know the difference between the two because their names are confusing. As you can see in my first comment, I repeated the same name mistakenly (while being busy with pcmanfm-qt's coding), although I knew the different ;)

To test my idea about styling, please stop and start "Notification Daemon" from LXQt Session Settings. Then check both menus. Do they have the same style now? If so, I'll open another report with the correct title (here, the title is important to prevent confusion) and add a link to this report.

> This is all just feedback from a user point of view

And it's very appreciated.

**Comment by tsujan** [comment]
I corrected names in my first comments to prevent further confusions.

**Comment by tsujan** [comment]
Oh, never mind!  In the style I use, both menus are the same only because my it leave menus to the widget style. No issue to fix.

I agree that it may be confusing. But I don't think that the removal of the left click menu is a good idea.

**Comment by tsujan** [comment]
I think users of Qt apps will encounter this kind of inconsistency forever, while users of GTK+ apps see a self-consistent look in GTK+. Anyhow, for reference:

### Styles in Qt/LXQt

The look of everything on Panel depends on its stylesheet, which belongs to what we call "LXQt theme". The look of everything else (pcmanfm-qt, for example) depends of the active Qt widget style (Breeze, for example). So far, things may seem self-consistent: this style *or* that style. But alas...

In the case of lxqt-notificationd, the right click menu of its tray icon is styled by Panel, while the left click menu is styled by "the app" and so, by the active Qt widget style. Yes, it's counterintuitive but isn't the last weirdness.

In the case of my personal LXQt theme, menus are NOT styled by its stylesheet --- there's no section for menus in the theme --, so both menus are the same and are like any other menu (and hence, my previous misunderstanding of this report). In other words, the same and one app is styled partly by a stylesheet and partly by the Qt widget style!

The discrepancy between stylesheets and widget styles is very old. Stylesheets can be seen as "special styles" for some GUI parts of particular apps. Those apps should support external stylesheets, in the first place. Most apps don't but LXQt Panel does and should.

The styling situation of Qt is even worse but not related to this.

**Comment by micrococo** [comment]
I really appreciate your detailed explanations @tsujan, thanks. Answering your question, yes, if I stop and restart "Notification Daemon" from LXQt Session Settings, the left and right click menus have a different style. So there is no need for another report.

Regarding to themes, while making my themes (first time, a copy of Breeze and Breeze-dark) I noticed that changing the Qt widget style makes some panel controls to take that style too if they have no style given via CSS (scrollbars, text fields and the volume slider). So I'll end styling everything to get a consistent panel look independently of the Qt widget style selected.

**Comment by tsujan** [comment]
> I didn't notice it before...

Not your fault. It *is* confusing.

> I noticed that changing the Qt widget style makes some panel controls to take that style too if they have no style given via CSS...

Exactly! Stylesheets override only those aspects of widget styles (= QStyle) that they include (but, unfortunately, not always in a predictable way). It's both good and bad. Good because a user like me may prefer the widget style menus (and some other components) with Panel. Bad because you should include every detail if you want something similar to KDE plasma.

**Comment by tsujan** [comment]
BTW and for the sake of completeness (although you may already know it), this is the best reference: http://doc.qt.io/qt-5/stylesheet-reference.html

**Comment by micrococo** [comment]
> BTW and for the sake of completeness (although you may already know it), this is the best reference: http://doc.qt.io/qt-5/stylesheet-reference.html

Yes, I already knew it, but thanks for pointing it out anyway. It may be useful for someone else.
