### ISSUE TITLE
Hidden shortcut keys?

### ISSUE THREAD

**Issue by gomesrod** [lxqt/lxqt#1657]
I have run across this issue when trying to disable some keyboard shortcuts that were in conflict with tools that I use.

Using lxqt-config-globalkeyshortcuts (Menu -> Settings -> Shortcut keys) I found some of such shortcuts and were able to disable them successfully.

However there are some other shortcuts which seems to be "hidden", they are not configured anywhere and are still taking effect.

##### Expected Behavior
I expected that all active shortcuts would be listed and could be configurable through the graphical interface.
I also understand that there are shortcuts that might belong to Openbox, and are located in its own configuration file (~/.config/openbox/rc.xml), but it does not seem to be the case

##### Current Behavior
The shortcuts Ctrl+Alt+T (opens the terminal) , or Ctrl+Alt+V (some context menu that I dont know what is for) are the ones on which I was able to find the issue.

The shortcuts are active, and not allowing me to use them as application-specific shortcuts.
They are not listed in the shortcut configuration GUI, and not listed in the ~/.config/openbox/rc.xml file.

Stopping the "Global keyboard shortcuts" service (via Settings -> Session Settings) has no effect, the shortcuts remain active.
By logging out and entering a pure Openbox session the shortcuts are not active, and can be successfully used inside application.

From these tests my understanding is that these shortcuts are somehow started by the LXQT "core", not by Openbox or by the lxqt Global Shortcuts daemon.

##### Possible Solution
The shortcuts should be configurable/optional, just like all the others.

##### System Information
* Distribution & Version: Ubuntu 18.10
Output of lxqt-about:

LXQt About Version | 0.13.0
LXQt Version | 0.13.0
Qt | 5.11.1

**Comment by agaida** [comment]
not an LXQt bug - and please don't file such "bugs" upstream - thats what is Launchpad for.

**Comment by gomesrod** [comment]
Hi,
Thanks for the reply.

As per the observations mentioned in the issue, I had reasons to come to the conclusion that the shortcuts are provided by LXQT (openbox alone does not activate them). But if you are able to confirm that LXQT do not provide its own shortcuts, then OK I will continue to investigate somewhere else.

> please don't file such "bugs" upstream - thats what is Launchpad for.
Sorry, didn't know about that. Actually I could not find this information on either the project home or the contributing guide. One of these could be updated to contain a link.

**Comment by agaida** [comment]
try to edit $HOME/.config/openbox/*.xml

**Comment by gomesrod** [comment]
I found where was the mistake.
I was looking only in the default Openbox config file `~/.config/openbox/rc.xml`
The shortcuts were in this other file: `~/.config/openbox/lxde-rc.xml`

**Comment by gwerbin** [comment]
Is this `lxqt-rc.xml` file provided by Openbox and not LXQT? Since it came with my LXQT installation as well, I think it's worth at least mentioning in the docs somewhere that a user might want to move/delete this file in order to be able to let LXQT global hotkeys manage keybindings without interference from Openbox, or conversely that a user might want to let Openbox handle keybindings and remove `globalhotkeys.conf`.

**Comment by wxl** [comment]
The OpenBox config comes from OpenBox. There's a historical association between LXDE/LXQt and OpenBox but both of them are window manager agnostic. LXQt emphasizes that fact a bit more.

As for your suggestion, LXQt doesn't handle window management, so all of the shortcuts that OpenBox provides for that won't work without OpenBox's configuration. Similarly, OpenBox doesn't do much beyond window management, so it's not going to be able to do all of the things that LXQt can do.

**Comment by gwerbin** [comment]
@wxl my question is: Who ships the `lxqt-rc.xml` file? Openbox? LXQT? My distro (Opensuse)?

**Comment by wxl** [comment]
@gwerbin let me quote myself:

> The OpenBox config comes from OpenBox

If there's a conflict shipped with your distro, you should consult your distro, as that is a packaging issue. It's possible this may be by design. Lubuntu ships LXQt configured to open the menu with the <kbd>Super</kbd> key, which makes any OpenBox shortcut that uses it fail. We edited the OpenBox config to remove any, but that doesn't keep the user from trying to change that.

**Comment by gwerbin** [comment]
OK, I will a bug w/ Opensuse to either adjust or remove the Openbox `lxqt-rc.xml` file in the default LXQT installation.

**Comment by wxl** [comment]
Actually, there [is one shipped with LXQt](https://github.com/lxqt/lxqt-session/blob/22e111ac9398fd62e0383763052b56aecbec9fc3/config/openbox/lxqt-rc.xml). I'm a little surprised by that (@tsujan is that really intentional given our window manager agnosticism? and surprised that it conflicts with OpenBox, but still likely a packaging issue.

**Comment by stefonarch** [comment]
Just to be clear: lxqt-rc.xml is part of lxqt-session https://github.com/lxqt/lxqt-session/tree/master/config/openbox

**Comment by tsujan** [comment]
It's a relic of very old times. It can be removed now.

I guess Alf ignored it because his Debian lxqt used xfwm4.

**Comment by wxl** [comment]
Pull request for you above.
