### ISSUE TITLE
New release not notified on the homepage?

### ISSUE THREAD

**Issue by rubyFeedback** [lxqt/lxqt#1683]
If you go to https://distrowatch.com/ then you see a link like:

https://github.com/lxde/lxqt-panel/releases/download/0.14.1/lxqt-panel-0.14.1.tar.xz

I assume this works for the other lxqt-components as well.

If you go to https://lxqt.org/ and the download page, 0.14.0 is the last version reported.

I proposed to sync both pages if 0.14.1 is released already; or a short entry for
at the least those components that were upgraded.

I understand that github releases are simpler to manage, but end users may prefer
the nicer overview on  https://lxqt.org/ - at the least I do. It also is sort of an "official"
recommendation to use it, something like a "thumbs up" from the lxqt-devs, rather
than just github releases alone.

**Comment by jubalh** [comment]
We make an announcement once things are ready.
Just because nowadays websites track github tags doesnt mean anything.

In the past when every project had its own hosting, there were often release tarballs out some time and only after some time the release was announced.

So take lxqt.org as the source and not some third party website.

**Comment by agaida** [comment]
@jubalh, thanks, couldn't say it better - btw. was there a release? There should be release notes ...

**Comment by jubalh** [comment]
@rubyFeedback https://lxqt.org/release/2019/02/26/lxqt-0141/
