### ISSUE TITLE
"Trust this executable" mark restet after reboot

### ISSUE THREAD

**Issue by MikePooh** [lxqt/lxqt#1687]
I have .desktop entries which are located in /usr/share/applications. If copy or symlink this file to `~/user/desktop`folder it apperars on the desktop with special sign which shows that file is untrusted. There is context menu where I can choose "trust this executable". Howere this mark reset after reboot/display-manager restart

##### Expected Behavior
"trust this executable" mark to save after reboot

##### Current Behavior
"trust this executable" mark resets after reboot

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.0.0-arch1-1-ARCH
* Qt Version: 5.12
* liblxqt Version: 0.14.1
* Package version: 0.14.1

**Comment by tsujan** [comment]
The "trust" state is a gvfs metadata. It can't disappear unless you remove the file and copy it again or you remove `~/.local/share/gvfs-metadata`.

Not reproducible.

**Comment by agaida** [comment]
@tsujan: erm - reproducible and the behaviour to be expected - that's exactly what we want :sunglasses: 

```
# just a sample
cp /usr/share/applications/featherpad.desktop $HOME/Desktop
```
RESULT:
![](https://i.imgur.com/NdxBuAG.png)

And thats exactly how it should be: The file is not trusted.

(to be continued)

**Comment by tsujan** [comment]
@agaida, he says -- or I think he says -- he does trust the file and then, the trust metadata disappears after report. Hence my reply.

**Comment by agaida** [comment]
That's why i wrote: To be continued 

Trust the file, log out and in  - trust will be there.  
* Now open a terminal and rm $HOME/.local/share/gvfs-metadata/*
* chown root:root $HOME/.local/share/gvfs-metadata
* Log out and log in again
* Trust the Desktop file again

Log out, log in - use some swearwords :smile:

**Comment by agaida** [comment]
Forget to mention that not writable userdirs might have different reasons

**Comment by tsujan** [comment]
> Trust the file, log out and in - trust will be there.

As it should, because it's saved in `~/.local/share/gvfs-metadata` -- GLib does it.

> chown root:root $HOME/.local/share/gvfs-metadata

Then, the metadata won't be saved but why does one want to do so? ;) I guess, you mean it may have happened by accident.

> Forget to mention that not writable userdirs might have different reasons

Yes! Bad root EVs can cause than but it can't happen with an up-to-date `lxqt-sudo`.

**Comment by agaida** [comment]
one might think about other failures too - assume $HOME on a different partition and not cleanly unmounted on restart - in that case it might be that $HOME will be mounted RO - there are a bunch of things that might happend. (Or - maybe - partition full, no space left ... or ... )

But i tend to aggree that it will be hard to track down and that in a 'normal' system our trust will simply work - at least for me it do, even on arch linux

**Comment by tsujan** [comment]
> there are a bunch of things that might happend.

Then, they show there are SERIOUS problems in that system; they aren't related to pcmanfm-qt (as you know). Specifically, this part is simply about gvfs metadata and GIO, not about libfm-qt/pcmanfm-qt.

**Comment by agaida** [comment]
You are right - it was only a remark that i was able to create a situation where the described behaviour happend. And that i can imagine some situations that will lead to the same result :P

**Comment by tsujan** [comment]
Understood.

**Comment by tsujan** [comment]
@agaida There may be a way to support "weird systems". The old promptless launch option of pcmanfm-qt may be changed so that if it's enabled, no emblem is shown at all. Then, its name should be changed too -- and you'll have to make a partial point release ;)

I'll do it if it doesn't need lots of code because, otherwise, supporting "weird systems" won't be worth the effort.

**Comment by MikePooh** [comment]
The problem was in absence of package gvfs. And solved by 
`pacman -Syu gvfs`
Strange that it is not in depencies to lxqt package group.
Your comments was helpful. Thanks.

**Comment by stefonarch** [comment]
Should be reported to arch bug tracker maybe.

**Comment by tsujan** [comment]
> Should be reported to arch bug tracker maybe.

It's already among Optional Deps of pcmanfm-qt. What's true in Debian is also true in Arch: always install recommended packages!

**Comment by agaida** [comment]
With the latest changes i can't say that gvfs is optional anymore:
* trust
* remote file-systems
* anything i forget 

That was the reason why i depend at least on gvfs-bin in debian - can't stand the claims that something is not implemented or don't work anymore because someone think one is clever and leave out important recommends.

Ok, that will make pcmanfm-qt not really fit better for embedded systems - otherwise even a raspi has enough RAM.

**Comment by tsujan** [comment]
> That was the reason why i depend at least on gvfs-bin in debian

If X is a recommended packages for A, A compiles and works without X but lacks this or that functionality. Here, those functionalities are very essential. So, I like what you did -- I'd also do it if I made a deb package.

In Arch, the story is a little different -- you were an Arch user when I was a Debian user ;)

**Comment by tsujan** [comment]
Oh, you forgot Trash -- very essential.
