### ISSUE TITLE
"Desktop prefs->Label text->Font style" not initialized?

### ISSUE THREAD

**Issue by someguy2013** [lxqt/lxqt#1711]
I'm using Lubuntu 19.04 with LXQt desktop.

When I right-click on the desktop (and choose Desktop Prefs, and navigate into Label Text, choose font), I changed the font-size to "10". After "ok" and "apply" the desktop font (labels) changed to italics (which is a change I didn't request).

It looks like font-style is not being set to its current value until it's manually set. I.e., it looks like it is defaulting to the top-most choice in the list (light italics). It doesn't recognize that the current (installed) value is "Regular." 

This isn't a big problem. It's just annoying/startling to think your changing font-size -- and get more than you bargained for. It's not clear that the font-style isn't initialized, and defaulting to something based upon alphapetical sort value(?).

**Comment by tsujan** [comment]
Not reproducible.

You should see what's chosen in Qt font dialog before applying.

Also, please fill in the template when reporting an issue.

**Comment by wxl** [comment]
I'd kind of forgotten about this but I just tried this in Debian and Lubuntu and it is reproducible, just not necessarily as described. 

Default font in Debian is Sans 11 (seems Regular, but might be Bold as we will later see). When I click to change the font, the default selected font is Bitstream Charter 11 - Bold. I guess this is because there is no Sans font, or at least one doesn't show in the list, and Bitstream is at the top of the list. Now if I select the next font— Caladea— it has options for Regular, Bold Italic, Bold, and Italic. Though the options are listed in that order, it's Bold that is automatically selected. Carlito also has four options, with Bold as the last, and when you select it, that's what's selected. Now if I select DejuVu Sans, it has lots of options, but Oblique— the first— is the one selected. Click back on Carlito and we have Italics selected.

Lubuntu is similar. Default font is Ubuntu 11 Regular. Initially, Ubuntu 11 Light Italic (at the top of the options) is selected. Click on Tlwg Typo and Oblique, at the top of the list, is selected. Select Tlwg Typist and we're on Oblique, third option down. Back to Ubuntu and we're on Italic. DejaVu Sans gets us to Bold at the top of the list. Back to Ubuntu and we're on Bold.

Maybe this is intentional, that the style *selected* is always dependent on whatever the previous selected was, regardless of whether or not it was the style that was applied previously. That might appear to some as a feature, but clearly where styles aren't equivalent between two different fonts, then things start to get confusing. Sure, selecting Bold, you'd like all future font choices to also be Bold, but where there is no Bold, you probably don't want Italics. 

Given the likelihood of this, it might be best to try not to be smart about selecting the style and instead just always select the top-most option when selecting a different font.

**Comment by tsujan** [comment]
@wxl That's how Qt font dialog works. Nothing is added by us and `QFontDialog` doesn't have an option about it. If you think that behavior is counter-intuitive, you might want to report it at Qt bug tracker.

IMO, it isn't good but I don't consider it as a Qt bug.

**Comment by wxl** [comment]
@tsujan Thanks for pointing that out. I'll file an upstream bug, thanks!

**Comment by wxl** [comment]
FWIW, [here](https://bugreports.qt.io/browse/QTBUG-77036) is the bug.

**Comment by tsujan** [comment]
We can use the font settings GUI of LXQt Appearance instead or somethings like this:

![font](https://user-images.githubusercontent.com/981076/61176489-01e75400-a5d7-11e9-89c3-13fa86d11014.png)

But, IMHO, it isn't important because the user could check what's selected before closing the dialog.

**Comment by tsujan** [comment]
OK, I played with FeatherPad's font dialog and succeeded in changing "Regular" to "Bold" for font "X" after doing a complex ritual I can't remember but *without selecting "Bold" intentionally*. Then I kept selecting fonts randomly and succeeded in changing "Bold" to "Regular" for "X" but, again, without selecting "Regular" deliberately.

So, there's definitely a bug in Qt font dialog but it isn't easy to catch. It isn't serious either, IMO.

**Comment by agaida** [comment]
you are not alone - it is in fact Qt as it occours in Windows too.

**Comment by tsujan** [comment]
I changed FeatherPad's font dialog because of this issue and also because `QFontDialog` couldn't distinguish between fixed-pitched and other fonts (`QFontDialog::MonospacedFonts` is almost good for nothing):

![fontdialog](https://user-images.githubusercontent.com/981076/62376445-e1674580-b555-11e9-8cd0-853d808fcef3.png)

It supports 4 font weights and if "Programming Fonts" is checked, only fixed-pitched fonts will be shown, without being italic or bold (the default for a text editor). `QFontComboBox` doesn't have the problems of `QFontDialog`.

If the issue isn't fixed by Qt devs, LXQt could have a similar font dialog or better. There's always a way with Qt.
