### ISSUE TITLE
Desktop font seperate from "Appearance" settings

### ISSUE THREAD

**Issue by someguy2013** [lxqt/lxqt#1712]
I'm using Lubuntu 19.04 with LXQt desktop.

This is an enhancement suggestion. 

Since the desktop is essentially PCManFM-Qt (the desktop is a folder?), it seems confusing to me to navigate to Preferences->LXQt Settings->Appearance, and have a font setting -- but have to go somewhere else (right click on desktop) to set the desktop's font.

The right-click access is handy. But, I think the Appearance dialog should say something about how that's the appearance of everything except the desktop(?). Maybe provide a button to invoke the desktop font setting from Appearance (as a convenience)?  

It seems like those two could be tied together a little more. Some of the Desktop's particiular settings are "Appearance-type" items. It seems like the could be adjusted from *either* place. As a convenience. (I think newbies might the distinction between the two, where to go to get all of it together, etc.).

**Comment by tsujan** [comment]
Thanks for your suggestion but:

> It seems like those two could be tied together a little more.

No, they can't. pcmanfm-qt is a stand-alone app, having its special settings. Configuration Center just calls pcmanfm-qt's desktop settings; nothing more. Of course, pcmanfm-qt's style follows what is set in Appearance, for example, because the style isn't a special setting and is shred by all Qt apps.

It's highly preferable not to make pcmanfm-qt dependent on LXQt for its special settings.
