### ISSUE TITLE
Trusted .desktop files inconsistency

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt#1718]
Not sure about this all: there is this "trust this file" option in the context menu and if checked it will launch, if unchecked it will show a dialog "Do you want to open or execute this file?". Some appimages add a .desktop file in this location.

Until here all good, but there is an inconsistency for files in ~/.local/share/applications if launched by the menu or lxqt-runner: they are
a) present 
b) will open also if untrusted without any further dialog.
##### Expected Behavior

If we have "untrusted" desktop files they should not be displayed in the menu or there should be a warning (better IHMO).
##### Current Behavior

Launching "untrusted" .desktop files from the menu shows no info about missing trust.
##### Possible Solution

Add a warning with explanation or a checkbox "Trust from now on" when launching.
##### Steps to Reproduce (for bugs)

1. Add a custom .desktop file in ~/.local/share/applications
2. Search it in the menu or with runner and launch it.

**Comment by tsujan** [comment]
(1) Any word — "trustworthy", "nice", "sexy"…  — could have been used. Its existence as a GLib metadata is completely neutral unless an app reacts to it. Purely Qt-based apps have no way to know it, let alone to react to it.

 (2) The "trust" meta-data isn't just for desktop files. It's for all *executable* files inside user's home, although it's shown by an emblem only for desktop files. However, most importantly:

 (3) When an item appears on a menu, it's there to be executed by user. That's while, items inside the view of a file manager are there to be *opened*, instead of being executed. The "trust" meta-data is a way to trust them for execution instead. In other words, "trust" is a file management concept.
