### ISSUE TITLE
desktop switch with window grouping and only windows of current dektop activated 

### ISSUE THREAD

**Issue by QuImUfu** [lxqt/lxqt#1725]
I am using Lubuntu 19.04. If this is the wrong place to report this issue, please direct me to the correct one.  
#### Behavior
Have "only show windows of current desktop" and "window grouping" activated in the Taskbar settings.  
Open two (or more) windows of the same applications on one desktop (dt1).  
Open one on another desktop (dt2).  
Minimize both windows on dt1.
Click on their window group.
##### Expected
The list of windows on dt1 should be displayed, nothing else should happen.
##### Current 
It switches to the open window on dt2.

#### Context
I normally keep different parts of my activity on different desktops and clicking on taskbar entries switching between these annoys me and creates confusion.  

#### System Information
* Distribution & Version: LXQT 14.1 on Lubuntu 19.04
* Kernel: 5.0.0-17-generic
* liblxqt package version: 0.14.1-0ubuntu1

**Comment by tsujan** [comment]
If you only want to see the list, you shouldn't click on the taskbar button but just put the cursor over it; then the list will be shown. This is how taskbar works.

That being said, if the taskbar button is *clicked* in the above-mentioned scenario, the desktop should not be switched but one of the minimized windows on the current desktop should be un-minimized because only windows of the current desktop are shown on taskbar. So, IMO, there's a bug here.

@palinek?

**Comment by palinek** [comment]
>  because only windows of the current desktop are shown on taskbar. 

This is configurable, you are free to choose...

**Comment by QuImUfu** [comment]
yes, but i configured to only show the ones on the current desktop, nevertheless clicking on this group switches desktop, opening a window that is not part of the group i clicked on, because it is on a different desktop.

**Comment by tsujan** [comment]
It's possible that I'm missing something but, IMHO, when other desktops are *excluded* from the task button, showing windows from other desktops on clicking it — instead of minimizing/un-minimizing a window from the current desktop — feels confusing.

**Comment by tsujan** [comment]
This may be possible with something like:
```c++
void LXQtTaskGroup::mouseReleaseEvent(QMouseEvent* event) {
    if (event->button() == Qt::LeftButton) {
        if (auto btn = mButtonHash.value(windowId())) {
            if (btn->isVisibleTo(mPopup)) {
                LXQtTaskButton::mouseReleaseEvent(event);
                return;
            }
        }
    }
    QToolButton::mouseReleaseEvent(event);
}
```
But I haven't had time to test it, let alone to consider its possible side effects with other settings.

**Comment by tsujan** [comment]
After giving it some thought, I have a more radical suggestion: Not doing anything with windows on clicking the task button *when the it has a non-empty group*. Instead, the group popup could be shown so that the user could choose what to do with its windows. Actually, @QuImUfu suggested the same idea:

> The list of windows on dt1 should be displayed, nothing else should happen.

My reason is that the current behavior of the task button isn't intuitive: the user clicks on it and a "random" window is focused/minimized/un-minimized or, sometimes, nothing happens. Of course, it isn't random and there's a logic to it but that logic is counter-intuitive in practice (IMHO).

So, I started to use this to get rid of the above-mentioned "randomness":
```c++
void LXQtTaskGroup::mouseReleaseEvent(QMouseEvent* event)
{
    // do nothing on left button release if there is a group
    if (event->button() == Qt::LeftButton && visibleButtonsCount() == 1)
        LXQtTaskButton::mouseReleaseEvent(event);
    else
        QToolButton::mouseReleaseEvent(event);
}
```
Please tell me if this idea had been discussed and rejected before!
