### ISSUE TITLE
lxqt-config-monitor seems to randomly forget configs, config is buggy/wonky

### ISSUE THREAD

**Issue by atsepkov** [lxqt/lxqt#1738]
##### Expected Behavior

I have a Lenovo laptop that's usually plugged into a docking station with 2 external monitors (3 total, including laptop screen). The laptop is almost never unplugged from the dock, but one of the monitors is often switched to my other machine via KVM. The expected behavior is for the laptop to either switch to 2 monitors when 3rd monitor is showing input form another PC or to remember it (which is usually does, but not always).

##### Current Behavior

Occasionally LXQT forgets about the 3rd monitor and disables it, requiring me to manually reenable it in lxqt-config-monitor. When this occurs, it also seems to forget the monitor position, requiring me to manually drag/align it in the "Monitor Settings" UI. This UI is also wonky and not user-friendly, often requiring several attempts to get it pixel-perfect (otherwise I got partial monitor overlap, or ~20-30 pixel misalignment between monitors). Moreover, some settings have no effect at all (even though they should) until the alignment is changed.

One example of such setting is which monitor is selected as "primary". Changing primary monitor has no effect until I also drag the displays around in the UI so the system realizes that something has changed. Often (when system accidentally resets the primary monitor because of the KVM), this means that I have to drag/apply the changes twice (once to move them out of alignment so that the system realizes that something has changed, and 2nd time back to where they were to fix the misalignment I caused for the sole purpose of making primary display change take effect).

I've also noticed that despite saving the settings for alignment (as the GUI allows), applying saved settings afterwards doesn't always seem to have an effect, requiring the awkward drag-and-drop via clumsy UI again.

##### Possible Solution

There are several issues at play here, changing either one would be a huge quality of life improvement, but I'd prefer a change to all:
1. Accept a text-based config file I can reuse instead of trying to drag-and-drop the alignment via UI (hopefully something I can trigger via terminal/command)
2. Fix the issue with primary display change getting ignored until screen alignment also changes (this may be an xrandr bug since I've seen similar behavior when working directly with xrandr)
3. Make the system more resilient to extended monitor disconnection/connection, so it doesn't randomly forget a monitor. Or, like Mac, remember several previous configs and automatically pick the most sane one based on connected monitors.
4. Fix whatever issue seems to make saved config not get applied.

##### Steps to Reproduce (for bugs)

1. Configure several monitors (3 in my example, in following horizontal configuration: [laptop: extended][desktop: primary][desktop: extended/kvm])
2. Switch right-most monitor to different machine
3. Wait until LXQT goes into sleep/standby
4. Reactivate LXQT, the appearance/disappearance of right-most extended monitor may cause it to forget about it, may also cause it to forget which monitor is primary and switch the left-most laptop screen back to primary (this can also sometimes occur during reboot, despite saving the config). Applying older config from lxqt-config-monitor may have no effect, requiring manual reconfiguration - which will forget the position of the extended monitor and require pixel-perfect drag-and-dropping via the awkward UI.

##### Context

This issue affects me because I have to realign my monitors at least once a day, and it's time-consuming/frustrating, especially with the poor UI. Accepting a text-based config file would improve the issue for me, even if the bugs were unsolved (since I could map it to a bash command).

##### System Information

* Vanilla Lubuntu 19.04 install
* Lenovo T460s + docking station + 2 external monitors to the right of the laptop screen (desktop monitor in the center is always primary and is always attached to the laptop), desktop monitor on the far right attached via KVM to another machine, often switches.

**Comment by selairi** [comment]
I haven't got my second display, now. But, the monitor settings are not
loaded after sleep. Then, it is a lxqt-monitor issue.

Moreover, it is possible a bug in xrandr. Please, send me your xrandr
output before and after sleep.

Maybe, we could write a simple xrandr script that you could run with a key
shortcut. Then you would work with your 3 displays until the bug is solved.

El lunes, 12 de agosto de 2019, Alexander Tsepkov <notifications@github.com>
escribió:
> Expected Behavior
>
> I have a Lenovo laptop that's usually plugged into a docking station with
2 external monitors (3 total, including laptop screen). The laptop is
almost never unplugged from the dock, but one of the monitors is often
switched to my other machine via KVM. The expected behavior is for the
laptop to either switch to 2 monitors when 3rd monitor is showing input
form another PC or to remember it (which is usually does, but not always).
>
> Current Behavior
>
> Occasionally LXQT forgets about the 3rd monitor and disables it,
requiring me to manually reenable it in lxqt-config-monitor. When this
occurs, it also seems to forget the monitor position, requiring me to
manually drag/align it in the "Monitor Settings" UI. This UI is also wonky
and not user-friendly, often requiring several attempts to get it
pixel-perfect (otherwise I got partial monitor overlap, or ~20-30 pixel
misalignment between monitors). Moreover, some settings have no effect at
all (even though they should) until the alignment is changed.
>
> One example of such setting is which monitor is selected as "primary".
Changing primary monitor has no effect until I also drag the displays
around in the UI so the system realizes that something has changed. Often
(when system accidentally resets the primary monitor because of the KVM),
this means that I have to drag/apply the changes twice (once to move them
out of alignment so that the system realizes that something has changed,
and 2nd time back to where they were to fix the misalignment I caused for
the sole purpose of making primary display change take effect).
>
> I've also noticed that despite saving the settings for alignment (as the
GUI allows), applying saved settings afterwards doesn't always seem to have
an effect, requiring the awkward drag-and-drop via clumsy UI again.
>
> Possible Solution
>
> There are several issues at play here, changing either one would be a
huge quality of life improvement, but I'd prefer a change to all:
>
> Accept a text-based config file I can reuse instead of trying to
drag-and-drop the alignment via UI (hopefully something I can trigger via
terminal/command)
> Fix the issue with primary display change getting ignored until screen
alignment also changes (this may be an xrandr bug since I've seen similar
behavior when working directly with xrandr)
> Make the system more resilient to extended monitor
disconnection/connection, so it doesn't randomly forget a monitor. Or, like
Mac, remember several previous configs and automatically pick the most sane
one based on connected monitors.
> Fix whatever issue seems to make saved config not get applied.
>
> Steps to Reproduce (for bugs)
>
> Configure several monitors (3 in my example, in following horizontal
configuration: [laptop: extended][desktop: primary][desktop: extended/kvm])
> Switch right-most monitor to different machine
> Wait until LXQT goes into sleep/standby
> Reactivate LXQT, the appearance/disappearance of right-most extended
monitor may cause it to forget about it, may also cause it to forget which
monitor is primary and switch the left-most laptop screen back to primary
(this can also sometimes occur during reboot, despite saving the config).
Applying older config from lxqt-config-monitor may have no effect,
requiring manual reconfiguration - which will forget the position of the
extended monitor and require pixel-perfect drag-and-dropping via the
awkward UI.
>
> Context
>
> This issue affects me because I have to realign my monitors at least once
a day, and it's time-consuming/frustrating, especially with the poor UI.
Accepting a text-based config file would improve the issue for me, even if
the bugs were unsolved (since I could map it to a bash command).
>
> System Information
>
> Vanilla Lubuntu 19.04 install
> Lenovo T460s + docking station + 2 external monitors to the right of the
laptop screen (desktop monitor in the center is always primary and is
always attached to the laptop), desktop monitor on the far right attached
via KVM to another machine, often switches.

**Comment by tsujan** [comment]
>  This UI is also wonky and not user-friendly, often requiring several attempts to get it pixel-perfect

I've seen that too. I use it only for a rough alignment and then go to the spin-boxes. IMO, the basic idea is good but the DND code needs improvement.

**Comment by atsepkov** [comment]
@selairi thanks, I'm traveling with a different laptop now, will send the info you requested once I'm back. The display after sleep issue does not happen 100% of the time, I'll attach it when it reappears. As @tsujan mentioned, simply having a more precise/intuitive UI would help a lot (even showing/editing exact coordinates for each monitor on the UI).

**Comment by selairi** [comment]
> I've seen that too. I use it only for a rough alignment and then go to the spin-boxes. IMO, the basic idea is good but the DND code needs improvement.

I think that we could change drag and drop code:
The display which is being dragged could be automatically moved to the nearest display. The nearest display could show an area, as in Fig. 1:
![20190818_123756](https://user-images.githubusercontent.com/1163139/63224985-28973c80-c1cc-11e9-91b7-d54e9e7ccfea.jpg)
Display 1 is being dragged, as depicted in fig. 1. Display 5 is the nearest one. It will show the dashed area when the display 1 reaches the dashed area, that will not be visible until the monitor is over it.
However, if display 2 is at the same distance of display 3 than display 1, no critical area will be shown (see Fig. 2)
If the user wants to align display 1 to top of display 2, the user will have to put a or b cornels to alpha area (see Fig. 3). If the user wants to align to bottom of display 2, the user will have to drag c or d cornels to beta area.
A similar procedure is expected when alignment to left or right is required (see Fig. 4).
What do you think about it?

**Comment by tsujan** [comment]
@selairi, your idea seems good to me. Unfortunately, I haven't had time to look into this code but I like to do so. I have a feeling that the faulty behavior can be corrected without rewriting it.

**Comment by selairi** [comment]
Hi,

I have just uploaded the commented method to drag and drop monitors. You
can see at:

https://github.com/selairi/lxqt-config

I found a bug in the older one, QGraphicsView uses float to store
positions. MonitorPicture class uses int. The cast from float to int
sometimes loses one or two pixels in monitor position.

To my mind, the new method is easier to users.

On the order hand, I am thinking about how to solve the "lost" of monitors
after suspend or after reconnections. A new service is required. I have
done some experiments, but I found that i915 driver doesn't sometimes
update the connected monitors list:

https://unix.stackexchange.com/questions/439545/how-to-make-linux-detect-re-probe-monitors-with-intel-i915-driver

In order to check connected monitors, I am reading
/sys/devices/pci.../cardX/cardX-HDMIX.../status. It is Wayland and X11
compatible. If I find something effetive, I will write you.

**Comment by tsujan** [comment]
@selairi 

I tested your patch. It works like a charm -- much better than before. I didn't need to use spin-boxes anymore because the DND GUI aligned the screens nicely.

**Comment by selairi** [comment]
I'm doing some experiments. They work as expected. I have to change
lxqt-session:

https://github.com/selairi/lxqt-session

It will run "lxqt-config-monitor -l", when a new monitor is connected.

I have also changed lxqt-config-monitor:

https://github.com/selairi/lxqt-config

Test it, please!

Note: Intel i915 doesn't sometimes detect the new display connection or
disconnection. You have to run xrandr command.

**Comment by selairi** [comment]
Could this issue be closed?
