### ISSUE TITLE
LXQt display ghosting 

### ISSUE THREAD

**Issue by kbeins** [lxqt/lxqt#1768]
Display ghosting when dragging icons or opening menus.
Have tested several machines and this only occurring on Intel NUC 8i3BEK - and only when
installing or using FOCAL Lubuntu 20.04 .

This also is occurring in the Live sessions before install.

I have tested Lubuntu Eoan 19.01 and Lubuntu Bionic 18.04.04 on this machine and cannot reproduce the issue.

**Comment by tsujan** [comment]
Should be reported to the Lubuntu team.

**Comment by agaida** [comment]
thanks

**Comment by kbeins** [comment]
Tested again today:
Live session: tested for bug 1864526 display ghosting when dragging icons or opening menus.Selecting "compton" the ghosting stops. This was present on test machine:
Dell Latitude 7280 - Intel i5-7300U CPU 2.70GHz – 16Gb RAM – Intel HD Graphics 620 – Intel Ethernet I219-LM Gigabit – Intel Wireless AC8265 – Intel wireless Bluetooth – 500GB hard disk.

**Comment by agaida** [comment]
@kbeins - again, not our problem, there are some things you could check - try the compton fork, not in debian or ubuntu yet, use a different DM (i would suggest xfce4 or kwin) - but there is nothing we can or will do in LXQt

**Comment by tsujan** [comment]
Although this report isn't related to LXQt at all:

The original Compton is dead and shouldn't be used. Its fork (https://github.com/yshui/compton) may be OK; at least, it's being developed.

**Comment by agaida** [comment]
@tsujan - i suggested an new project (github,om/compton is used) like github.om/compton-compositor years ago - xorg goes south, compton-comp willl do so too - so that's not really our problem.

**Comment by tsujan** [comment]
> so that's not really our problem.

I know.

BTW, and not really related to this, after the next release, I'll try to make some components, that I've worked on them, compatible with Wayland. If, in addition, LXQt session could make use of Wayland-KWin and Wayfire, it'll be very nice. I don't care about other Wayland compositors but KWin is quite mature and, IMO, Wayfire (which can also be called "Wayland Compiz") has a bright future, although it needs lots of work.

I remembered that only because we talked about an old X11 compositor (compton).

**Comment by wxl** [comment]
As one of Lubuntu's developers, I agree that the responsibility for this problem is completely outside the wheelhouse of LXQt and the bug should be reported [downstream](https://phab.lubuntu.me/w/bugs/). In fact, all bugs in Lubuntu should be reported downstream. Triagers will push it upstream as needed.

I will add, though, that the problem seems to have been *resolved* by using Compton (which is off by default in Lubuntu), as are a lot of very basic display problems (e.g. screen tearing). That said, Compton is dead and the fork (now called Picom) is ultimately the future. I did some initial packaging on this which was promising but didn't file the necessary paperwork in Debian. It's [on the TODO list](https://phab.lubuntu.me/T96), though.

**Comment by tsujan** [comment]
> Compton is dead and the fork (now called Picom)...

Yes. https://github.com/yshui/compton goes to https://github.com/yshui/picom.

**Comment by kbeins** [comment]
Sorry for any confusion caused. The bug was originally posted "downstream" and I was advised to send it "upstream".Will be more carefull in the future.

See for original report:

https://bugs.launchpad.net/bugs/1864526

Leó K.

**Comment by wxl** [comment]
@kbeins Didn't realize that was you, Leó! 

As I said above, use our tracker for everything and we'll push things upstream if needed. If you want to take on the task of confirming and triaging bugs yourself, it's essential to show that you can recreate it upstream. I always start first with Debian. Then it's good to look through issues and see if the problem's already been solved in Git master or just build from sources and see for yourself. Then, if you're certain it's a valid issue, you should still first file a report on our tracker before creating the upstream issue and linking to the downstream one. This will help us independently track the development of the upstream solution as well as the downstream implementation. 

Thanks, as always, for helping with Lubuntu!
