### ISSUE TITLE
Screen Tearing in Lubuntu 19.10

### ISSUE THREAD

**Issue by paulvonlux** [lxqt/lxqt#1771]
Screen Tearing in Lubuntu 19.10 i got if fix by doing this.
I have an Intel ultrabook with 1007u processor.

https://askubuntu.com/questions/240923/enable-sync-to-vblank-on-lxde-with-intel-video-card

**Comment by tsujan** [comment]
Please don't report Lubuntu problems/solutions here. This is LXQt bug tracker, not Lubuntu's.

**Comment by paulvonlux** [comment]
> Please don't report Lubuntu problems/solutions here. This is LXQt bug tracker, not Lubuntu's.

Yeah but Lubutu is your MAIN client...most bugs will come from LUBUNTU in 20.04 LTS...

**Comment by tsujan** [comment]
> Yeah but Lubutu is your MAIN client

No, it isn't.

Lubuntu may use LXQt but LXQt isn't made for Lubuntu.

**Comment by wxl** [comment]
@paulvonlux As a Lubuntu developer (and Lubuntu Council member), I can certainly say that the vast majority of LXQt development is done by people who are not Lubuntu users and that LXQt, in general, strives for agnosticism, both in terms of distros that provide it, as well as interoperability with components outside of its scope (e.g. they don't just rewrite the code because Lubuntu's chosen window manager, Openbox, has a quirk that no other window manager has). There are things that I would like LXQt to do because it would make my job easier :) but I actually respect and wholeheartedly support this conscious design decision.

Finally, as a former Ubuntu Community Council member, I will point out that a little respect goes a long way. #1774 is a great example of how failing to heed the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct) can have disastrous results. I will add there's a particular portion of the CoC that emphasizes its relevance everywhere, so it applies here in just the same way:

> The Code of Conduct governs how we behave in public or in private whenever the project will be judged by our actions. We expect it to be honoured by everyone who represents the project officially or informally, claims affiliation with the project, or participates directly.
