### ISSUE TITLE
[Feature Request] Add gtk3-nocsd with a graphical front-end

### ISSUE THREAD

**Issue by e-trace** [lxqt/lxqt#1789]
Hi everybody,

gtk3 applications using CSD in qt desktops like LXQT (and not only) partially ruin the user experience: the applications using CSD haven't the same look of other apps, and you can't use all the functions of your favorite windows manager.

There is a project called [gtk3-nocsd](https://github.com/ZaWertun/gtk3-nocsd) (originally developed by PCMan, but now forked), that can disable CSD.

I'd like if you could add gtk3-nocsd to LXQT, with a graphical tool that can make you able to turn off/on CSD as you want.

**Comment by tsujan** [comment]
> ... partially ruin the user experience

I'm afraid that's Gnome devs' fault and they should fix it (but they will never).

LXQt is a Qt DE for several reasons, one of which is getting rid of GTK hassles.

You could use GTK apps inside LXQt but may not need most of them because there are Qt-based counterparts. Using Firefox, Thunderbird and Inkscape is understandable (the last two are a must for many) but none of them has CSD.

**Comment by e-trace** [comment]
Some other apps uses CSD, for example Bleachbit
I think a tool like that could be useful not only for LXQT users, but for the entire Linux community.

> getting rid of GTK hassles.

and a tool like that can help many users, also not expert users, to get rid of that crap called CSD.
If Gnome devs have no brain, maybe people that have brain should use it.

I've no technical skills to write a tool like that, but I would if I were able  to do that.

Of course, it's you choose, 
Thank you

**Comment by tsujan** [comment]
> and a tool like that can help many users

I understand but we have no time to waste in following backward-incompatible changes Gnome devs make to GTK every now and then -- even KDE devs got tired of that -- and we definitely don't want to receive bug reports because of them.

You need to find an individual developer who cares about how GTK looks.
