### ISSUE TITLE
Missing configuration method for  automated configuration changes from scripts.

### ISSUE THREAD

**Issue by hadmut** [lxqt/lxqt#1802]
LXQt (using Lubuntu 20.04) comes with a rich set of graphical tools (lxqt-config) to change settings of all kind, like panel, terminal, window manager settings. 

However, it's still graphical tools and requires mouse sports. I need to configure several computers in the same way, i.e. through a shell script or with the configuration tool puppet. 

Even if using tools for inifiles and changing the settings in ~/.config/* where LXQT keeps its configuration, the changes are without effect. Strange enough, the graphical configuration tools then show the state in the file, while the window manager doesn't follow.  

I did not find any hint in the man pages or anywhere else how to change settings automatically from scripts.

##### Expected Behavior

 In the good old days of Gnome, there was command line tools to change settings and manpages for the tools. Are there similar tools for LXQT?

I need to apply the same settings (pcman, terminal, toolbar,...) automatically to plenty of computers. 

##### System Information

Lubuntu 20.04

* Distribution & Version: Lubuntu 20.04
* Kernel: -
* Qt Version:  
* liblxqt Version: 0.14.1 
* Package version: 0.14.1-0ubuntu1

**Comment by tsujan** [comment]
1. Config files are there for apps, not for users.
 2. Changing a config file manually doesn't have any effect when the app/daemon is running because the file will be overwritten. That's not specific to LXQt.
 3. Window manager is not a part of LXQt.
 4. Terminal? If you mean QTerminal, its config file is in its own folder. The same is true for pcmanfm-qt.
 5. If you need the same settings for several computers, copy and paste the config folders/files *when the apps aren't running*, i.e. outside an LXQt session. That isn't specific to LXQt either.

**Comment by hadmut** [comment]
The answer is completely useless. 

Gnome and XFCE were able to solve that problem.

**Comment by tsujan** [comment]
> The answer is completely useless.

This isn't a forum but LXQt bug tracker and I'm not here to give "useful" answers to your questions.

**Comment by Vladimir-csp** [comment]
Higher conepts aside, refreshing configuration by a signal (USR1 for example) would be a nice feature to have.

**Comment by tsujan** [comment]
> refreshing configuration by a signal (USR1 for example) would be a nice feature to have.

Theoretically possible for each and every component but, practically, who has time or the slightest reason to do it? To say nothing of the time needed to review patches by a developer who really thinks it's nice enough to have.

Stop daemon/app → overwrite its config → start daemon/app.
