### ISSUE TITLE
PCManFM-Qt: Double-click raise an unexpected multi-selection of all files

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt#1811]
IDK if this is an expected feature that I ignore or caused by a defective mouse but I have never seen something like this before:
when double click a file or folder in PCManFM-Qt listview, all files get selected.

##### Expected Behavior
When double clicking a file I expect an open file/directory action.

##### Current Behavior
It doesn't happens in all cases, it seems it happens if after the double click the mouse has moved, say after an half second. It seems to me like a bug of some unrelated multi selection code.

![unexpected-multiselection](https://user-images.githubusercontent.com/1171962/84664598-15094f00-af1f-11ea-9dd5-f870d915739f.png)

##### Possible Solution
I don't know the code, I suppose there is some part that should be removed or some wrong condition.

##### Steps to Reproduce (for bugs)
1. Set the default view to detailed
2. In any folder try to click a subfolder or file and quickly move the mouse after the double-click.

##### Context
I wasn't able to test other view modes than detailed view, os it might be related only in that context.

##### System Information
* Distribution & Version: Archlinux
* Kernel: 5.6.15-arch1-1
* Qt Version: qt5-base 5.15.0-3
* liblxqt Version: liblxqt 0.15.1-1
* Package version: pcmanfm-qt 0.15.1-1

**Comment by tsujan** [comment]
It was very hard to reproduce but I succeeded in reproducing it with Fusion, Breeze and Kvantum but only in the detailed list mode.

Provided that the double-click mode is chosen both in LXQt and in pacmanfm-qt, then if the cursor moves *immediately after* double clicking a folder, all of the contents of the child folder will be selected in the detailed list mode. The "immediately after" part is hard to do ;)

Will look into it. Thanks for the report!

**Comment by Chiitoo** [comment]
The cursor does not need to move immediately after; one only needs to keep holding down the second click of the double click, then move the pointer.

(I noticed this issue quite some time ago, but never got to reporting it still... so thanks from me too!)

**Comment by tsujan** [comment]
@Chiitoo 
Thanks! That should make debugging much easier; I won't have to rely on chance :)

**Comment by tsujan** [comment]
OK, I found the problem. Its fix was very easy (a simple condition was missing).

However, Qt's default behavior isn't very good either. I tested with Qt's default file dialog (not that of LXQt): When a folder is opened by double clicking and the left mouse button isn't released, if the mouse moves a little, the item under the cursor will be selected.

I'll see if I could include a workaround in the upcoming PR. Since Qt's default behavior isn't very bad, I'll only fix the bug if no simple workaround is found. So, it may take a little longer than I thought...

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/libfm-qt/pull/549

Qt's default behavior wasn't a problem because the mouse movement should be greater than the drag distance for the item to be selected.

@redtide
If you're experienced in making Arch packages with patches, you don't need my advice; [the patch](https://github.com/lxqt/libfm-qt/pull/549.patch) is compatible with libfm-qt 0.15.1 too — just restart the Desktop session after applying it. Otherwise, you might need to wait for the next release (not soon).

Thanks again for reporting this hidden bug!

**Comment by redtide** [comment]
Thanks! I tried making a PKGBUILD meanwhile but I encountered some strange makepkg conflict issue, I'll ask AUR guys tomorrow.

**Comment by redtide** [comment]
I haven't received feedback from AUR people on IRC yet, so I tried a dirty
replacement using the original package name in [this PKGBUILD].
Unless I did something wrong there after several tries, there is something strange with the Archlinux packages or pacman; no matter what it insists to reinstall the original one, so I have no way to test it.

[this PKGBUILD]: https://gist.github.com/redtide/71b5a96a8f407d3da06fd0907ef06642

**Comment by tsujan** [comment]
> EDIT: Got an useful help and it installed, no more selection of all files but with the same procedure one file get selected to start a multiselection while the mouse button is down.

That's Qt's default behavior and, as mentioned above, it's OK because the cursor movement should be greater than the drag distance (usually 10 px).

**Comment by redtide** [comment]
OK, thanks, so I can close this?
