### ISSUE TITLE
gtk_status_icon_is_embedded always returns false.

### ISSUE THREAD

**Issue by ekpyron** [lxqt/lxqt#1817]
The system tray doesn't properly work at least with GTK-2.0 causing issues with programs like e.g. claws-mail (see https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=3922).

In particular ``gtk_status_icon_is_embedded`` doesn't return the status correctly.

Take the following example program:

```
#include <gtk/gtk.h>

static GtkStatusIcon *status_icon = NULL;

static void destroy(GtkWidget *widget, gpointer data)
{
    gtk_main_quit ();
}

static gboolean chkStatusIcon(gpointer pIn)
{
  printf("embedded: %d\n", gtk_status_icon_is_embedded(status_icon));
  return FALSE;
}

int main(int argc, char* argv[])
{
    gtk_init( &argc, &argv );
    status_icon = gtk_status_icon_new_from_stock(GTK_STOCK_QUIT);
    gtk_status_icon_set_visible(status_icon, TRUE); 
    g_idle_add((GSourceFunc) chkStatusIcon, NULL);

    g_signal_connect (G_OBJECT (status_icon), "activate", G_CALLBACK(destroy), NULL);

    gtk_main();

    return 0;

}
```

This behaves differently on LXQt than on e.g. KDE.

##### Expected Behavior

``gtk_status_icon_is_embedded`` should return ``TRUE``, so this should output
``embedded: 1``

##### Current Behavior

``gtk_status_icon_is_embedded`` returns ``FALSE``, so the example program outputs
``embedded: 0``

##### Possible Solution

Unfortunately, I have no idea what kind of interactions lead to this behavior, resp. how to make GTK report this correctly.

##### Steps to Reproduce (for bugs)

1. Paste the snippet above into ``test.c``
2. ``gcc test.c $(pkg-config gtk+-2.0 --libs --cflags) && ./a.out``

##### Context

GTK 2.0 software relies on this information to be correct. E.g. claws-mail will not stay hidden in the tray, but pull up its main window, if the status icon is not properly reported as embedded in the tray.

##### System Information

This seems to happen on various systems. I tested it in a Debian Sid Virtual Machine just now.
* Distribution & Version: Debian Sid
* Kernel: 5.6.0
* Qt Version: 5.12.5
* liblxqt Version: 0.14.1

~~But it is also appears to be happening on up-to-date Archlinux (so with the most recent LXQt release. I'll confirm this soon and will edit this part here accordingly).~~
EDIT: I just confirmed: this does also happen on up-to-date Archlinux:
* Distribution & Version: Archlinux (2020-06-22)
* Kernel: 5.7.4-arch1-1
* Qt Version: 5.15.0
* liblxqt Version: 0.15.1
* lxqt-panel: 0.15.1

It happens independently of the chosen window manager (I tried at least openbox and KWin), so my guess is that this is an issue with the LXQt system tray.

**Comment by ekpyron** [comment]
This may actually be rather an issue in https://github.com/lxqt/lxqt-panel, but I still opened it here, since I'm not entirely sure about where this is coming from.

**Comment by tsujan** [comment]
As is mentioned several times in some other reports, System Tray is obsolete and Status Notifier should be used instead of it (we'll add a warning dialog to LXQt 0.16.0).

Now, either Claws Mail and similar apps update their codes to be compatible with https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/ or their tray icon won't work with it.

`gtk_status_icon_is_embedded` or any GTK function isn't our concern. LXQt is a Qt based DE; we don't have GTK codes.

**Comment by ekpyron** [comment]
Well, this does work properly on KDE and on most other Desktop Environments, even those that don't directly interact with GTK either, so there ought to be a way to do this gracefully. IMHO LXQt being Qt-based doesn't mean that it should behave in a way that prevents GTK applications (be it legacy GTK 2.0 applications) to work on it, so it seems to me that this *is* indeed a bug in LXQt.

However, I don't know myself what it would take to make GTK 2.0 properly report on the system tray and why it doesn't with LXQt specifically in contrast to other systems - and it's of course your prerogative to just ignore this, not fix this bug and point fingers elsewhere ;-).

**Comment by tsujan** [comment]
> Well, this does work properly on KDE

Your link (https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=3922) says otherwise. Even if Claws Mail devs have added a workaround for KDE, it's for KDE.

The "new" status notifier specification isn't our invention (actually, it's old now). We have to go with what's up-to-date and ignore what's obsolete. Some devs may still prefer GTK2 to GTK3 and that's understandable but its limitations aren't our problem to solve. As far as GTK (whether 2 or 3) follows standards, its apps should be OK -- to say nothing about the fact that Gnome devs have removed the tray capability from Gnome and they're in charge of GTK3 too; again, not our concern.

**Comment by ekpyron** [comment]
The issue with KDE in the link is a separate issue (of race conditions between autostart applications and the system tray on autostart). The simple example program I provided in the issue above does work correctly on KDE, so this *is* a matter of the desktop environment.

The interesting question would be where this difference is coming from and why KDE is better at being backwards compatible with GTK2 apps in this regard.

I can fully understand the point of not wanting to support stuff that's obsolete, though.
Still this is a somewhat slippery slope - it *is* nice for a desktop environment to have as many applications working on it as possible after all ;-). If I had the time right now, I'd look into what KDE does differently here, but unfortunately I don't... If changing this was a major undertaking and would e.g. require dynamically loading GTK, if available, and notifying it about tray-related stuff, I'd definitely not go for it, if I were you - but it may also be something trivial, I don't know.

**Comment by tsujan** [comment]
> it is nice for a desktop environment to have as many applications working on it as possible after all ;-).

Yes, it is. But GTK is totally out of question.

I don't know about KDE but you could imagine that KDE was developed even before GTK2, so it may have codes from very old times. LXQt was started to migrate away from GTK because of what Gnome devs did to GTK. If that wasn't the case, LXDE would still be developed and we wouldn't have LXQt.

Anyway, we haven't removed Panel's System Tray plugin and don't have a plan to remove it soon. You might want to work on its code and make a PR. Please note that your PR (1) shouldn't contain any extra dependency -- especially a GTK one -- and (2) should be limited to the code of System Tray.

**Comment by ekpyron** [comment]
Ok, fair enough. If I have some spare time for looking into it, I might have a go at it, but to be honest it has been time-consuming and echausting to track down the issue this far already :-).
But thank you very much for clarifying your position on this in any case!

**Comment by tsujan** [comment]
> but to be honest it has been time-consuming and exhausting to track down the issue this far already

I understand completely and wonder how motivated you have been about this issue.

If I were a Claws Mail developer and wanted to stay with GTK, I'd port it to GTK3 and accept what Gnome devs have done to it, instead of dealing with the growing hassles of GTK2. But, frankly, if I were a Claws Mail developer, I'd totally migrate away from GTK ;)

**Comment by ekpyron** [comment]
Yeah, well... unfortunately I never found an alternative to claws-mail that has an equally small footprint and isn't cluttered, while still being rather feature-full... at least none that I liked... so I really like claws-mail :-) - but I have been bothered by this particular issue for years :-D.
But yeah - asking Claws Mail to migrate away from GTK2 is probably an even higher ask than trying to get legacy support for GTK2 from you :-). Let's see, maybe I'll find some time in the next weeks to figure this out further myself then.

**Comment by tsujan** [comment]
Yes, some apps are unique.

BTW, this may help:

I still use `ClipIt`, which is a GTK2 app. Its tray icon is shown by Status Notifier without any problem. It uses `libappindicator-gtk2`. Maybe, a similar code could be used in Claws Mail. Sorry, it's more than a decade since I coded in GTK2; I remember almost nothing of GTK coding ;)

**Comment by Chiitoo** [comment]
I'm also using Claws Mail, but haven't noticed this exact behaviour.

It might be due to the fact that, for my personal use, I revert a particular commit [1] that fixed a different issue [2], because said fix makes the panel auto-hide when hovering over the Claws Mail tray icon.

If the behaviour described here started with the same fix, I imagine it might give some context for how to fix this without re-introducing an old bug.

1. https://github.com/lxqt/lxqt-panel/commit/b8c33e97
2. https://github.com/lxqt/lxqt-panel/issues/1266

**Comment by tsujan** [comment]
@Chiitoo 
That fix is for the whole panel: anywhere with a right-click menu. We can't reverse it only for System Tray.

I think GTK2 apps that are still being developed need to implement ClipIt's solution and use Status Notifier. ClipIt shows that's possible.

**Comment by Chiitoo** [comment]
Yeah, I would not suggest reversing it, but, for anyone interested, exploring different ways to go about it.

Indeed, it looks like it's best to fix it on the GTK application side though, should the application want to stick around (pun may or may not have been intended).

I do hope the commit and issue I mentioned will at least give some background information on why this started happening here, if it was unclear to anyone still, and if indeed this issue too started with it.

**Comment by ekpyron** [comment]
Interestingly, in the example code posted above, changing ``g_idle_add((GSourceFunc) chkStatusIcon, NULL);`` to ``g_timeout_add(1000, (GSourceFunc) chkStatusIcon, NULL);`` will have ``gtk_status_icon_is_embedded`` return ``TRUE`` on lxqt.
So my guess is that lxqt-panel's implementation of the XEmbed protocol is different than in other system trays in some way, causing the actual embedding to happen a bit later than usual...

**Comment by ekpyron** [comment]
Hahaha, this is the reason: ``lxqt-panel/plugin-tray/trayicon.cpp``:
```
    // NOTE:
    // see https://github.com/lxqt/lxqt/issues/945
    // workaround: delayed init because of weird behaviour of some icons/windows (claws-mail)
    // (upon starting the app the window for receiving clicks wasn't correctly sized
    //  no matter what we've done)
    QTimer::singleShot(200, [this] { init(); update(); });
```

Replacing this by just ``init(); update();`` fixes the problem...

**Comment by ekpyron** [comment]
And actually I can't reproduce the https://github.com/lxqt/lxqt/issues/945 which caused this workaround to end up there in the first place... I'll create a PR to remove this workaround, then you can discuss if you want to take the risk of reintroducing https://github.com/lxqt/lxqt/issues/945 (which to me no longer seems to be happening even without the workaround).
