### ISSUE TITLE
lxqt-powermanagement error

### ISSUE THREAD

**Issue by hektr** [lxqt/lxqt#1841]
lxqt-powermanagement: Power Manager Error (D-BUSS call)
There is already a shutdown or sleep operation in progress

I use debian buster with lxqt 0.14.1
Error occures when I open my notebook. 
Lid Watcher is enabled. 
Action when lid is closed -- suspend.

**Comment by tsujan** [comment]
LXQt 0.14.1 is obsolete and not supported anymore.

**Comment by stefonarch** [comment]
On my old laptop is running the same version, and I don't see this issue.
Maybe it depends on some double setting setup, check /etc/systemd/logind.conf

**Comment by tsujan** [comment]
> On my old laptop is running the same version, and I don't see this issue.

We all had LXQt 0.14 before and none of us encountered this issue ;)

My point was that searching for the cause is impossible when the installed LXQt is old.

Anyway, I'm almost sure that this isn't an LXQt issue. It can have many causes but @stefonarch is right: probably, something is wrong with systemd.

**Comment by hektr** [comment]
it seems, error is gone when I've enabled policykit and reboot my note

вс, 30 авг. 2020 г., 12:38 tsujan <notifications@github.com>:
