### ISSUE TITLE
Global keyboard layout doesn't work

### ISSUE THREAD

**Issue by omeritzics** [lxqt/lxqt#1858]
#### Expected Behavior
The keyboard layout is global and the same in all of the windows.

##### Current Behavior
The keyboard layout always resets to the main layout when editing different text boxes or leaving them.

##### Steps to reproduce
1. Boot LXQt in a live CD (using VM isn't possible to reproduce the bug).
2. Configure the keyboard layouts (at least 2) as you want.
3. Run Fcitx daemon.

##### Context
This bug makes the typing annoying for who use non-latin writing systems (for example: Hebrew/English, Arabic/English, Russian/English).

##### System Information

* Distribution & Version: Lubuntu 20.10
* Kernel: 5.8.0-26-generic
* Qt Version: 5.14.2
* Package version: 0.15.0

**Comment by tsujan** [comment]
Thanks for the report.

I can't reproduce it. Actually, I used the global layout for years and it always worked fine — only recently, I changed it to the application based policy (which also works fine).

Like other reports that can't be reproduced, there should be a hidden factor. Waiting for you to find it...

**Comment by omeritzics** [comment]
> Thanks for the report.
> 
> I can't reproduce it. Actually, I used the global layout for years and it always worked fine — only recently, I changed it to the application based policy (which also works fine).
> 
> Like other reports that can't be reproduced, there should be a hidden factor. Waiting for you to find it...

The hidden factor is the Fcitx daemon, the global keyboard layout doesn't work when Fcitx daemon runs in the background only.

**Comment by tsujan** [comment]
> The hidden factor is the Fcitx daemon

My bad! You're right; I didn't pay attention to Fcitx in your report because, having seen [your other report](https://github.com/lxqt/lxqt/issues/1857), I thought you found a problem in LXQt's handling of keyboard layouts.

I think the problem should be either in Fcitx or about how it's set up (or isn't set up) because keyboard layout changes correctly without It. Sorry, I can't be of more help; have never used Fcitx.

@palinek, can this be our problem?

**Comment by palinek** [comment]
I remember vaguely this input method systems take precedence over the basic X settings ... So in case it is installed our kbindicator plugin is useless.

(if I'm not mistaken)

**Comment by omeritzics** [comment]
> I remember vaguely this input method systems take precedence over the basic X settings ... So in case it is installed our kbindicator plugin is useless.
> 
> (if I'm not mistaken)

As I know, kbindicator is used to display the keyboard state in the panel, and Fcitx doesn't display it.

**Comment by palinek** [comment]
> As I know, kbindicator is used to display the keyboard state in the panel, and Fcitx doesn't display it.

...but Fcitx takes the control over switching the layouts. So configuration in kbindicator is not used in that case.

**Comment by omeritzics** [comment]
> > As I know, kbindicator is used to display the keyboard state in the panel, and Fcitx doesn't display it.
> 
> ...but Fcitx takes the control over switching the layouts. So configuration in kbindicator is not used in that case.

So, can removing one of them solve this issue without problems?

**Comment by tsujan** [comment]
@omeritzics 
If you want to change your keyboard layout globally, for each window or for each app under LXQt, you won't need Fcitx; LXQt handles keyboard layouts through Panel's Keyboard Status Indicator (like most other DEs).

As @palinek mentioned (and I read a little about Fcitx today), Fcitx can't be compatible with lxqt-panel's plugin-kbindicator. The problem you see is caused by that and doesn't belong to LXQt.

**Comment by omeritzics** [comment]
> @omeritzics
> If you want to change your keyboard layout globally, for each window or for each app under LXQt, you won't need Fcitx; LXQt handles keyboard layouts through Panel's Keyboard Status Indicator (like most other DEs).
> 
> As @palinek mentioned (and I read a little about Fcitx today), Fcitx can't be compatible with lxqt-panel's plugin-kbindicator. The problem you see is caused by that and doesn't belong to LXQt.

I opened a bug in their repository. Please consider using a different daemon for input methods.
