### ISSUE TITLE
terminal apps won't open (lxqt-config/libqtxdg)

### ISSUE THREAD

**Issue by slidinghotdog** [lxqt/lxqt#1889]
I recently reinstalled my system and since lxqt-config doesnt set $TERM anymore and i don't have xterm installed, trying to open terminal programs from menu (fails silently) or from desktop (shows error dialog about xterm not found) does not work.

##### Expected Behavior
app opens

##### Current Behavior
doesn't open

##### Possible Solution
- add default terminal selection to lxqt-config, setting $TERM
- set $TERM=qterminal since it's probably installed alongside lxqt
- i saw [this discussion](https://github.com/lxqt/lxqt/issues/433) so maybe both lxqt-config and libqtxdg should use another variable name?
- provide some way for plugin-mainmenu ~~and pcmanfm-qt~~ to set terminal command

##### Steps to Reproduce (for bugs)

1. install some minimal distro like arch, without xterm (or remove xterm from $PATH and unset $TERM)
2. install latest lxqt and some terminal app like htop
3. try to open terminal app from mainmenu or desktop

##### Context
doesn't bother me much since i know i can just set $TERM, but there should be some way to config it from lxqt-config on default applications, and/or use qterminal by default

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.9.14-arch1-1 
* Qt Version: 5.15.2-1
* liblxqt Version: 0.16.0-1
* Package version: libqtxdg 3.6.0-2 / lxqt-config 0.16.1-1

**Comment by tsujan** [comment]
Confirming: Htop can't be opened from the main menu when xterm isn't installed and `TERM` isn't set. I don't have a minimal distro but didn't encounter any problem with uninstalling xterm and removing `TERM` from an LXQt session.  

However, since `TERM` is included in `LXQt Session Settings → Environment (Advanced)` and can be easily set/changed, I don't think there's a problem.

@luis-pereira, what do you think?

**Comment by slidinghotdog** [comment]
@tsujan i just set $TERM and it doesn't open from desktop, it looks like pcmanfm-qt doesnt use libqtxdg nor $TERM?

**Comment by slidinghotdog** [comment]
> However, since `TERM` is included in `LXQt Session Settings → Environment (Advanced)` and can be easily set/changed, I don't think there's a problem.

this isn't set by default, so on a fresh install if u don't have xterm nothing happens when u try to open some terminal app, not sure if DE's or if it is common to set TERM but i don't think it's easy to figure out that u need to set it.

**Comment by tsujan** [comment]
> i just set $TERM and it doesn't open from desktop

That's because you haven't set pcmanfm-qt → Preference → Advanced → Terminal emulator (correctly).

> it looks like pcmanfm-qt doesnt use libqtxdg nor $TERM?

pcmanfm-qt (actually, libfm-qt) uses the terminal you set in the above-mentioned section. It has nothing to do with `TERM`.

> this isn't set by default

I said `TERM` exists in `LXQt Session Settings`; didn't say it's set.

We had a long and old discussion about "default terminal" and concluded that it didn't make much sense. Whether your report is a counterexample or not, I still don't know. And, since this seems to be the only use case for `TERM`, I don't think there's a problem to fix. Waiting for other LXQt devs to share their thoughts...

**Comment by slidinghotdog** [comment]
> That's because you haven't set pcmanfm-qt → Preference → Advanced → Terminal emulator (correctly).

> pcmanfm-qt (actually, libfm-qt) uses the terminal you set in the above-mentioned section. It has nothing to do with `TERM`.

yeah, i found this a little later, i wrongly assumed it would work for both.

> I said `TERM` exists in `LXQt Session Settings`; didn't say it's set.

it doesn't exist there, u have to know that the variable name is TERM and set it yourself, i think lxqt-config used to set it when it had a default terminal selection, this would possibly be a problem for when you're switching DE and installing by default from repos, unless the packager for the distro adds it.
from a fresh install:
![2020-12-14_01-45](https://user-images.githubusercontent.com/33790211/102041473-55eaff00-3dae-11eb-80a3-a732aa1fbe5d.png)

**Comment by tsujan** [comment]
You're right; my mistake. I thought it was in `/usr/share/lxqt/session.conf`; don't remember whether it existed and was removed recently or not. However, read below to see why it isn't important.

As for libqtxdg, the code is https://github.com/lxqt/libqtxdg/blob/ce27256400598fc9769710c293d4db27b9a8f932/src/qtxdg/xdgdesktopfile.cpp#L459:

```c++
    if (q->value(QLatin1String("Terminal")).toBool())
    {
        QString term = QString::fromLocal8Bit(qgetenv("TERM"));
        if (term.isEmpty())
            term = QLatin1String("xterm");

        args.prepend(QLatin1String("-e"));
        args.prepend(term);
    }
```

Because of this, IMO, `xterm` should be an optional dependency (or a "recommend" is Debian systems) of `libqtxdg`. `TERM` isn't needed. Problem solved! Again, this isn't something that can be fixed upstream.

@yan12125, is `xterm` an optional dependency for any LXQt package in Arch, directly or indirectly?

**Comment by tsujan** [comment]
For now, these solutions have occurred to me:

 1. Add the default terminal option to LXQt Session Settings again. I don't like it and think that others don't either.
 2. Add `TERM` to `/usr/share/lxqt/session.conf`. But the user may not know why it is there.
 3. Make xterm an optional dependency. This should be done by distros.
 4. Personally, I like this solution: Instead of using `TERM` and `xterm` so quickly in `libqtxdg`, first check `System/Terminal` in `~/.config/pcmanfm-qt/lxqt/settings.conf`. The order is `pcmanfm-qt's user config file` → `TERM` → `xterm`. In this way, we won't have a double handling of terminal emulators.

**Comment by tsujan** [comment]
And a cleaner version of solution No.4:

 5. Make pcmanfm-qt set/read its default terminal in a file inside `~/.config/lxqt/` (like `lxqt.conf` or `session.conf`) and make `libqtxdg` first check the same file in the above-mentioned code block.

**Comment by slidinghotdog** [comment]
> Add TERM to /usr/share/lxqt/session.conf. But the user may not know why it is there.

this is enough and IMO the main issue is the default one should be `qterminal` since it is part of lxqt, so if u just install the `lxqt` group/metapackage (arch/debian) it already works, i also think the default should be set by `lxqt` since `pcmanfm-qt` and `libqtxdg` are used in a lot of different DEs and WMs, and combining your 5th option so they get the `lxqt` default would be nice too.

i don't like adding `xterm` an optional dep or recommended, i know it is a common default on wms that have hardcoded menu or for keyboard shortcuts, but i think it is unnecessary if this is the only reason, since `qterminal` is already included.

**Comment by yan12125** [comment]
> is xterm an optional dependency for any LXQt package in Arch, directly or indirectly?

Neither. Are we sticking to xterm? I imagine the default should be changed sooner

**Comment by yan12125** [comment]
Sorry fat finger :(

**Comment by tsujan** [comment]
@yan12125 
Sooner or later, we should get rid of both xterm and `TERM` and have a unified way of handling terminals. I think that could be achieved by something like https://github.com/lxqt/lxqt/issues/1889#issuecomment-744183086 because libfm-qt's terminal handling is independent of xterm and `TERM`.

**Comment by yan12125** [comment]
A common place sounds a good idea!

**Comment by luis-pereira** [comment]
Wasn't aware of this.
I was under the impression that xterm was a runtime requirement.  I wrote the CMake find module and my hard drive broke before publishing it.
Yes, reading the `TERM ` environment variable  should not be done. It should have been removed wen `TERM` was removed from `lxqt-config-session`.
Will add an FindXTerm CMake module and update that piece of code.

The most sensible place to put a Default Terminal would be in the LXQt Default Applications. With the backend done in the `qtxdg-mat def-terminal`. QtXdg does not depend on LXQt (neither PCManfm-qt) so it should not depend on LXQt configurations.

The environment variable TERM contains a identifier for the text window’s capabilities, not the terminal executable name.

**Comment by tsujan** [comment]
> The most sensible place to put a Default Terminal would be in the LXQt Default Applications.

Sadly, it's inside "File Associations", although it isn't about any file.

**Comment by luis-pereira** [comment]
> Sadly, it's inside "File Associations", although it isn't about any file.

Yes, that's unfortunate. We  could make LXQt Default Applications an independent application.

**Comment by tsujan** [comment]
> We could make LXQt Default Applications an independent application.

No, we could just make a few changes :) "File Associations" can be changed to "Default Applications" and the "Default Applications" tab could become the first tab with the name "Applications"; the second tab being "Associations". The reason: file association is actually about setting default applications.
