### ISSUE TITLE
Better Color Consistency for LXQt Themes

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt#1904]
A good number of modern desktop environments only support two system themes ("light" and "dark"). While LXQt's theme concept is more powerful it doesn't really make use of its potential. The system color palette is managed separately from each theme - and modifying system colors manually can be quite "fiddly".

However if each theme would provide its own color palette (either by file or API) we could overcome this and make LXQt colors shine - or rather *not* as the following screenshot shows:rofl:.

![theme-dark-sample](https://user-images.githubusercontent.com/440517/104104637-abc99e80-52a9-11eb-952a-36df1221e750.png)

As #145 is from an past era where stylesheets were the name of the game in Qt (LXQt integrates QStyle instead) here comes the up-to-date feature request.

##### Expected Behavior
Colors follow the LXQt theme consistently throughout GUI applications. 

##### Current Behavior
Application colors do not change with the theme (despite some very subtle LXQt applications like e.g. "panel" and "runner").

##### Possible Solution
Configure system colors when changing the LXQt theme. Needs implementation.

##### Steps to Reproduce (for bugs)
Select an LXQt theme different from the current via `lxqt-config-appearance -> LXQt Theme`.

##### Context
Overall appearance of LXQt.

##### System Information
* Distribution & Version: Any Desktop Linux with LXQt (screenshot above taken with Manjaro 20.2)
* Kernel: 5.4
* Qt Version: 5.15.2
* liblxqt Version: 0.16
* Package version: 0.16

**Comment by tsujan** [comment]
This is a valid feature request. Its implementation requires four things, at least:

 1. Defining a format and an extension for "LXQt palette files" (like KDE color schemes but much simpler);
 2. Adding "LXQt palette files" (in contrast to stylesheet colors) to each and every LXQt theme;
 3. Adding an option to load those palettes when the active LXQt theme is changed (it should be disabled by default); and most importantly,
 4. Adding code to lxqt-appearance for loading and applying "palette files".

Also, the user should be informed that "palette files" don't apply to all styles; they're especially for Fusion and, to a great extent (but not completely), for Breeze/Oxygen,

All this is possible but needs a considerable amount of time and motivation.

As for me:
I added simple palette colors to LXQt as a way of colorizing Fusion and Breeze styles, which are used by most LXQt users. I have no incentive to do more because I use Kvantum, which is independent of LXQt's palette. However, I can review patches.

**Comment by antis81** [comment]
I'd prefer an LXQt API call (see `lxqtsettings.h`) by slightly extending `LXQt::LXQtTheme` class by a `palette()` method. Here's a modfied code snippet from lxqt-config-appearance -> styleconfig.cpp:

```c++
StyleConfig::StyleConfig(/* …constructor init… */) {
    …
    connect(ui->defaultPaletteBtn, &QAbstractButton::clicked, [this] {
        // NOTE: Every theme provides a valid color palette!
        //            Anyway the window color could be used there as a default
        //QColor winColor(239, 239, 239);
        //QPalette defaultPalette(winColor);

        // now simply get the theme's default palette
        QPalette defaultPalette = LXQt::LXQtTheme::currentTheme().palette(); // <--- DOES NOT EXIST YET!

        ui->winColorLabel->setColor(defaultPalette.color(QPalette::Window), true);
        ui->baseColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::Base), true);
        // Qt's default highlight color may be different from that of Fusion
        ui->highlightColorLabel->setColor(QColor(60, 140, 230), true); // <---- THIS NEEDS TO MOVE TO THEME PALETTE
        ui->windowTextColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::WindowText), true);
        ui->viewTextColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::Text), true);
        ui->highlightedTextColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::HighlightedText), true);
        ui->linkColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::Link), true);
        ui->linkVisitedColorLabel->setColor(defaultPalette.color(QPalette::Active,QPalette::LinkVisited), true);
    });
}
```

The default palette *always* matches an LXQt theme *and* remains customisable. Usually it will "just work" though and no modifcation is needed by user. The main work is in finding a handful of "well defined" color presets for the existing LXQt themes - essentially burns down to "light" and "dark".

Btw. Ironically the Kvantum theme does not work for me and shows "black text on black background" in runner dialog! (w/o Kvantum installed).

**Comment by antis81** [comment]
@tsujan I deleted my previous comment as it was based on the false assumption, that a theme was an actual class inheriting `LXQt::LXQtTheme`. As LXQt's theme concept builds purely on files this doesn't work this way. So `LXQt::LXQtThemeData` is our friend here, which needs to be initiated with a color palette on instantiation.

As you stated earlier this requires defining a file format first.

So I'm gonna sort things out for us:

Point 1:
To keep things simple I suggest a `palette.conf` in INI format (basically a copy of the `lxqt.conf -> [Palette]` section). I am going to prepare a PR in `lxqt-theme` where we can discuss in further detail.

Point 2 is trivial/implied -> over to `3`:
This is part of `liblxqt` where the `LXQtTheme` object is created based on the provided file structure. For this reason we could rethink LXQt themes and join the (text) files in a central definition file (`theme.json` or `theme.conf`). However INI files will do a good job in the first place.

Point 4:
bsolete in most parts, because the QPalette is set already by the theme (just like the qss stylesheets are) at this point. The constants in `defaultPalette()` need to be (re)moved though to not mess up color configuration.

Did I miss anything? :thinking:

**Comment by tsujan** [comment]
> I deleted my previous comment as it was based on

No need to delete your comments; we usually don't delete our incorrect comments in LXQt.

> Did I miss anything?

We may see things differently, which is OK. But there's no need to touch anything other than `lxqt-config` and `lxqt-themes`.

In my plan, 1, 2 and 3 are trivial (by 3, I just meant a simple checkbox that says something like, "Also, apply the Qt palettes of themes."); 4 is time-consuming and very boring ;)

`palette.conf` is a good but, IMHO, something like `lxqt-palette.conf` is better.

Anyway, you might like to do it a different way but please write your main code (for applying theme palettes) only in `lxqt-config`!

**Comment by RivenSkaye** [comment]
Any updates on this? I've been fiddling around with themes and started porting a couple Ubuntu-only themes for shits and giggles and would like automatic palette changes to be possible. Especially considering that Ubuntu (as per my use-case example) doesn't offer this properly either causing the install instructions there to include an entire section on getting all colors everywhere to match the style.

As for the palette, how and where is this currently saved? If this is already some config file or a serialized format listing the option and value pairs, couldn't themes supply their own while keeping a changed version with a -user suffix and the default with a -default suffix? I assume at least some standard is already in use considering the "Default Palette" button and the fact changes persist across sessions. 

On a related sidenote, I've noticed changing the current LXQt theme can cause the DE to become very slow for a while, not responding to user input at times, when there's windows open that use their own styling for everything that isn't window decoration (e.g. Discord, Telegram, Spotify). At some point LXQt seems to give up though, making everything run smooth again.

**Comment by tsujan** [comment]
Using Ubuntu, you probably have an old version of LXQt. Whole palettes can be saved and loaded now. Their place is in the sub-folder `/lxqt/palettes/` inside `QStandardPaths::GenericDataLocation` (`~/.local/share`, `/usr/local/share`, `/usr/share` in Linux). As for their format, you could see it if you save a palette with LXQt 1.0.0.

So, each LXQt theme can have an accompanying palette file with the same name. However,

 * We didn't add any palette file to any LXQt theme inside the package `lxqt-themes`. Theme makers are free to add them to their themes though.
 * Applying an LXQt theme doesn't apply its palette, if any. The user is free to apply it (in the same dialog) or not. The reason is that, unlike KDE, LXQt doesn't (and won't) have a specific widget style of its own and some widget styles don't follow the palette.

**Comment by stefonarch** [comment]
Maybe we could think about a similar checkbox at the bottom as "Use wallpaper of the theme"
"Apply corresponding color palette (if available)"

**Comment by tsujan** [comment]
If I remember correctly, I proposed it, you didn't like it, and then I didn't like it either. The difference between wallpaper and color palette is that the user may not know where the wallpaper is but, if there's a palette alongside an LXQt theme, it'll be shown by the GUI ("Load Palette" button).

**Comment by stefonarch** [comment]
If I recall correctly didn't like some (like the "silver" that I made for testing having same colors), for some themes like dark or arch colors a corresponding palette can look good.

**Comment by tsujan** [comment]
Sooner or later, users will ask for it. I'll implement it as an option later, disabled by default. Then, lxqt-themes will need some additions. Of course, themes like Frost can't have a palette file.

**Comment by stefonarch** [comment]
Hm, not sure about frost ecc, you can make them half illegible with a some random (dark) palette.

**Comment by tsujan** [comment]
Frost is made to be dark with light palettes and light with dark ones; you can't make both dark or light.

We even won't need to add palette files to all LXQt themes, as not all of them have wallpapers.

**Comment by stefonarch** [comment]
I remember some parts in frost just unreadable with some palette colors., but could be wrong, maybe it was "light" or another one.

**Comment by tsujan** [comment]
Before starting to implement automatic applying of color palettes alongside an LXQt themes, I thought about the design and found that it's impossible in a self-consistent way with the current GUI. On the other hand, it is so unimportant that, IMO, making another GUI for it would be an overkill — I have no reason to do so.

Suppose that we add a check-box to the LXQt Theme section that says, "Also, apply the color palette that may come with the theme," and suppose that the user has checked it. Then he opens LXQt Appearance Configuration, changes the Qt palette and clicks Apply. What should happen?

If the changes to Qt palette are applied, that will contradict the above-mentioned check-box; if not, something will be obviously wrong.

Worse than that, suppose that the user changes LXQt theme and then changes the Qt palette and then clicks Apply…

The difference with KDE's System Settings is that the latter asks you whether you want to apply changes as soon as you want to leave the page, while LXQt Appearance Configuration applies all changes together.

**Comment by RivenSkaye** [comment]
I'm on Arch, hence why I need to port the theme to get things to display properly. If I were on Ubuntu, I'd have just popped over to Unity for an easy fix of the issue. Luckily that also means I'm on LXQt 1.0.0.

I like the option for a checkbox or a switch to turn a theme's palette on or off. In the meantime I've found that using Kvantum is also a great way to set window styles and most Qt-styled applications seem to respect these, making it work very well. So well, in fact, that the LXQt theme seems to only apply to the taskbar and main menu! So perhaps finding a way to integrate with the selected Kvantum theme (if at all possible) could work as an option too? openbox seems to accept Kvantum themes just fine too, so that could become a very consistent manner of styling in LXQt, with the option to allow specific overrides through its own theming options

**Comment by tsujan** [comment]
> So perhaps finding a way to integrate with the selected Kvantum theme (if at all possible) could work as an option too?

No, it isn't possible. Kvantum is DE-independent. Like other styles, it can be selected and activated in LXQt Configuration Center. A distro can make it the default style and choose its default theme.

Like in KDE, there are two kinds of themes: (1) LXQt theme, which is only for LXQt's Panel and Runner; and (2) Qt widget style, which is for all Qt apps.

Some Qt widget styles, like Fusion (the default widget style of Qt), accept palettes. LXQt 1.0.0 supports saving and restoring of palettes. Palettes can also be installed in the above-mentioned paths. That was added mainly for switching between light and dark palettes easily.

Some Qt widget styles, like Breeze and QtCurve, accept palettes partially. They have internal colors that aren't provided by Qt's palette.

Some Qt widget styles, like Kvantum and Qt's gtk2, don't accept palettes. They use their internal colors and methods for drawing widgets. Kvantum has its own configuration and Qt's gtk2 depends on the old GTK2 style.
