### ISSUE TITLE
lxqt-config-monitor segfaults on save

### ISSUE THREAD

**Issue by ElectricCoffee** [lxqt/lxqt#1909]
As the title suggests, the program simply crashes when I hit the save button in the GUI.
Nothing is saved, and thus nothing can be recovered and used as the default settings.

##### Expected Behavior

I expect it to save and not just segfault.

##### Current Behavior

Program lets me set my monitor settings as expected, but segfaults on save.

##### Steps to Reproduce (for bugs)

1. Open program, either via terminal or otherwise
2. Save settings
3. Window closes
4. (In terminal) it reads `Segmentation fault (core dumped)`                                            --->

##### System Information

* Distribution & Version: Lubuntu 20.10 x86_64
* Kernel: 5.8.0-41-generic
* Qt Version: ???
* liblxqt Version: ???
* Package version: ???
Can't find ways to print the qt, liblxqt and package versions

**Comment by tsujan** [comment]
Closing because no version info is provided. Crash on saving was an old issue, fixed a long time ago.

**Comment by ElectricCoffee** [comment]
That may very well be the case, but it doesn't help the fact that I have this issue on a brand new system install and nothing online seems to give me any info as to how to resolve it

**Comment by stefonarch** [comment]
> brand new system install

LXQt version in Lubuntu 20.10 is 0.15
Actual version is 0.16

**Comment by tsujan** [comment]
> but it doesn't help the fact that...  If something were to tell me how to provide this info....

Please ask Ubuntu questions from Ubuntu.

**Comment by ElectricCoffee** [comment]
> > brand new system install
> 
> LXQt version in Lubuntu 20.10 is 0.15
> Actual version is 0.16

And how do I then upgrade to the latest version?

**Comment by stefonarch** [comment]
There are 2 ways: [compiling ](https://github.com/lxqt/lxqt/wiki/Building-from-sour) or switching distro/version - arch based distros have by default latest versions of all software. Ubuntu 21.04 should have 0.16 too afaik.

**Comment by wxl** [comment]
@ElectricCoffee 

If you read the template when reporting the bug you would have seen:

```
<!--- BEFORE FILLING OUT THIS REPORT FORM:                                 --->
<!--- Dear users of stable and LTS (long term service) distributions:      --->
<!--- Please do NOT file bugs against old (dead) versions but use your     --->
<!--- distribution bugtracker instead. This is esp. true for Ubuntu LTS.   --->
```

In general, too, I will say that all Ubuntu bugs should be reported with Ubuntu. (P.S. I'm part of the Lubuntu Team)

Personally @tsujan I think we should change the stable/LTS reference to "non-rolling release" and should also add a little checkbox that asks the reporter to confirm they have tested against the latest available release version and perhaps another one to confirm they have tested against the latest master. 

Also, to be perfectly punctilious, "officially" 21.04 doesn't exist yet. Development releases only have codenames until they're actually released. Although, I knew what you meant ;)

Hirsute Hippo (don't blame me, I don't come up with this), which should become 21.04 assuming it's released as planned with no other weirdness, should have 0.16 in it. Currently it does not as we have some merges from Debian which didn't sync cleanly and we've got a point release of 20.04 we're trying to manage right now.

There are ways we have to even run off of Git master, but you might end up with breakage, too. And while compiling is an easy solution, the result doesn't update itself, so that may not be preferable to the average user.

**Comment by tsujan** [comment]
@wxl 
Sometimes, there are good reports by the users of non-rolling distros too. Following the template is enough for a report to be acceptable. Unfortunately, some users may think that we should have time for reading between lines.

Here, I'm not saying that Ubuntu users should always report everything to Ubuntu. The reporter told about his "brand new system" and wanted us to tell him "how to provide this info". That's a distro-specific question; it isn't related to LXQt or its bug tracker.

**Comment by tsujan** [comment]
@wlx
I wonder how Ubuntu doesn't have at least one good PPA for the latest git version of LXQt. Or if it does, why don't Ubuntu users know about it? Not being a rolling distro isn't a real obstacle.

**Comment by ElectricCoffee** [comment]
It may be true that this is an Ubuntu related issue, moreso than a LXQt issue, but when I, as someone with no experience with this project what so ever, installs a distribution and get a segmentation fault when I do something as basic as saving my settings, I expect there to be _some_ info about how to resolve it **somewhere**.

Naturally, since the issue occurred in software pertaining to the LXQt project, this is the first place I went to report the bug, not knowing it had already been solved or that it was a known problem in the build shipped with Lubuntu 20.10.

Furthermore, as a user of a distribution like Lubuntu, I expect some level of stability, and that a cruicial bug like that to have been fixed asap on the repo, as it essentially means I have to re-configure my multi-monitor setup every time I log into the computer.

You can't expect everyone to be super savvy with regards to knowing how to build the project from scratch or somehow acquiring a bleeding-edge version of said software without stuff like this being addressed in a FAQ or guide somewhere pointing new users in the right direction. It shouldn't be my responsibility as the end user to fix what shouldn't be broken in the first place.

**Comment by wxl** [comment]
@ElectricCoffee it's often true with non-rolling release distros that old software, even with bugs, stays that way just by the nature of the design. In Ubuntu there's certainly a very rigid process to fix bugs in distro versions that are already released. It's not as simple as you might think it is. It is *absolutely* true that if no bugs are reported, it's unlikely that anyone's going to fix anything.

That said, there are usually mechanisms in place in report bugs in Ubuntu that are extremely well documented. I'm sure you could have figured that out way easier than bothering to come here (hint: `ubuntu-bug`). That's not a request for you to fix the problem, but a request to report it so that it can be fixed.

**Comment by tsujan** [comment]
> You can't expect everyone to be super savvy

@ElectricCoffee, no user needs to be savvy to know the versions of programs installed on his/her system. It's OK if don't know how to get that info but you need to learn it (from Ubuntu doc) before reporting anything.
