### ISSUE TITLE
Window Manager Menu option missing

### ISSUE THREAD

**Issue by 0n0w1c** [lxqt/lxqt#2016]
There used to be an option to use the Window Manager Menu, this option no longer appears, at least on the version 0.17

Desktop preferences has an option in the Advanced Tab which used to allows the use of the Window Manager Menu.

We still used the openbox menu generation for the desktop menu.

Manjaro rolling
Qt5 5.15.2
linux-5.10.39-1
LXQt 0.17

Was the result of [#425](https://github.com/lxqt/pcmanfm-qt/issues/425) to remove the option? Is there a manual way to configure this option?

**Comment by tsujan** [comment]
The WM menu was removed a long time ago, alongside its X11 codes.

**Comment by imachine** [comment]
Can this be brought back to life? The openbox "quick" menu together w/ lxqt was a preferred way to work for me, make work much easier, now not able to set that up, could there be a quick fix, to make openbox "overlay" upon right click instead of pcmanfm-qt desktop menu? Upgraded from Ubuntu 20.04 to 22.04 and together w/ version 0.17 of lxqt this option no longer works... maybe somewhere in config manually?

**Comment by tsujan** [comment]
> Can this be brought back to life?

Absolutely not.

**Comment by tsujan** [comment]
Sorry, but the facts are that Openbox is dead, LXQt-0.17 is dead, and cluttering the current source by adding X11-specific codes to it isn't an option, especially now that it works under Wayland too. X11 will be supported indefinitely but not by adding X11 codes.

**Comment by imachine** [comment]
Ok, you're right.
