### ISSUE TITLE
Issue with pcmanfm

### ISSUE THREAD

**Issue by hektr** [lxqt/lxqt#2030]
In thumbnail mode, pics max size is 160x160. If I set bigger size, pics remain the same size, only whitespace around them is added. [Demonstration ](https://youtu.be/K5bVXsoHWrA)

**Comment by stefonarch** [comment]
I suppose that your thumbnails are not regenerated. In ~/.thumbnails/large I've 256x256 ones, as my setting is.

**Comment by hektr** [comment]
May be i installed some programs and it uses one of them to make thumbnails??

**Comment by stefonarch** [comment]
What are your max size (MB) settings for internal and external thumbnailer? 
External ones are in `/usr/share/thumbnailers`

**Comment by stefonarch** [comment]
EDIT: I see that `~/.thumbnails` isn't used anymore but `~/.cache/thumbnails`

**Comment by hektr** [comment]
It depends on aspect ratio. If difference between pics height and weigh is not too big, then everything works good.

**Comment by tsujan** [comment]
There's no bug. Those images should have exif thumbnails with the sizes you see. If there's an exif thumbnail, it'll be used by the thumbnailer (instead of making a thumbnail out of the whole image).

You can verify that in various ways. For example, you could extract the exif thumbnail by using `exiftool` (see `-ThumbnailImage` in its manual) and see that the thumbnail size is correct, or you could covert it to PNG and see that the thumbnail size of the PNG image is bigger.
