### ISSUE TITLE
Make configuration for HiDPI displays easier

### ISSUE THREAD

**Issue by falko** [lxqt/lxqt#2173]
##### Expected Behavior

LXQt should adjust scaling and font sizes automatically to HiDPI displays or at least make configuration easy, e.g. via LXQt Configuration Center.

##### Current Behavior

It took me several hours on Lubuntu 21.10 to read through GitHub issues, StackOverflow articles, and wiki pages from other distros and then try out several approaches until I ended up with a workable solution, which I contributed here: https://askubuntu.com/a/1385626/366575

Among the materials I studied, were the issues #916, #1814 and lxqt/lxqt-config#403, which rather accidentally had helpful hints but are not a structured documentation or tutorial on the topic.

##### Possible Solution

Provide graphical configuration for setting `QT_SCALE_FACTOR` and `GDK_DPI_SCALE` and/or detect DPI automatically and configure a reasonable scaling factor. Alternatively, 

##### Steps to Reproduce (for bugs)

1. Run LXQt on a HiDPI display.

##### Context

I'm using a Thinkpad P51 that features a 15-inch display with 4k resolution, which is impossible to use without scaling. Running the display in Full-HD resolution is a workaround but is blurry, hard on the eyes and obviously a waste of the money I invested into the display.

##### System Information

* Distribution & Version: Lubuntu 21.10
* Kernel: 5.13.0-22-generic
* Qt Version: 5.15.2
* liblxqt Version: 0.17.0
* Package version: 0.17.0-0ubuntu1

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt/discussions/2054#discussioncomment-1891254

**Comment by falko** [comment]
Digging further I found lxqt/lxqt-config#402

**Comment by tsujan** [comment]
> Digging further I found lxqt/lxqt-config#402

Good to have its link here. I leave both reports open until an option (or two options, for Qt and GTK) is added. LXQt 1.0.0 was released 2 months ago; hopefully LXQt 1.1.0 will have them.

**Comment by tsujan** [comment]
Is this enough (for now)?

![scale](https://user-images.githubusercontent.com/981076/148636131-07d74d63-0a45-47f7-bc0f-c3b60ae4db4e.png)

It sets `QT_SCALE_FACTOR` and `GDK_SCALE` to the same value, which is between 1.0 and 4.0. 

I put it in basic settings page of session conf dialog because it's a session setting and the user should to be told about logging out and in if he changes it.

**Comment by falko** [comment]
Yes. Intuitively, I would expect it in Monitor Settings because the scaling depends on the resolution. Having to log out for it is fine.

**Comment by tsujan** [comment]
> I would expect it in Monitor Settings...

As I mentioned in the [PR](https://github.com/lxqt/lxqt-session/pull/408)'s comment, we could talk about an ideal option later. A long time has passed but we still haven't agreed on it, while users need it in practice.

Personally, I think that if we put it in Monitor Settings, it should also be in Session Settings because it's about two EVs (which will reflected by the Environment page too) and also because it's a basic session setting (saved in `~/.config/lxqt/session.conf`).

Qt6 might give us other methods too but `QT_SCALE_FACTOR` works with it. Whether `GDK_SCALE` will work with future versions of GTK, I don't know; GNOME's behavior isn't predictable.

**Comment by heckert-gamedev** [comment]
Having to re-login for changing graphics settings is so Windows-95. Please don't go there ;)

**Comment by tsujan** [comment]
> Please don't go there

If you know of another method, please make a PR. We accept patches.

**Comment by tsujan** [comment]
For the record (a short explanation was added to the PR before):

Setting Qt and Gdk EVs is the simplest and safest way of scaling. It scales GUI + icons + font in Qt5/6 and GTK apps without requiring other changes.

Its main drawback is that it's global. Those who have 2 screens, of which only one is HiDPI, won't benefit from it. It neither scales the cursor. The cursor size should be changed independently. In fact, it isn't *screen* scaling but GUI scaling.

LXQt still needs a per-screen scaling but that doesn't contradict an option for global scaling, which is enough for most users.

As for logging out and in, KDE requires it without telling its users about it. When you scale the screen in KDE's systemsettings, fonts are scaled but icons and most GUI elements aren't — windows are ugly and inconsistent — until you log out and log in again.

GNOME really needs no comment because it only cares about itself; except for font, nothing is scaled in Qt apps under GNOME, although GTK apps are scaled correctly.

**Comment by aiyagari** [comment]
> It took me several hours on Lubuntu 21.10 to read through GitHub issues, StackOverflow articles, and wiki pages from other distros and then try out several approaches until I ended up with a workable solution, which I contributed here: https://askubuntu.com/a/1385626/366575
> 

Thank you for including the link.  The Jammy Jellyfish version still does not include this change, so I had to do it manually, as per your description.
