### ISSUE TITLE
"home" link on desktop does not work

### ISSUE THREAD

**Issue by MauroMombelli** [lxqt/lxqt#221]
Trying to open the "home" link on deskop i get a "operation not supported" message box, and then the deskop seems to crash (all icons disappear, blue screen, then it turns back BUT with tansaparent icon, but maybe this is because of my default theme cause this, see #220

**Comment by goodluckclever** [comment]
I opened the PCManFM File Manager and tried to click "Computer". But a "operation not supported" message box appeared... What was the matter?
![operationnotsupported](https://cloud.githubusercontent.com/assets/23009119/19625630/a699f18a-9958-11e6-869c-bde4c28254c8.png)

**Comment by Esclapion** [comment]
Works here...

![xiszqt9](https://cloud.githubusercontent.com/assets/3512979/19625944/9e33ae82-9926-11e6-9a38-12ea9b4eae71.png)

**Comment by stefonarch** [comment]
Probably some gvfs related stuff is not installed?

**Comment by goodluckclever** [comment]
I'm new to linux. I've just installed arch+lxqt.
@Esclapion Yes, 0.11. Isn't is the newest version? By the way, how did you change the language into French?
@stefonarch Firstly, I installed arch in VirtualBox according to "Installation guide (wiki)". And then, 
# pacman -S virtualbox-guest-utils lxqt sddm
What's the meaning of "gvfs"? Are there any other packages I should install?

**Comment by MauroMombelli** [comment]
If lxqt package is missing a dependency its a bug of the package. Still would be nice if the system would tell you a component is missing instead of a cryptic error that nobody know how to solve

**Comment by stefonarch** [comment]
Try out  `pacman` -S gvfs udisks  udisks2

**Comment by Esclapion** [comment]
@goodluckclever : i did nothing special for lxqt language, but my whole system is configured for french (LANG=fr_FR.UTF-8).
I use a manjaro, so an arch-based distribution where gvfs & co are installed by default.

**Comment by pmattern** [comment]
@MauroMombelli

Are you still seeing the issue you described in the initial posting and if so could you elaborate?
I've just tried to reproduce your findings by fiddling with various folders on the desktop to no avail.

@goodluckclever

> By the way, how did you change the language into French?

Aside from setting a system locale as proposed by @Esclapion the locale valid within LXQt sessions can be tweaked by GUI "LXQt Locale Configuration", binary `lxqt-config-locale`, which you may launch from the panel's main menu - Preferences - LXQt settings or the "Configuration Center", binary `lxqt-config`, at the same location.

> What's the meaning of "gvfs"?

Sorry, but to figure out stuff like this please file it into one of the well-known search engines. Bug trackers as well as actually forums aren't the right place for basic questions like this.

> Are there any other packages I should install?

Distributions in general and Arch Linux in particular tend to install as little dependencies as possible in order to let users decide what they deem necessary. Just have a look at package pcmanfm-qt:
```
$ pacman -Si pcmanfm-qt 
Repository      : community
Name            : pcmanfm-qt
Version         : 0.11.1-1
Description     : The LXQt file manager, Qt port of PCManFM
Architecture    : i686
URL             : http://lxqt.org
Licenses        : GPL2
Groups          : lxqt
Provides        : None
Depends On      : liblxqt  libfm-qt  lxmenu-data
Optional Deps   : gvfs: for trash support, mounting with udisks and remote filesystems
                  udisks: alternative for mounting volumes
                  xarchiver: archive management
Conflicts With  : None
Replaces        : None
Download Size   : 198.89 KiB
Installed Size  : 917.00 KiB
Packager        : Jerome Leclanche <jerome@leclan.ch>
Build Date      : Sat 24 Sep 2016 05:51:06 PM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
Note that a lot of dependencies are handled as optional. As a beginner you may just install them, reboot and you should be good to go.
