### ISSUE TITLE
size of the cursor will not be remebered after rebooting the computer

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt#2391]
Steps to reproduce
1 main-menu, preferences, ..., appearance
2 select `Cursor`
3 select `Breeze`
4 Change `Size` from 22 to 40
5 Click `Apply`
6 restart the computer

Result
The cursor has the size of 22. In `Size` there is 22.

Expectation
The cursor should have the size of 40. In `Size` there should be 40.

Lubuntu 22.10
LXQt 1.1.0

**Comment by tsujan** [comment]
Not reproducible.

**Comment by ralf3u** [comment]
I just recognized that I don't even need to restart the computer. If I let appear again the Appearance, then the size is again 34 and not 40 as it should be.

**Comment by Butterfly** [comment]
> > also in Lubuntu 23.04
> 
> Report it to Lubuntu, telling them that it doesn't happen upstream.

Hi! I had already reproduced this prior to this thread, but I'm having some serious memory issues right now. I think I figured out that it *might* be about the cursors we choose and how their developers set them up. If you can hold off for a little while to give me a chance to figure out what I had tracked down, I'll try to figure out what happened here on Debian Bookworm.

In the meantime, I think I remember getting ready to ask if the cursor you're using offers a choice of something like small, regular, and large when you go to `Preferences > LXQt Settings > Keyboard and Mouse`. Mine does. It's `Chameleon-Purple-Regular`.

Those multiple size options seem to be the clog. And it just occurred to me this second that it could somehow still be the case with certain other cursors that only have one line to click. They may still be hardwired in a dot conf file somewhere. Those apparently override our personal *CHOICE* or needs to have e.g. larger medium sized cursors that aren't quite as big as the default "large" size.

See you all in a little bit. :smile:

**Comment by tsujan** [comment]
> I think I remember getting ready to ask if the cursor you're using offers a choice of something like small, regular, and large

I tested with what @ralf3u mentioned in its report, namely, Breeze and Breeze Light.

Also, see https://github.com/lxqt/lxqt/issues/2397#issuecomment-1480966514, although I don't think it's related to this because @ralf3u told that, in his case, the dialog showed 34 after reopening (which isn't reproducible here).

**Comment by ralf3u** [comment]
@tsujan

Are you using a non-SDDM based setup?

I ask this because according to this comment (https://discourse.lubuntu.me/t/bug-in-lubuntu-23-04-customized-size-of-the-cursor-is-not-remembered/4184/2) the issue could be caused by SDDM.

**Comment by tsujan** [comment]
I use SDDM.

**Comment by tsujan** [comment]
> I ask this because according to this comment (https://discourse.lubuntu.me/t/bug-in-lubuntu-23-04-customized-size-of-the-cursor-is-not-remembered/4184/2) the issue could be caused by SDDM.

It may be specific to Ubuntu. Here, when I set the cursor size to a big value like 40, it remains 40 inside the LXQt session. When I log out, the cursor size becomes 22 in SDDM, which isn't a surprise because I'm outside the session. After logging into LXQt, the cursor size becomes 40 again, as expected.

**Comment by humpity** [comment]
> I use SDDM.

Are you using Manjaro ? because I think I know why it works there too.

**Comment by tsujan** [comment]
Yes. Why?

**Comment by humpity** [comment]
The SDDM startup scripts look for directories and files that
may contain X resource files. 
I tried out a Manjaro ISO and installed sddm+lxqt.

SDDM default SessionCommand is /usr/share/sddm/scripts/Xsession.

	/etc/X11/ had neither Xresources nor Xresources/
	$HOME/ had no .Xresources
so xrdb is never called.
RESOURCE_MANAGER property is NOT created.
So I think lxqt-config picks up .Xdefaults instead.
Cursor size is correct.

For debian based distros,
SDDM default SessionCommand is /etc/sddm/Xsession.
Again, the scripts hunt for Xresources but in Lubuntu it
does find one file; /etc/X11/Xresources/x11-common.
xrdb is called to merge it.
RESOURCE_MANAGER property is created.
lxqt-config picks up cursor size from RESOURCE_MANAGER
(which doesn't have Xcursor.size).
Cursor size is wrong.

So SDDM is focused on Xresources while LXQt is updating Xdefaults.

A workaround is to symlink ~.Xdefaults to ~/.Xresources. This way
LXQt updates ~/.Xresources. (btw: the update is crude, it appends
lines instead of changing existing values).

Why isn't LXQt reading the cursor size from ~/.config/lxqt/session.conf ?

**Comment by tsujan** [comment]
@humpity 
I opened https://github.com/lxqt/lxqt-config/issues/937. Thanks!

**Comment by tsujan** [comment]
OK, the function `fixXDefaults` in `cfgfile.cpp` belonging to lxqt-config should be changed (also, its name), so that it writes to `~/.Xresources` in addition to `~/.Xdefaults`.

Even in its current form, that function isn't good because it clutters the file by adding new settings without removing the old ones.

We might need a point release for lxqt-config too.
