### ISSUE TITLE
size of the cursor is not be remembered after resume

### ISSUE THREAD

**Issue by Dan-Essin** [lxqt/lxqt#2397]
This is Debian 11. All available updates have been applied

I used the LXQt Appearance Configuration to set the icon size to 25. 
It changed.
After resume, it reverted to 30.

the file session.conf shows cursor_size=25
The gui shows 30

##### Expected Behavior
Using LXQt Appearance Configuration to set the icon size to 25 - the setting should persist.

##### Current Behavior

I used the LXQt Appearance Configuration to set the icon size to 25. 
It changed.
After resume, it reverted to 30.

the file session.conf shows cursor_size=25
The gui shows 30

##### Steps to Reproduce (for bugs)

1.  Use the gui and sett a new value
2. Cursor changes size
3. logout
4. login
5. Cursor returns to default size session.conf shows the size selected in the gui (e.g. 20) but the screen shows a cursor of size 30
6. 
7. 
8. 

##### Context

Problems like this make me wonder if it is worth the time to adopt and learn something that does not behave predictably.

##### System Information

* Distribution & Version: Debian 11
* Kernel:  5.10.162-1
* Qt Version:  If you had mentioned how to find it, I would have included it
* liblxqt Version: ditto
* Package version: ditto

**Comment by tsujan** [comment]
As the [documentation](https://linux.die.net/man/3/xcursorsetdefaultsize) of `xcursorsetdefaultsize` says,  "Each cursor image is tagged with a nominal size so that the best size can be selected automatically."

The final result depends on the cursor theme. Usually, 24 to 30 are treated as 24, while a value of 31 may make the cursor bigger by one step. You could see the real cursor size by putting the mouse cursor over the preview section of LXQt Appearance Configuration → Cursor.

> ... if it is worth the time to adopt and learn something that does not behave predictably.

That's up to you.
