### ISSUE TITLE
Can't start session with startlxqt

### ISSUE THREAD

**Issue by AlfredoRamos** [lxqt/lxqt#408]
Hi there,

I just upgraded my system (Arch Linux) with Qt 5.4.0 and now i can't start session.

When i try to run `startlxqt` i get:

```
QXcbConnection: Could not connect to display (Aborted (core dumped))
```

I have [lxqt-desktop-git](https://aur.archlinux.org/packages/lxqt-desktop-git/) and [qt5](https://www.archlinux.org/groups/x86_64/qt5/) installed.

Some info:

```
$ inxi -CGMzc 0
Machine:   System: Hewlett-Packard product: HP Pavilion dv6 Notebook PC v: 058A110000242B10010020100
           Mobo: Hewlett-Packard model: 1448 v: 65.38 Bios: Hewlett-Packard v: F.29 date: 11/07/2011
CPU:       Quad core Intel Core i7 Q 720 (-HT-MCP-) cache: 6144 KB 
           clock speeds: max: 1600 MHz 1: 1066 MHz 2: 933 MHz 3: 933 MHz 4: 933 MHz 5: 1600 MHz 6: 933 MHz
           7: 933 MHz 8: 1199 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]
           Display Server: X.Org 1.16.2.901 driver: fglrx Resolution: 1366x768@60.03hz
           GLX Renderer: AMD Mobility Radeon HD 5000 Series GLX Version: 4.4.13283 - CPC 14.201.1006.1002
```

**Comment by tjgillies** [comment]
I'm having similar error when trying to run pcmanfm-qt from cron

**Comment by pmattern** [comment]
@tjgillies 
In order to try and reproduce issues we always need more detailed information like OS as well as version of LXQt and the way it was installed.
In this particular case it would be good to get the corresponding line of your `crontab`, too. At first glance I fail to understand what's the purpose of launching a file manager as a cron job, tbh.
