### ISSUE TITLE
Feature request: allow using a separate icon theme for lxqt panel/menu

### ISSUE THREAD

**Issue by hagabaka** [lxqt/lxqt#470]
lxqt's panel, application menu, and applets follow a common theme which sets their background color, among other things. The lxqt theme is configured separately from Qt application styles, so it's possible for lxqt's panel and menu etc to have dark backgrounds, and for regular Qt applications to have bright backgrounds, at the same time. In fact this is the default with the "frost" lxqt theme and "Breeze" or "Oxygen" Qt style. An icon theme that looks good over a dark background doesn't necessarily look good on a bright background, so I think it's appropriate to have a separate setting for the icon theme used in lxqt panel etc.

To demonstrate the problem, below are two screenshot showing PCManFM-Qt and part of the panel, using different icon themes.

![screenshot with Breeze](http://i.imgur.com/dtH3kQh.png)
Using the Breeze icon theme, icons in PCManFM-Qt are clearly visible, but the sound mixer in the bottom right is very dim. 

![screenshot with Breeze Dark](http://i.imgur.com/sd0VOvJ.png)
Using the Breeze Dark icon theme, the sound mixer icon in the panel has nice contrast, but most of the icons in PCManFM-Qt are barely visible except when highlighted with blue background.

**Comment by intialonso** [comment]
I dont know, this is true for Breeze (which is incomplete right now) but there is more icon themes with this problem? Most themes include dark panel variants (Ubuntu, Numix, Elementary XFCE, Faenza).

One option could be to hard code the icons to the lxqt theme, like plasma themes do. But Im not sure.

**Comment by hagabaka** [comment]
When you say those themes include dark panel variants, do you mean they assume panels are dark, or they actually have versions of icons for bright panels and for dark panels? How does the right one get selected?

**Comment by jleclanche** [comment]
I'm +1 on this as long as it's discrete.

**Comment by hagabaka** [comment]
@jleclanche could you clarify what you mean by discrete?

What do you think about this outline of a possible solution?

1. An LXQt theme can optional define an "icon theme replacement" setting. A value of `theme1a:theme1b,theme2a,theme2b` means to use theme1b for panel when theme1a is selected as the Qt icon theme, and theme2b for panel when theme2a is selected as the Qt icon theme.
2. Dark LXQt themes should define the above setting as `"Breeze:Breeze Dark"`, or `"Breeze:Breeze Dark,Some Theme Light:Some Theme Dark"` if similar light-dark pairs of icon themes exist.
3. A new method `XdgIcon::fromThemeForPanel` honors the above setting. It would probably need to temporarily set `QIcon::themeName`, and restore it after fetching the icon.
4. Panel applets need to make sure to use `XdgIcon::fromThemeForPanel` for icons over themed backgrounds, but continue to use `XdgIcon::fromTheme` for configuration dialogs etc which use regular Qt backgrounds.

A flaw with this is that it's also possible to set the background color from Configure Panel, and then the icon theme replacement may not make sense if the user changes a dark theme to use a bright background. However I don't think this would be very common, and this background color setting doesn't seem to apply to menus either.

**Comment by jleclanche** [comment]
That's the opposite of discrete, that's extremely invasive.

An option in lxqt-panel config to choose to override *all* icons would be the only solution I'd be ok with, personally.

**Comment by hagabaka** [comment]
My suggestion *was* to override icons in menu, systray and plugins, except for configuration dialogs which use plain Qt styles.

Let's break possible solutions into decisions:

1. How does the panel decide which alternative icon theme to use?
    1. Use the global icon theme (current behavior)
    2. Use an icon theme hardcoded into the LxQt theme
    3. Use an icon theme hardcoded into the panel
    4. Use an icon theme only for panels chosen by the user: my initial suggestion, but since the purpose of using this alternative icon theme is to ensure visibility of icons over the LxQt theme backgrounds, I think it would be more appropriate to let the LxQt theme influence this setting
    5. Use an icon theme based on global icon theme and LxQt theme configuration (my preference)
2. How should the alternative theme be applied?
    1. Set it globally for lxqt-panel:
        requires fewer lines of changed code to implement, but while solving the problem for themed parts of the panel, it creates the same problem for configuration dialogs
    2. Set it only for themed parts:
        requires changing individual plugin code to implement, but ensures icons in both themed parts and regular Qt UI are usable (my preference)

**Comment by hagabaka** [comment]
Either way, I suppose it's best to start from the basics. hagabaka/lxqt-panel@c7fc81b allows using a separate icon theme for the entire lxqt-panel application.

It can only be set by editing the configuration file for now. It could be added to the Configure Panel dialog, but I think if it has to be user-configurable, I would prefer for it to be set in the LXQt Theme section of lxqt-config-appearance instead, since changing the LXQt theme is likely to require changing the panel theme too.

I will try to find a clean way to make config dialogs still use the system icon theme.

**Comment by paulolieuthier** [comment]
I agree with @jleclanche. And the option really has to be on lxqt-panel's config dialog as lxqt-panel is supposed to be independent.

**Comment by hagabaka** [comment]
@paulolieuthier The panel is independent, but it already uses LXQt theme settings which are defined in the lxqt-common repository, and configured in lxqt-config-appearance.

**Comment by paulolieuthier** [comment]
You're right.

**Comment by agaida** [comment]
@all - two and a half year later we still have no solution - so i guess we should implement it as soon as possible. We have exactly two choices right now:
a) Quick and Dirty
implement this for the panel and the runner
b) Right
implement this in config appearance with variable applications

i would suggest right now a) Quick and dirty and do it right later - distributions like Lubuntu desperatly need it and should not be delivered without as it would make us look bad as project.

**Comment by tsujan** [comment]
@agaida I know this isn't déjà vu; we had a discussion elsewhere.

When this issue was reported, people thought, "an icon theme that looks good over a dark background doesn't necessarily look good on a bright background" (quoted from the first comment) because they didn't know about symbolic SVG icons and how they change color.

To have a light color for SVG symbolic icons on a dark panel, you should assign a dark Qt theme to that panel -- and conversely. IMO, changing the icon theme is a bad idea and its implementation would have serious side effects... Murphy's law.

**Comment by tsujan** [comment]
A detailed explanation (which I might have given in another form elsewhere):

SVG symbolic icons solve the problem of contrast against different backgrounds. That's exactly the problem brought up here. However, *symbolic SVG icons only follow the widget style and its palette; they can't know anything about QSS or how dark/light it may be.*

Unfortunately, there's no general way of assigning different Qt palettes to different apps. Kvantum can do it; other Qt styles can't.

Therefore, IMO, a solution can be like this: Make it possible for each LXQt theme to have a simple Qt palette file (= color scheme) and add dark palettes to themes whose QSS files are dark, and conversely.

Such a solution will be without side effects. How it can be done is another question. Moreover, it is necessary because of the dichotomy between stylesheets and `QStyle` in Qt.

BTW, KDE's panel has exactly the same issue, at least, in its systray. It just tries to avoid it by using external icons in other places.

**Comment by agaida** [comment]
erm - i didn't know if we talk about the same thing. I explicitly talk about: User should be able to select an Icont theme for the panel/runner/any application - the follow color switch included. Easy as can be. And I'm really not interested in discussing hypothetical bugs again while i have a look onto my screen and see LXQt behaving the first time in may life the way i want it in that regard :dagger: 

Maybe I'm wrong about, but i'm not interested in what Qt can do or not - i'm in this case only interested in what i can do to set things like i want it - and hey, it really works that way. Might sound a bit harsh, but please understand that i want LXQt to look the way ***i want it*** - and now it does. And there are several ways to achive this i guess. Maybe a picture says more than thousand words so i will add a screenshot.

![](https://i.imgur.com/1ETSiqF.png)

And i migth like it to have different icon sets for the panel/runner and all other applications - why not, it should be possible:
![](https://i.imgur.com/vErx0m0.png)

And i know that this can lead to combinations where we run away crying and screaming - but it is possible on application level - thats all about. So we just need a sane way to handle it via UI.

**Comment by agaida** [comment]
BTW - the " It just tries to avoid it by using external icons in other places." is the tricky part - and it is not KDE, it seems to be a Qt thing depending on the icon size:

22px ![](https://i.imgur.com/oZS9cLW.png)

23 px and above
![](https://i.imgur.com/8k6kU0M.png)

**Comment by tsujan** [comment]
> why not, it should be possible

It's possible but makes Mr. Murphy angry. When I think only in terms of what I want, I may easily neglect other possible scenarios and break them.

On second thought, I withdraw my above suggestion because, in the last analysis, it means making a special style for LXQt -- like Breeze for KDE but with the difference that it should be able to assign different color schemes to different apps. That's simply impractical for 2 reasons: it requires a lot of work (who wants to do it?); and users may simply ignore it and use another style (a lot of effort for nothing).

The only remaining solution that comes to my mind is the possibility of setting the icons of widgets like volume control and removable media in the panel style -- like the main menu icon and like what KDE does. It shouldn't be so hard and won't have side effects either.

> and it is not KDE, it seems to be a Qt thing depending on the icon size:

No, it's the icon set. The symbolic icons of most sets are limited to ≤ 22-24 px.

Last but not least, think why others don't do that; are they stupid?

**Comment by tsujan** [comment]
This screenshot shows KDE with a dark widget style and a light panel:

![kde](https://user-images.githubusercontent.com/981076/44304475-e09fc880-a371-11e8-848c-04179e2ebcc4.png)

The network icon is white on a light bg. We aren't alone.

**Comment by tsujan** [comment]
![side_effect](https://user-images.githubusercontent.com/981076/44304569-80f6ec80-a374-11e8-81ab-bdcde3dbba16.png)

**Comment by rexxster** [comment]
Is qt5ct an option?

**Comment by agaida** [comment]
erm - re side effects - see it the other way round - this will happend everytime - even with no changes to the current state. But that doesn't change anything. Let me be more verbose:

* I provide a main icon theme and a rule how to react on different background colors - so far so good, implemented right now.
* This will work fine most of the time - but not in every situation.

Now the suggestion is: override some things for several applications - no problem technically. I'ts proven to work, in that special case with two different icon themes. Might be nuts or not, it is possible. A second thing that i don't have implemented right now is the switch that is implemented right now in config apperance. Overriding this switch  for  applications might help a lot to. And this is exactly what i suggested times ago. Will implement it the hard way right now and see what happend.

And to be honest - i don't see any pitfalls right now. It will not be worse than the current situation and don't change the general behaviour, because if implemented it will change the behaviour only for selected applications  - and that's all about. Finding a fine theme(s) for any use case will be up to the user - and thats it. :dark_sunglasses:

**Comment by tsujan** [comment]
The correct way:

![no_side_effect](https://user-images.githubusercontent.com/981076/44309056-b7b11f00-a3d5-11e8-8ab9-9dcacc18a91c.png)

The active theme is light, while the panel theme is dark.

This was just one example with Kvantum. There's nothing special in it that couldn't be implemented with other styles. Breeze title-bar already supports different color schemes for different apps.

The problem is neither ours nor in the icon set; it's in Fusion and Breeze. We don't need to be ashamed of it.

**Comment by agaida** [comment]
Given that the world outside is not perfect - i don't care about because we have this things already with our current implementation. What i do care about is to be able just to use things that are already there and more or less error free. Right now even that don't work.

Let's take the papirus icon them as example. Papirus comes with a bunch of available sets, which would be work fine if i had a more fine grained control over some aspects of the theme built in's. And that mean - i should be able to override at least panel and runner (the follow... switch and the theme).
That would be sufficient. Bonus points if the overrides could be just disabled.

If disabled there will be no different behaviour to our current implementation. If enabled $user or $distributor can do what he want to. Done. And that would be a major improvement over the current situation.

Result:
![](https://i.imgur.com/5JDqgIU.png)

**Comment by tsujan** [comment]
LOL! You've hidden the bad parts in your screenshot ;)

A question: With that, what happens to Panel's icons when you change the icon theme from Appearance → Icons Theme?

**Comment by agaida** [comment]
Let's take the upcoming Lubuntu release:

Current defaults (green ok, red not)
![](https://i.imgur.com/Abx0WND.png)

Turning Colorize icons off:
![](https://i.imgur.com/dRo2bFD.png)

So the team has exactly the choice between pest and cholera or a rock and a hard place. And this is not exactly the self promotion we should do as project - no, i don't hide anything :P

**Comment by agaida** [comment]
nothing - i have hard set the icon theme in the panel to papirus-dark - one can choose whatever one want. The only thing that has an effect on the panel appearance  is the colorize switch - so i would like to override it too.

**Comment by tsujan** [comment]
Whatever screenshot you attach, it just shows the feature poorness of Fusion or Breeze ;) Whoever uses a light Breeze/Fusion theme with a dark panel and sees dark icons on dark backgrounds should know where the problem comes from. *It is not ours.*

Sweeping this problem under the carpet will be wrong in the long run; it'll perpetuates an ignorance. Instead, someone could break this vicious circle and make KDE devs aware of the problem by using a KDE screenshot like the one I'd attached (forget about Qt devs). As I said above, the problem also exists in KDE but, again, swept under the carpet.

**Comment by tsujan** [comment]
> And this is not exactly the self promotion we should do as project

Nothing to be shamed of, IMO.

> no, i don't hide anything

White icons on light backgrounds of Panel's preferences dialogs. People are allowed to use Breeze ;)

**Comment by agaida** [comment]
so they have to live with the consequences - if providing the colorize hint with the theme that would help - if this is not possible i can live with that. Not nice, but better some not so often used dialogs are fucked up than the main desktop.

**Comment by agaida** [comment]
Re: Upstream awareness - Do you really think that devs who applaude this as an major improvement:
```
#ifndef Q_OS_WIN
    // Prohibit using sudo or kdesu (but allow using the root user directly)
    if (getuid() == 0) {
        if (!qEnvironmentVariableIsEmpty("SUDO_USER")) {
            std::cout << "Executing Dolphin with sudo is not possible due to unfixable security vulnerabilities." << std::endl;
            return EXIT_FAILURE;
        } else if (!qEnvironmentVariableIsEmpty("KDESU_USER")) {
            std::cout << "Executing Dolphin with kdesu is not possible due to unfixable security vulnerabilities." << std::endl;
            return EXIT_FAILURE;
        }
    }
#endif
```
will change the icon stuff or even understand the problems?
(source: dolphin main.cpp)

**Comment by tsujan** [comment]
> Do you really think that devs who...

LOL! No, I don't :D But they may not be the same devs.

Recently, I've seen some progress in this direction and think that's because new KDE devs do good things. Symbolic SVG icons were a brilliant idea too; they could just be used with their full potential if KDE devs implement different Breeze color schemes for different apps. It's very logical to do so because it's already possible with the Breeze title-bar.

I admit though that I may be too optimistic.

I won't kill myself if a setting is added to LXQt for a different icon theme for Panel -- I might do it myself when I see you want it so much and if no one does it -- but I won't get tired of saying to users, "it was a wrong decision; do so and so instead" ;)

**Comment by tsujan** [comment]
I started to work on this in my free time. Is the bottom of the GUI OK?

![config](https://user-images.githubusercontent.com/981076/44311615-d1675c00-a3ff-11e8-8c31-ccad2b614d1b.png)

The group-box has a tool-tip saying:
```
A workaround for widget styles that
cannot assign themes to applications.
```
I know that this info is too short and unclear but it's better than nothing, IMO; it shows that something's wrong and we've worked around it.

The combo lists icon themes and if one of them is selected, Panel icons change accordingly. It remains to save/read the setting.

**Comment by tsujan** [comment]
> don't forget the switch for the colorize override - that would be often enough.

You mean adding it to the tooltip, or something else?

**Comment by tsujan** [comment]
If you mean adding a check box for switching that option *here*, I think it's neither good nor possible. A hint is enough, IMO.

**Comment by tsujan** [comment]
The new tooltip:
```
A workaround for widget styles that
cannot assign themes to applications.

You might also want to disable:

LXQt Appearance Configuration →
Icons Theme →
Colorize icons based on widget style (palette).
```

**Comment by agaida** [comment]
ok

**Comment by tsujan** [comment]
@agaida: Frankly speaking, I'd never had such a bad PR: https://github.com/lxqt/lxqt-panel/pull/674

*Do* hesitate to merge it! I just wanted to see what was possible and what not. On the "bright" side, it's relatively small and can be reversed easily.

**Comment by tsujan** [comment]
BTW, overriding icon colorizing *only for Panel* is "somehow" possible but only with private headers and then, if the global option for colorizing is turned off and on, everything will be ruined. So, it can be forgotten peacefully ;)

**Comment by palinek** [comment]
@agaida @tsujan 
Wouldn't it be better to add config files with palettes into themes? So we would have e.g. `lxqt-panel.pal` together with `lxqt-panel.qss`, `lxqt-runner.pal` with `lxqt-runner.qss` ...

**Comment by tsujan** [comment]
@palinek That's what I suggested at https://github.com/lxqt/lxqt/issues/470#issuecomment-414088420 but couldn't do it from inside Panel's code. It can be done easily from a Qt style code (like in Kvantum) though; I don't understand why Breeze doesn't have it. If you know of a way of doing it, please make a PR.

**Comment by tsujan** [comment]
@palinek Actually, giving palettes to panel parts is easy but, when I tried it, it didn't work in that way....

**Comment by palinek** [comment]
How about http://doc.qt.io/qt-5/qapplication.html#setPalette and adding it into `LXQt::Application::updateTheme()`? Isn't it worth a try?

**Comment by tsujan** [comment]
> How about....

Tried it to no avail but, maybe, without patience. I suggest you try palettes too.

**Comment by palinek** [comment]
>

Tried with following patch for liblxqt:
```diff
diff --git a/lxqtapplication.cpp b/lxqtapplication.cpp
index dfb88f3..2218591 100644
--- a/lxqtapplication.cpp
+++ b/lxqtapplication.cpp
@@ -131,6 +131,9 @@ void Application::updateTheme()
 {
     const QString styleSheetKey = QFileInfo(applicationFilePath()).fileName();
     setStyleSheet(lxqtTheme.qss(styleSheetKey));
+    const QScopedPointer<QPalette> pal{lxqtTheme.palette(styleSheetKey)};
+    if (pal)
+        setPalette(*pal);
     emit themeChanged();
 }
 
diff --git a/lxqtsettings.cpp b/lxqtsettings.cpp
index 84bec7d..c496f40 100644
--- a/lxqtsettings.cpp
+++ b/lxqtsettings.cpp
@@ -35,6 +35,7 @@
 #include <QFileSystemWatcher>
 #include <QSharedData>
 #include <QTimerEvent>
+#include <QPalette>
 
 #include <XdgDirs>
 #if QT_VERSION < QT_VERSION_CHECK(5, 6, 0)
@@ -113,6 +114,7 @@ class LXQt::LXQtThemeData: public QSharedData {
 public:
     LXQtThemeData(): mValid(false) {}
     QString loadQss(const QString& qssFile) const;
+    QPalette * loadPalette(const QString& qssFile) const;
     QString findTheme(const QString &themeName);
 
     QString mName;
@@ -555,6 +557,27 @@ QString LXQtThemeData::loadQss(const QString& qssFile) const
 }
 
 
+/************************************************
+
+ ************************************************/
+QPalette * LXQtTheme::palette(const QString& module) const
+{
+    return d->loadPalette(QStringLiteral("%1/%2.pal").arg(d->mPath, module));
+}
+
+/************************************************
+
+ ************************************************/
+QPalette * LXQtThemeData::loadPalette(const QString& paletteFile) const
+{
+    QSettings pal_s{paletteFile, QSettings::IniFormat};
+    QVariant pal = pal_s.value(QStringLiteral("palette"));
+    if (pal.isNull() || !pal.canConvert<QPalette>())
+        return nullptr;
+
+    return new QPalette{qvariant_cast<QPalette>(pal)};
+}
+
 /************************************************
 
  ************************************************/
diff --git a/lxqtsettings.h b/lxqtsettings.h
index e3a5d8c..8167a19 100644
--- a/lxqtsettings.h
+++ b/lxqtsettings.h
@@ -147,6 +147,10 @@ public:
     */
     QString qss(const QString& module) const;
 
+    /*! \brief Returns palette (if exists and is successfully read) of the called module.
+    */
+    QPalette * palette(const QString& module) const;
+
     /*! \brief A full path to image used as a wallpaper
      \param screen is an ID of the screen like in Qt. -1 means default (any) screen.
                    Any other value greater than -1 is the exact screen (in dualhead).
```

With this and the "palette" settings file for e.g. ambiance generated like:
```c++
  QSettings pal_file{QLatin1String("panel.pal"), QSettings::IniFormat};
  QPalette pal{QColor{0x51, 0x50, 0x48}};
  pal.setColor(QPalette::Base, QColor{0x3c, 0x3b, 0x37});
  pal.setColor(QPalette::Disabled, QPalette::Base, QColor{0x4c, 0x4b, 0x47});
  pal.setColor(QPalette::Highlight, QColor{0xeb, 0x71, 0x40});
  pal.setColor(QPalette::Disabled, QPalette::Highlight, QColor{0xfb, 0x81, 0x50});
  qDebug() << Q_FUNC_INFO << pal;
  pal_file.setValue(QStringLiteral("palette"), pal);
```
which gives 
```
$ cat panel.pal 
[General]
palette="@Variant(\0\0\0\x44\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xffy\xf9xwlk\0\0\x1\x1\xff\xff\x65\x65\x64\x64ZZ\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xff\x36\x36\x35\x8b\x30\x30\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff<<;;77\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xeb\xebqq@@\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0\0\0\xff\xff\0\0\x1\x1\xff\xff\xff\xff\0\0\xff\xff\0\0\x1\x1\xff\xff(((($$\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xffy\xf9xwlk\0\0\x1\x1\xff\xff\x65\x65\x64\x64ZZ\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xff\x36\x36\x35\x8b\x30\x30\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xffLLKKGG\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xfb\xfb\x81\x81PP\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0\0\0\xff\xff\0\0\x1\x1\xff\xff\xff\xff\0\0\xff\xff\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xffy\xf9xwlk\0\0\x1\x1\xff\xff\x65\x65\x64\x64ZZ\0\0\x1\x1\xff\xff(\xa8('$$\0\0\x1\x1\xff\xff\x36\x36\x35\x8b\x30\x30\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff<<;;77\0\0\x1\x1\xff\xffQQPPHH\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xeb\xebqq@@\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0\0\0\xff\xff\0\0\x1\x1\xff\xff\xff\xff\0\0\xff\xff\0\0\x1\x1\xff\xff(((($$\0\0)"
```
we're getting (with breeze icon theme):
- with system theme
![screenshot](https://user-images.githubusercontent.com/10990929/44371090-71df7e00-a4dd-11e8-986c-b2dc07582147.png)

- with ambiance theme
![screenshot](https://user-images.githubusercontent.com/10990929/44371129-b5d28300-a4dd-11e8-916c-2a6d97c9a84f.png)

**Comment by tsujan** [comment]
Maybe I'm a little suggestible but, after all, it seems logical to be able to change the icon theme of a widget *that can have its own style(-sheet)*. It should have had its own icons too in the first.

Runner may need that too.

**Comment by palinek** [comment]
> The style plugin has the upper hand and can enforce its own palettes. Only style sheets can override what QStyle does.

Yes. And with the colorized icons we have problem, that the default (qApp) palette (which is used in xdgiconloader) doesn't match with the configured colors/palette in .qss (panel, runner ...). If we approximate the colors that are defined in .qss (in particular theme)  into the assigned qApp palette, the colorization can work.
The next step can be to completely remove usage of local colors in .qss and just use those from palette.

**Comment by tsujan** [comment]
> If we approximate the colors that are defined in .qss (in particular theme) into the assigned qApp palette, the colorization can work.

No, it won't make any difference because we want freedom with style-sheets :D Limiting their colors isn't an option.

Let's have icon set overriding!

**Comment by tsujan** [comment]
Everyone:

Please also note that stylesheets with dark and light elements are possible: the panel can be dark while the main menu can be light. It'll be up to the user to choose an appropriate icon set for such cases (and they exist).

**Comment by agaida** [comment]
@tsujan - it was not about win or lose - i was just a bit pissed because the only avialable choices was pest and cholera - now we have added flu. :P

**Comment by tsujan** [comment]
To me, this was a fruitful discussion. I still believe that all style plugins "should" be able to give different themes/color schemes to different apps but that's not the case in the real world. The more I tested, the more I learned that no other approach would work; being able to give a different icon set to the panel is the best approach, albeit with side effects.

**Comment by agaida** [comment]
@tsujan - and you are right, in a perfect world this should work. So we could consider the state now as a imperfect solution in an imperfect world :sunglasses:

And maybe we could poke some people to make our world more perfect.

**Comment by agaida** [comment]
@tsujan - and yes, the runner need this too

**Comment by tsujan** [comment]
@agaida Because of https://github.com/lxqt/lxqt/issues/470#issuecomment-414635225 , a perfect world is impossible -- even assigning a different theme wouldn't work in that case.

Style-sheets add flexibility and create problems at the same time. We can ignore the latter because of the former.

Advanced user can always make simple icon themes by inheriting/using the existing ones and put them in `~/.local/share/icons`.

**Comment by agaida** [comment]
Funny Fact: one of the icon themes that work out of the box without any magic is the good old faenza-darker 
So we can consider - if one add more magic to some themes the amount of side effects will grow non-linear to the used magic.

**Comment by tsujan** [comment]
The side effects I mentioned were all about symbolic SVG icons on config dialogs and other dialogs they may call. They won't exist if the theme has no symbolic SVG icon; it should just be good enough on both dark and light backgrounds.

**Comment by agaida** [comment]
right - and now we have a problem - teach users about these things
