### ISSUE TITLE
Change some icons to remove duplicates

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#576]
Hi,

Compton-conf: change the icon to something else since it's using the same icon as the display settings, which is mostly a screen/monitor icon so this isn't really intuitive.

lxqt-config-notificationd: preferences-desktop-notification would be much more intuitive.

lxqt-admin-time: preferences-system-time would be much more intuitive.

lxqt-admin-user: system-users or preferences-desktop-user would be much more intuitive.

**Comment by luis-pereira** [comment]
@sixsixfive Can you provide an patch ?

**Comment by Vladimir-csp** [comment]
for compton-conf there are preferences-system-windows or window-manager

**Comment by sixsixfive** [comment]
@luis-pereira 

do you rellay think i need a to create a patch for this? you just need to change the icon name in 4 text files:

https://github.com/lxde/compton-conf/blob/master/compton-conf.desktop.in
-Icon=preferences-desktop-display
+Icon=preferences-system-windows

...

**Comment by palinek** [comment]
> lxqt-config-notificationd: preferences-desktop-notification would be much more intuitive.
lxqt-admin-time: preferences-system-time would be much more intuitive.
lxqt-admin-user: system-users or preferences-desktop-user would be much more intuitive.

These components are using standard icon names defined by [xdg](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), so I'm not sure if we want to change them. @jleclanche, @luis-pereira, @paulolieuthier ?

I've changed the compton-conf icon -> it wasn't using one of the standard anyway...

**Comment by paulolieuthier** [comment]
I think we should stick to the standard.

**Comment by palinek** [comment]
...just note: the standard was last updated in 2006

**Comment by paulolieuthier** [comment]
Yeah, there are a lot of new icons, common between themes. But how to know we'll pick one widely supported?

**Comment by palinek** [comment]
Yes... that's the question :)

**Comment by paulolieuthier** [comment]
@jleclanche @luis-pereira what are your opinions on that?

**Comment by jleclanche** [comment]
My opinion is that the standard sucks and ideally we should ship our own fallbacks.

**Comment by luis-pereira** [comment]
I think we should use the standard icons whenever we can. When we need stuff that not's available,  I agree with @jleclanche, we should ship our own icons. Creating an coherent experience will not be easy. 
The standard it's an crystallized fossil from today's perspective.

**Comment by tsujan** [comment]
I told my (related) opinion at https://github.com/lxde/lxqt/issues/941 but @pmattern closed it. So, I repeat it here:

Sticking to current standards isn't a good approach to me. Being based on Qt, KDE is a good model to follow. KDE doesn't see "standard" as a sacred concept. I would consider an icon theme incomplete if it doesn't have `preferences-desktop-notification`, for example.

It's good to fulfill standards, but if that causes problems, I'll vote for following KDE.

**Comment by intialonso** [comment]
Just a note: Design and maintain icons could be a big deal, specially to achieve consistency with the user environment (dark, light, monochrome?). 

For example, have you seen the CMST icon? It looks absolutely out of place in almost every desktop.

**Comment by charwhee** [comment]
Have you considered asking Numix for some help with your icon/theming issues? Just a thought. 
https://numixproject.org/ They probably have some good experience in this type of issue, and maybe a good solution.

**Comment by Vladimir-csp** [comment]
Speaking of artistic theming and icons projects, I would also add [RAVEfinity](http://ravefinity.com/) in the mix.

**Comment by sixsixfive** [comment]
>For example, have you seen the CMST icon? It looks absolutely out of place in almost every desktop.

thats probably since your icon theme didn't include those icons or you didn't set the correct icon name( https://github.com/andrew-bibb/cmst/wiki/Icons-and-Icon-Themes ) ,since i don't have those issues:

![untitled](https://cloud.githubusercontent.com/assets/3780774/12619924/71b6e6d4-c51a-11e5-83ae-dee67d073329.png)

@recommendations

If you ever include a "default" LXQT icon set, keep in mind that you need to replace/remove many icons(trademarks eg: flash, chrome,steam, the bluetooth, usb, firewire logo icon etc.) since they are per definition illegal(the most usage rights for logos prohibit alternation of forms or colors). For the same reason they will also get blocked or patched on bigger distribution(eg debian dfsg).

**Comment by tsujan** [comment]
CMST uses different icons for its desktop file and window/taskbar. The taskbar icon is correct, as sixsixfive mentioned.

**Comment by ska67** [comment]
You are looking for icon names for the three apps lxqt-admin-user, lxqt-admin-time and lxqt-config-notificationd? Icon names that, in the absence of a standard, are used in existing icon sets?

I have tested some *-icon-theme packages in Debian (stretch), if the names suggested by @sixsixfive  are present.

`system-users` for **lxqt-admin-user**
Adwaita, breeze/breeze-dark, faba, faenza, gnome, human,
lxde, mate, matefaenza, moblin, moka, oxygen, tango

`preferences-desktop-user` for **lxqt-admin-user**
breeze/breeze-dark, moka, nuvola, oxygen

`preferences-system-time` for **lxqt-admin-time**
(Adwaita only with -symbolic suffix), breeze/breeze-dark, faba,
faenza, gnome, mate, matefaenza, moka, numix, oxygen

`preferences-desktop-notification` for **lxqt-config-notificationd**
breeze/breeze-dark, moka, (nuvola only with -bell suffix), oxygen

`preferences-desktop-notifications` for **lxqt-config-notificationd**
faba

`preferences-system-notifications` for **lxqt-config-notificationd**
Adwaita, gnome, mate. moka

Looks to me as if you could easily use `system-users` as icon name for lxqt-admin-user and `preferences-system-time` for lxqt-admin-time.
Using `preferences-desktop-notification` as icon name for lxqt-config-notificationd would not be a problem. because of the xdg algorithm, which falls back to `preferences-desktop`. And `preferences-desktop` exists in the gtk icon sets Adwaita, gnome, mate and moka.

Should more icon sets be tested or was the selection sufficient?

**Comment by stefonarch** [comment]
Nice work! 
I've tested just  plataro, nitrux, paper and papirus and they work fine too with your proposal.

**Comment by palinek** [comment]
@ska67 thanks

IMO... we can go with the `system-users-symbolic`, `preferences-system-time-symbolic` & `preferences-desktop-notification-symbolic`, because the 'preferences-system` & `preferences-desktop` are part of the XDG spec and `system-users` is widely supported by icon themes.

just my 2cents

**Comment by tsujan** [comment]
> we can go with the system-users-symbolic, preferences-system-time-symbolic...

Such icons -- with the suffix "-symbolic" -- are gnome-specific and aren't good with dark Qt themes because they don't change color.

**Comment by stefonarch** [comment]
Looks like  done as proposed https://github.com/lxqt/lxqt/issues/576#issuecomment-336751032
