### ISSUE TITLE
Qt4 applications do not get themed

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#692]
My main theme, set by lxappearance and obconf is "MediterreaneanLight" and my lxqt theme is "Ambiance".

All my windows are nice, except for juffed and virtualbox who dont follow.

![screen](https://cloud.githubusercontent.com/assets/3512979/8149859/9ccded3a-12d3-11e5-99b2-04bad05db5b3.jpg)

Impossible to change the top toolbar. What am I doing wrong, and if not, what files should I change manually ?

**Comment by Vladimir-csp** [comment]
Add parameter `style=GTK+` into section `[Qt]` of ~/.config/Trolltech.conf
Or use qtconfig-qt4 to select the style.

**Comment by pmattern** [comment]
Also, it would be interesting to know whether the JuffEd package in use was compiled against Qt 4 or Qt 5.

**Comment by paulolieuthier** [comment]
Yes, this issue is Qt4 related.

**Comment by paulolieuthier** [comment]
I guess we shouldn't remove Qt4 support from lxqt-qtplugin (834fc30677cf5abfb8d90209c79d9a4993cb8384) after all.

**Comment by Esclapion** [comment]
Works, thanks a lot. (I had not seen that it was qt4, I'll install the version Qt5 for juffed).

![screen](https://cloud.githubusercontent.com/assets/3512979/8150014/00aba784-12d9-11e5-874b-91c6444f7ad9.png)

Closed :-) :-)

**Comment by paulolieuthier** [comment]
Let's reopen, since it's a real issue.

**Comment by jleclanche** [comment]
I don't think it's worth it. Qt4 is mostly unsupported now.

**Comment by ypnos** [comment]
I second the sentiment that there is still need for the Qt4 plugin and I don't really understand why code that is already working is thrown out. There are several Qt4 applications out there and it is hard to tell if all of them will eventually get ported.

On my system without the plugin and even while using style=GTK+ in Trolltech.conf, Qt4 falls back to "hicolor" icon theme. That means that in applications many icons are just missing (because hicolor is so incomplete). I spent considerable time hunting this done, reading the sources of at least 10 Qt4 files. Eventually I fixed my problem by making Qt4 believe it is in a gnome environment.

**Comment by PCMan** [comment]
I'm the author of the plugin. Technically, supporting Qt4 is not that difficult.
Just add back the Qt4 code that was deleted previously.
The real problem is keeping the Qt4 and Qt5 versions in sync and do all the testing to make sure it still works.
If someone can help this part, I personally am not against supporting Qt4.

**Comment by ypnos** [comment]
I think this should be a separate module to avoid a general dependency on Qt4. I volunteer to maintain such a module if it is included in the lxqt project (obviously only if it meets your standards). Because I won't do this for myself alone, for myself I already found a workaround.

**Comment by agaida** [comment]
Qt4 should really considered dead - we have 2018 now, Qt 5.11 - if there are still bugs - bad luck, but we shouldn't spend a minute on it.
