### ISSUE TITLE
Fedora 23 and Rawhide Menu category selections missing.

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt#783]
Filed [bug report with Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1252581). Bug report includes screenshot. This is from a fresh install from Fedora 23 Alpha release and today's Rawhide .iso.

Qt5 packages are (truncated list, can provide full if you want);

```
Installed Packages
qt5-qtbase.x86_64               5.5.0-15.fc23 @System        
qt5-qtbase-common.noarch        5.5.0-15.fc23 @System        
qt5-qtbase-devel.x86_64         5.5.0-15.fc23 @System   
```

LXQt packages are;

```
lxqt-about.x86_64                  0.9.0-5.fc23       @System
lxqt-common.noarch                 0.9.1-5.fc23       @System
lxqt-config.x86_64                 0.9.0-6.fc23       @System
lxqt-globalkeys.x86_64             0.9.0-7.fc23       @System
lxqt-notificationd.x86_64          0.9.0-6.fc23       @System
lxqt-openssh-askpass.x86_64        0.9.0-6.fc23       @System
lxqt-panel.x86_64                  0.9.0-7.fc23       @System
lxqt-policykit.x86_64              0.8.0-7.fc22       @System
lxqt-powermanagement.x86_64        0.9.0-6.fc23       @System
lxqt-qtplugin.x86_64               0.9.0-6.fc23       @System
lxqt-runner.x86_64                 0.9.0-6.fc23       @System
lxqt-session.x86_64                0.9.0-6.fc23       @System
lxqt-theme-fedora.noarch           0.9.1-5.fc23       @System
```

Please let me know if you need any more information.

**Comment by pmattern** [comment]
Downstream packaging (dependency) issue, see comment on Red Hat bug tracker.

Nothing to discuss here.

**Comment by pmattern** [comment]
Turns out this may eventually not be as strictly downstream as I had thought:

LXQt panel is by default using file `lxqt-applications.menu` (provided by lxqt-common) which in turn references a bunch of files `lxde-*.directory` that are provided by lxmenu-data *only*. So lxmenu-data is a runtime- but not a build-dependency of lxqt-panel which isn't reflected in the code at all, though.
So far this didn't have too much consequences, most likely as lxmenu-data happens to be installed on the majority of systems as dependency of preexisting LXDE or whatever anyway. But as a matter of fact only the Arch Linux packages are depending on it, neither the ones from the *buntu PPA, Siduction or Fedora which was causing the issue mentioned by the OP.

I do not know whether there's some common approach regarding source code if it comes to
runtime-only dependencies like here.
But I wonder whether some modification of the code or something else is feasible which brings the dependency to downstream packagers' attention.

On a side-note it was considered to copy those files `lxde-*.directory` from lxmenu-data to lxqt-common in #437 which got refused in the end, in particular so as not to maintain two sets of those files in parallel.

**Comment by paulolieuthier** [comment]
@PCMan, @agaida, @luis-pereira what do you guys think of this?

**Comment by agaida** [comment]
No words without my lawyer :) - but lets be serious:
<pre>
 LANG=C aptitude why lxmenu-data
i   lximage-qt Depends libfm4 (>= 0.1.99)
i A libfm4     Depends lxmenu-data  
</pre>
So fortunally lximage-qt throw this dependency in for siduction - and because the most people, myself included, install metapackage lxqt - lximage-qt will be installed and nobody noticed the missed dependency. Can we make a test in cmake if the file exists (and create a hard dependency that way)? Maybe not the best of all ideas - but the only one i have. Maybe pkg-config would be a way too, but i have never worked with.

**Comment by paulolieuthier** [comment]
The menu files will eventually move to lxqt-common, but probably not in the next release. I think all we can do now is to document it so that the packagers will see it.

**Comment by agaida** [comment]
ok - seems to work, the base has changed and we still are in need of menu-handling improvements. But this one can be really closed.
