### ISSUE TITLE
Please increase liblxqt SOVERSION due to LxQt -> LXQt change.

### ISSUE THREAD

**Issue by czchen** [lxqt/lxqt#821]
In liblxqt commit [here](https://github.com/lxde/liblxqt/commit/f05ba5af5441602a4474e1f29e9934fecc77b5bf), all `LxQt` are changed to `LXQt`. However, the `SOVERSION` of liblxqt is not bumped after `LxQt` -> `LXQt` change. This kind of change cause the problem in distribution like Debian because it is API incompatible and we assume a library will remain API compatible if the `SOVERSION` is the same. Without changing `SOVERSION`, we are forced to use workaround which causes lots of compatibility problem in Debian and all its derivative.

To avoid the problem in distribution, please bump `SOVERSION`.

**Comment by jleclanche** [comment]
It'll be bumped on release. Why does debian care about what's on master?

**Comment by agaida** [comment]
Sorry, no offense, but you must be jokeing - packaging the release now is nuts and we both know it :)

**Comment by gilir** [comment]
That's a problem when you daily build master ... Without SONAME change, there is no way to know you have to rebuild every component because API change.

**Comment by agaida** [comment]
if you would daily build master - the problem would be not there - the builds would fail if symbols are included. (logs anyone?) - and once liblxqt is newly built the other packages would use the new builded library - and it is not the case that nobody knows or has mentioned the current problems for 3 weeks. It may sound unkind, but ignoring bugs and user complaints for more than three weeks is not really a upstream problem.

**Comment by gilir** [comment]
In the past, I try using symbols on C++ library, that was a nightmare, even on stable release (even my DD mentor advise me to remove them). Also, as it will fix the problem of API breakage, that will also break the build every time API change, and need an update of the package each time (and adding API on an upstream library is very often, and I don't have time to track every commit for it).

**Comment by agaida** [comment]
@gilir: in that special case i can help - you should join oftc #debian-lxqt. We have prepared a project for lxqt on alioth (pkg-lxqt) and we can host both the debian packaging and packaging for derivatives.
I've moved the siduction packaging already as we fight with the same problem. For you that means you could have branches for lubuntu-daily and lubuntu-$release. And you are right, fiddeling with symbols can be a major pain in the ass - but we have tools for it and have done this already. So please join the party, we would be glad about. :)

**Comment by gilir** [comment]
@agaida I was planning to use pkg-lxqt for official packages :-) For daily build, I can only use the master branch of a git tree on Launchpad, which is limited (packing upstream git with stable version packaging is sometimes incompatible).

**Comment by agaida** [comment]
ah, ok

**Comment by gilir** [comment]
Looks like the major version of the soname is still 0. Between 0.9.0 and 0.10.0, all the functions names changed ... Look like a major API changes fr me. If you don't change the soname for this type of event, you will never change it ... Except if you consider 0.X as unstable releases.

**Comment by jleclanche** [comment]
Guys, if we're going to need soname changes every release, we need to do something about their versioning - either they're done automatically when the lxqt version is changed,  or they're done manually at commit time when creating backwards-incompatible changes... I can't keep track of whether we're backwards compatible or not :/

**Comment by gilir** [comment]
The safest way is to make cmake bump the soname at every big release (not minor / bug fix release). I think some projects do this, but it's very annoying for a packaging point of view (especially debian based).
But, since liblxqt is a depend for every lxqt component, I'm sure you will not plan / want incompatible changes very often (more API additions than API modification). Or, in this case, maybe just do them just after the release, and all in one.
Using libraries is very useful, but maintaining them and packaging them is painful :-(

**Comment by luis-pereira** [comment]
This liblxqt release isn't even source compatible.
@jleclanche we definitely need a systematic way to handle this kind of stuff although I'm not sure what's the best way to do it.

**Comment by agaida** [comment]
we will not need a so bump with every new version - come on, be creative :) - to be true, it would be a fucking pita, because the would mean a new package every new version that has to go through debian NEW queue. And this is not funny.

But there is a solution - introducing a virtual package. In debian it would look like:

Package: liblxqt0
Provides: lxqt-abi-0-10-0

and in the corresponding symbols (first line):
liblxqt.so.0 liblxqt0 #MINVER#, lxqt-abi-0-10-0

There might be better solutions like:
liblxqt.so.0 liblxqt0 #MINVER#
| liblxqt0 #MINVER#, lxqt-abi-0-10-0

aka an alternative symbols layout, that will be only used by packages that really depend on the symbols in charge - and add the lxqt-abi- dependency only to those packages.

and there is something that we can do as upstream to avoid problems: Please don't make incompatible changes - if a new interface is needed, deprecate the old one, leave the interface intact and never use it again - remove the crap some versions later (or let it bitrot)

new functions with new interfaces that add new symbols will be ok - these new interfaces create additional symbols and these symbols will be ok packaging wise.

PS: One could have a look, how the Qt guys handle this - i borrowed the idea with the virtual package and the alternative symbols layout from them. https://www.debian.org/doc/debian-policy/ch-sharedlibs.html -might be an interesting reading, esp. 8.6.3.2 The symbols File Format and the alternative Formats

**Comment by agaida** [comment]
btw - doing it the way with the symbols and the virtual package the dependencies of liblxqt could look like this:
<pre>
~$ LANG=C aptitude show liblxqt0
Package: liblxqt0                        
New: yes
State: installed
Automatically installed: no
Multi-Arch: same
Version: 0.10.0-2
Priority: optional
Section: libs
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 505 k
Depends: libc6 (>= 2.14), libkf5windowsystem5 (>= 4.96.0), libqt5core5a (>= 5.5.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.2.0),
         libqt5widgets5 (>= 5.2.0~rc1), libqt5xdg1 (>= 1.0.0), libstdc++6 (>= 4.1.1)
Provides: lxqt-abi-0-10-0
Description: Shared libraries for LXQt desktop environment (libs)
</pre>
<pre>
~$ LANG=C aptitude show lxqt-about
Package: lxqt-about                                                                                                                    
New: yes
State: installed
Automatically installed: no
Version: 0.10.0-2
Priority: optional
Section: x11
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 188 k
Depends: libc6 (>= 2.14), liblxqt0 (>= 0.9.0+20150911), libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2),
         libqt5xdg1 (>= 1.0.0), libstdc++6 (>= 4.1.1), lxqt-abi-0-10-0
Description: About screen for LXQt
</pre>
