### ISSUE TITLE
how to autostart (multiple) commands?

### ISSUE THREAD

**Issue by excalibur1234** [lxqt/lxqt#888]
i am talking about the settings --> lxqt settings --> session configuration --> autostart option. in that menu, you can click "add" in order to add an autostart application. you can enter the name and command you want to autostart in a pop up window.

until about half a year ago (or longer) all of the following autostart commands worked:
xmodmap ~/.Xmodmap
xmodmap ~/.Xmodmap && sleep 5
sleep 5 && xmodmap ~/.Xmodmap
sh -c "xmodmap ~/.Xmodmap"
sh -c "sleep 5 && xmodmap ~/.Xmodmap"
now, only these autostat commands work:
xmodmap ~/.Xmodmap
sh -c "xmodmap ~/.Xmodmap"

do you see a pattern there? 
every autostart command, which consists of more than one command (and uses && to connect these commands) does NOT work (anymore).

i have noticed that bug before and i worked around it by autostarting a bash script (with a single command), which contains multiple commands. 

was this feature removed intentionally?
in that case, it would be nice to have an error message pop up window, which explains that autostarting multiple commands is not supported.

**Comment by Vladimir-csp** [comment]
Autostart is handled by XDG spec now via .desktop entries. So what you set in 'command' field should comply to desktop entry spec, and it does not allow naked shell constructs.

**Comment by Vladimir-csp** [comment]
`sh -c "sleep 5 && xmodmap ~/.Xmodmap"` - this should work though.

**Comment by pmattern** [comment]
Yep. A related discussion took placer a while ago in #737.

**Comment by palinek** [comment]
`lxqt-session-config` is suited to configure autostarting a executable -> creating a .desktop file with *Exec* key with (escaped) executable.

@excalibur1234 if you need to to run something as you described, you should:
- create a shell script and configure to autostart it with `lxqt-session-config`
- or create the autostart .desktop file manualy in ~/.config/autostart with exec key like described above `sh -c "..."`

@luis-pereira IMO there is a problem with logic editing existing autostart. If there are special chars in the exec key in edited .desktop autostart file, after dialog submit w/o any change the particular .desktop file is changed (due to escaping/unescaping)

**Comment by luis-pereira** [comment]
@palinek Will take a look
