### ISSUE TITLE
[lxqt-sudo] Consider (not) preserving of environment with sudo backend

### ISSUE THREAD

**Issue by palinek** [lxqt/lxqt#899]
There are objections on lxqt-sudo's behaviour in #874:

| . | . |
| --- | --- |
| @pmattern | As of lxde/pcmanfm-qt@4af5a3e the settings when running instances by "Open as Root" get saved correctly using gksu both with su and sudo as backend or lxsu but not with lxsudo. This makes me wonder about the advantages of the said unification given that the behaviour in PCManFM-Qt can surely be considered a disadvantage. |
| @Vladimir-csp | IMHO, preserving such a big chunk of environment into an elevated session is not secure. lxsudo should preserve no more than sudo does or just reuse whatever sudo is based on. Bits of user's configuration shouldn't leak into elevated session. In case of sudo the only user-related vars present in sudo environment are: XAUTHORITY, SUDO_USER and SUDO_UID |

... opening a separate thread for discussion related to this.

**Comment by palinek** [comment]
This is the criticised commit lxde/lxqt-sudo@54a40f7... That means lxqt-sudo isn't doing anything special on its own, just using the -E parameter of sudo.
I've added that for following reasons:
- unify the provided functionality no matter what backend is used (lxqt-sudo user should get the same functionality for both su & sudo)
- many environment variables are used by GUI applications and they tend to be ugly in case the environment is stripped (e.g. the said pcmanfm-qt doesn't use icons set by the theme)
- preserving the environment with sudo doesn't make lxqt-sudo any much unsecure than the sudo is by itself (preserving environment can be denied by sudo's configuration)

**Comment by Vladimir-csp** [comment]
GUI issues are to be expected, since an app is run by different user (e.g. root), which has different or absent theme configuration. This is logical.
But the reverse issues are bigger - apps run by different user create their files in current user's dir resulting in ownership problems. That is not a cosmetic issue.
IMHO, lxsudo should attend to default backend configuration. If sudo is configured not to preserve environment, do the same by default.

**Comment by agaida** [comment]
Right now we have two possible implemementations:
* https://github.com/lxqt/lxqt-sudo/pull/22
* https://github.com/lxqt/lxqt-sudo/pull/30

We should discuss both without bias and make a decision

**Comment by palinek** [comment]
> We should discuss both without bias and make a decision

Just make it clear:
- lxqt/lxqt-sudo#22 -> whitelist -> strip everything except well known
- lxqt/lxqt-sudo#30 -> blacklist -> leave everything except well known

**Comment by agaida** [comment]
Ok - thanks for doing the first step - thought about it a lot and like the whitelist approach far better, all the fun that approch will bring included (angry users because we are to strict or forget something). 

And esp. i like the thing that the environment things like application styles and so not are whitelisted by default. It might sound strange, but i want the applications looking different when running as root - that doesn't mean that they have to be fugly. They have only to run with the settings for root - that give me the chance to see at the first view if a application is running as root. Tsujan - and in know that you don't will follow, esp. with the design and look thing :smile:

**Comment by tsujan** [comment]
> but i want the applications looking different when running as root

That's just a workaround for poor widget styles ;) I give a special Kvantum theme to root apps -- I don't want a bad but a *different* look for them.

Frankly, [I really need my blacklist approach](https://github.com/lxqt/lxqt-sudo/pull/30#issuecomment-365675009) and will keep using it.

**Comment by agaida** [comment]
tststs - why i'm not surprised - without kvantum i was forced to set a good looking theme for root :P

**Comment by agaida** [comment]
ok - back to be serious: is it possible to switch the environmental thing with a (to be created) config option? God damn, i don't want to take away the users choice for users to aim and shoot in boot feets or knees ...

**Comment by tsujan** [comment]
Since lxqt-sudo isn't changed rapidly, I could patch it for my personal use once in a while if @palinek's patch is merged. Users may not complain and if they do, it won't be a disaster. So, as far as I am concerned, you could merge the whitelist approach :)

**Comment by tsujan** [comment]
BTW, are you sure that the whitelist approach gives a poor look?

**Comment by agaida** [comment]
not in every case - but i noticed that in my former aproaches since 2009

**Comment by tsujan** [comment]
*Merge it!* I also have to patch pcmanfm-qt heavily once in a while (personal things I'm sure wouldn't be accepted). Since I am the only one who likes the blacklist approach, there's no reason to hesitate.

**Comment by agaida** [comment]
OK

**Comment by palinek** [comment]
done

**Comment by tsujan** [comment]
@agaida I think the whitelist approach (merged now) shouldn't have any problem with root style settings -- they may be the same for both approaches.
