### ISSUE TITLE
size of text widgets of lxqt widgets

### ISSUE THREAD

**Issue by Esclapion** [lxqt/lxqt#997]
The text size of widgets desktopswitch and clock doesn't follow that of the icons in lxqt panel :

![wid](https://cloud.githubusercontent.com/assets/3512979/14045151/da1f93a6-f297-11e5-9dcb-ecea3e61f1d9.png)

**Comment by palinek** [comment]
I don't follow. What's the issue about?

**Comment by intialonso** [comment]
I guess he expect the font to escalate with the icons, Im not sure.

**Comment by Esclapion** [comment]
Exactly. I we use big icons, the text remains small, and it's bad to see.

**Comment by tsujan** [comment]
When I put myself in a new LXQT user's shoes, I see the situation this way:

Like other widgets, the font size of the panel is set in Configuration Center → Appearance → Font. The clock is OK because its font can be set separately. Panel icon sizes can be defined in Configure Panel → Panel → Size. So far, so good! However, there seems to be no way of changing the Panel font and its size without changing them globally.

Now, there can be different solutions:

(1) Adding custom font options to each widget;
(2) Adding font options to Configure Panel → Panel → Size (or Custom styling);
(3) Setting the font size according to the icon size in the code.

IMO, the third way is not good because different fonts may need to have different sizes.

**Comment by intialonso** [comment]
Why would you want a different font size in your panel than in the rest of your system? If you have eye problems the logic is to set ALL of your fonta to a big size, and that is what the global settings do.

Im against having different configurable font sizes for everything. It will lead to a incoherent UI, and redundant code.

**Comment by tsujan** [comment]
> Why would you want a different font size in your panel...

The answer is this very issue! When there's a setting for changing a widget's icon size, there should be another setting for changing its font size.

**Comment by Esclapion** [comment]
"The clock is OK because its font can be set separately.". I don't see how, else...

If i can do it manually, ok, but ?

**Comment by tsujan** [comment]
> If i can do it manually, ok, but ?

Oh, sorry! I meant World Clock, which I use instead of "Date & time". I don't see any need to the latter when the former exists.

**Comment by tsujan** [comment]
> Im against having different configurable font sizes for everything. It will lead to a incoherent UI, and redundant code.

I forgot this part. Your argument isn't acceptable to me because:

(1) Here we're talking about a UI that's incoherent exactly because there's no font and font size setting for it;
(2) A code that enables users to set up a GUI according to their preferences can never be called "redundant" -- it's a feature. As far as I've known, we don't want to follow Gnome dev's policy of "minimalism". The goal is to provide users with a lightweight, advanced and configurable DE.

If a piece of code interferes with LXQT's lightness (with no good reason), I'll also consider it redundant.

**Comment by Esclapion** [comment]
(a bit off-topic)
> I meant World Clock, which I use instead of "Date & time". I don't see any need to the latter when the former exists.

How  can i get it (manjaro, so arch), please ?

**Comment by intialonso** [comment]
> (1) Here we're talking about a UI that's incoherent exactly because there's no font and font size setting for it;

I see the panel (and all what lxqt is) like a part in a system, not like independent pieces. What Im trying to say, is that (visually) having different font sizes in your windows, widget, panel, menus, etc is incoherent.

Esclapion had a problem some days ago with the color font and panel background because the "custom color setting", sometimes all that extra configuration options can lead to problems like that one.

But, again, that is my opinion as a designer, so if the setting are easy to include and mantain, I dont see a problem (but I think we are short in man power, and there is some features and bugs that should be priorized).

What if we put that options under an "advanced" category?

**Comment by Esclapion** [comment]
I always have this color problem, because the white color in the panel follows that of the theme. For the moment, i use a compromise.

**Comment by intialonso** [comment]
@Esclapion It should be in your installation by default, under the Add plugins option from the panel.

![instantanea1](https://cloud.githubusercontent.com/assets/7544231/14056702/7368e1a0-f2bd-11e5-9a24-912018ddc960.png)

**Comment by Vladimir-csp** [comment]
This might bring back the old discussion about default/no theme state for panel.
By the way, how does font size work from toolkit's point of view?
In GTK there is the font-name property with name and size, either in GTK config or in Xsettings. How does Qt do it?

I think, apps should take font size from some generic configuration (LXQt appearance settings in this case). But they could have an override (off by default). This way they would fit as part of the whole, but also have an ability to stand apart.

**Comment by Esclapion** [comment]
Found, my bad. But you can set the size separately ? I will investigate.

**Comment by tsujan** [comment]
> there is some features and bugs that should be priorized

I agree.

BTW, as an example of what may be said to be redundant, IMO "Date & time" can be removed because all of its functionality and more can be found in World Clock. I guess "Date & time" was made first and World Clock later. The "maximalism" of KDE isn't a good pattern to follow either.

> Found, my bad. But you can set the size separately ?

Display format → Advanced manual format → Customize. Try something like:
````
'<font size="4"><b>'hh:mm:ss a '</b>'
````
I don't know why the meaning of font size is different here but the point is that it works.

**Comment by tsujan** [comment]
> I think, apps should take font size from some generic configuration (LXQt appearance settings in this case).

Yes, and most of them do so. But some special apps, like the panel, need to override it optionally because of the jobs they do. Those are usually the apps whose icon size can be set separately.

**Comment by Vladimir-csp** [comment]
> >  I think, apps should take font size from some generic configuration (LXQt appearance settings in this case).

> Yes, and most of them do so. But some special apps, like the panel, need to override it optionally because of the jobs they do. Those are usually the apps whose icon size can be set separately.

The rest of my message says relatively the same.

**Comment by szg0000** [comment]
New feature needed for adjust the font size of time and the date. Especially when "Show date below time on new line" feature selected.

**Comment by agaida** [comment]
Why? Strings like the following are possible right now:
'<b>'HH:mm:ss'</b><br/><font size="-2">'ddd, d MMM yyyy'</font>'

**Comment by tsujan** [comment]
"Date & time" was removed. The rest was a chat.
